import {chromium} from 'playwright';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {SAMPLE_DEALS,summarize} from '../src/executive-dashboard.mjs';
const root=process.cwd();
assert.equal(summarize(SAMPLE_DEALS.filter(r=>r.quarter===3),6).revenue,15435000);assert.equal(summarize(SAMPLE_DEALS.filter(r=>r.quarter===3),6).forecast,22809500);
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.SITE_URL||'http://127.0.0.1:4173/kc-kuto-crm/');await page.getByRole('button',{name:'เข้าใช้งานโหมดทดลอง',exact:true}).click();await page.getByRole('button',{name:'แดชบอร์ดผู้บริหาร',exact:true}).click();
 if(width>=1024){await page.getByRole('button',{name:'ซ่อนแถบเมนู',exact:true}).click();await page.waitForFunction(()=>document.getElementById('crm-desktop-sidebar').getBoundingClientRect().width===0);await page.getByRole('button',{name:'แสดงแถบเมนู',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('crm-desktop-sidebar').getBoundingClientRect().width>180);await page.getByRole('button',{name:'ซ่อนแถบเมนู',exact:true}).click();await page.reload();await page.getByRole('button',{name:'แสดงแถบเมนู',exact:true}).waitFor();await page.getByRole('button',{name:'แสดงแถบเมนู',exact:true}).click();await page.getByRole('button',{name:'แดชบอร์ดผู้บริหาร',exact:true}).click();}const dash=page.locator('.exec-sample');await dash.getByRole('heading',{name:'ภาพรวมธุรกิจสำหรับผู้บริหาร'}).waitFor();assert.equal(await dash.locator('.exec-kpi').count(),6);assert.ok((await dash.locator('.exec-kpi').first().innerText()).includes('15.44'));
 await page.screenshot({path:path.join(root,'test-artifacts/executive-'+width+'.png'),fullPage:true});
 await dash.getByRole('heading',{name:'Pipeline ตามขั้นตอนการขาย'}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'test-artifacts/executive-charts-'+width+'.png')});await dash.getByLabel('ทีมขาย',{exact:true}).selectOption('Enterprise');assert.equal(await dash.locator('.exec-text-button').count(),2);const teamValue=await dash.locator('.exec-kpi').first().innerText();assert.ok(!teamValue.includes('15.44'));
 await dash.locator('.exec-text-button').first().click();assert.equal(await dash.getByLabel('พนักงานขาย',{exact:true}).inputValue(),'S01');assert.equal(await dash.locator('.exec-text-button').count(),1);
 await dash.getByLabel('ไตรมาส',{exact:true}).selectOption('2');assert.ok((await dash.locator('.exec-snapshot').innerText()).includes('30 มิ.ย.'));
 await dash.getByLabel('ทีมขาย',{exact:true}).selectOption('all');assert.equal(await dash.locator('.exec-text-button').count(),6);
 await dash.getByRole('button',{name:/^ดูรายละเอียด DEMO/}).first().click();await dash.getByRole('region',{name:'รายละเอียดดีลตัวอย่าง'}).waitFor();await dash.getByRole('button',{name:'ปิดรายละเอียด',exact:true}).click();assert.equal(await dash.locator('.exec-detail').count(),0);
 const download=page.waitForEvent('download');await dash.getByRole('button',{name:'ส่งออกข้อมูลตัวอย่าง CSV',exact:true}).click();const d=await download;assert.equal(d.suggestedFilename(),'DEMO-executive-Q2-2026.csv');const file=await d.path();assert.equal(fs.readFileSync(file,'utf8').split('\r\n').length,73);
 await dash.locator('summary').click();assert.ok(await dash.getByText('ข้อมูลจำลองสร้างเพื่อสาธิตเท่านั้น',{exact:false}).isVisible());
 await page.getByRole('button',{name:'เปลี่ยนเป็นภาษาอังกฤษ',exact:true}).click();await dash.getByRole('heading',{name:'Executive business overview'}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByRole('button',{name:'Existing system dashboard',exact:true}).click();assert.equal(await page.locator('.exec-sample').count(),0);await page.getByRole('button',{name:'Executive sample data',exact:true}).click();await page.locator('.exec-sample').waitFor();assert.deepEqual(errors,[]);await page.close();
}console.log('PASS executive dashboard: reconciled totals, team/quarter/seller filters, detail, CSV, definitions, bilingual, legacy toggle, desktop/mobile');}finally{await browser.close();}
