begin;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='admin' and is_active limit 1),true);
set local role authenticated;
do $$
declare a uuid; b uuid; item uuid; serial_item uuid; tx uuid:=gen_random_uuid(); p jsonb; failed boolean; c uuid; t uuid; r uuid; part uuid;
begin
 insert into public.crm_warehouses(code,name) values('QA_INV_A','QA Inventory A') returning id into a;
 insert into public.crm_warehouses(code,name) values('QA_INV_B','QA Inventory B') returning id into b;
 update public.crm_inventory_settings set enabled=true,allow_negative=false,default_warehouse_id=a where id;
 item:=public.crm_inventory_save_item(jsonb_build_object('name','QA Inventory Part','code','QA_INV_PART','unit','pc','price',20,'cost',10,'stock_mode','stock'));
 p:=jsonb_build_object('id',tx,'kind','opening','item_id',item,'warehouse_id',a,'quantity',10,'reason','QA rollback');
 perform public.crm_inventory_post(p);perform public.crm_inventory_post(p);
 if (select quantity from public.crm_stock_balances where warehouse_id=a and item_id=item)<>10 then raise exception 'Idempotency failed'; end if;
 failed:=false;begin perform public.crm_inventory_post(p||jsonb_build_object('quantity',11));exception when others then failed:=true;end;if not failed then raise exception 'ID payload conflict accepted';end if;
 perform public.crm_inventory_post(jsonb_build_object('id',gen_random_uuid(),'kind','transfer','item_id',item,'warehouse_id',a,'to_warehouse_id',b,'quantity',4,'reason','QA transfer'));
 if (select sum(quantity) from public.crm_stock_balances where item_id=item)<>10 then raise exception 'Transfer conservation failed';end if;
 failed:=false;begin perform public.crm_inventory_post(jsonb_build_object('id',gen_random_uuid(),'kind','issue','item_id',item,'warehouse_id',a,'quantity',7,'reason','QA overissue'));exception when others then failed:=true;end;if not failed then raise exception 'Negative stock accepted';end if;
 if (select quantity from public.crm_stock_balances where warehouse_id=a and item_id=item)<>6 then raise exception 'Failed posting changed stock';end if;
 failed:=false;begin update public.crm_stock_balances set quantity=99 where item_id=item;exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'Direct balance write accepted';end if;
 failed:=false;begin delete from public.crm_stock_movements where item_id=item;exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'History deletion accepted';end if;
 failed:=false;begin update public.crm_price_items set unit='box' where id=item;exception when others then failed:=true;end;if not failed then raise exception 'Unit mutation accepted';end if;
 serial_item:=public.crm_inventory_save_item(jsonb_build_object('name','QA Serial','code','QA_INV_SN','unit','pc','price',20,'cost',10,'stock_mode','stock','track_serial',true));
 perform public.crm_inventory_post(jsonb_build_object('id',gen_random_uuid(),'kind','receipt','item_id',serial_item,'warehouse_id',a,'quantity',1,'serial_number','QA-SN1','reason','QA serial'));
 failed:=false;begin perform public.crm_inventory_post(jsonb_build_object('id',gen_random_uuid(),'kind','receipt','item_id',serial_item,'warehouse_id',b,'quantity',1,'serial_number','QA-SN1','reason','QA duplicate'));exception when others then failed:=true;end;if not failed then raise exception 'Duplicate serial accepted';end if;
 perform public.crm_inventory_post(jsonb_build_object('id',gen_random_uuid(),'kind','transfer','item_id',serial_item,'warehouse_id',a,'to_warehouse_id',b,'quantity',1,'serial_number','QA-SN1','reason','QA SN transfer'));
 if (select quantity from public.crm_stock_balances where warehouse_id=b and item_id=serial_item)<>1 then raise exception 'Serial transfer failed';end if;
 insert into public.customers(name) values('QA inventory service rollback') returning id into c;
 insert into public.tickets(subject,customer_id,assigned_to_id) values('QA inventory service issue',c,auth.uid()) returning id into t;
 insert into public.crm_service_repairs(ticket_id,engineer_id) values(t,auth.uid()) returning id into r;
 insert into public.crm_service_parts(ticket_id,repair_id,part_no,name,quantity,unit) values(t,r,'QA_INV_PART','QA Inventory Part',2,'pc') returning id into part;
 perform public.crm_inventory_post(jsonb_build_object('id',gen_random_uuid(),'kind','issue','item_id',item,'warehouse_id',a,'quantity',2,'reason','QA service part','service_part_id',part));
 if not exists(select 1 from public.crm_service_parts sp join public.crm_stock_movements m on m.id::text=sp.inventory_reference where sp.id=part and m.service_part_id=part) then raise exception 'Service issue linkage missing';end if;
 failed:=false;begin update public.crm_service_parts set quantity=3 where id=part;exception when others then failed:=true;end;if not failed then raise exception 'Issued part was editable';end if;
 failed:=false;begin perform public.crm_inventory_post(jsonb_build_object('id',gen_random_uuid(),'kind','issue','item_id',item,'warehouse_id',a,'quantity',2,'reason','QA duplicate part','service_part_id',part));exception when others then failed:=true;end;if not failed then raise exception 'Service part issued twice';end if;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 failed:=false;begin perform public.crm_inventory_post(p);exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'Inactive/unknown user posting accepted';end if;
 if exists(select 1 from public.crm_stock_balances) then raise exception 'Unknown user could read inventory';end if;
end $$;
reset role;
rollback;
select 'PASS: stock conservation, retry idempotency, insufficient-stock rollback, serial uniqueness, immutable balances/history, unit locking, service issue linkage and access denial; all fixtures rolled back' result;
