import {chromium} from 'playwright';import assert from 'node:assert/strict';import {openThaiSettings} from './menu-helper.mjs';
const browser=await chromium.launch({headless:true});try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.SITE_URL||'http://127.0.0.1:4173/kc-kuto-crm/');await page.getByRole('button',{name:'เข้าใช้งานโหมดทดลอง',exact:true}).click();await openThaiSettings(page,width);await page.getByRole('searchbox',{name:'ค้นหาเมนูตั้งค่า'}).fill('ข้อมูลหลัก');await page.getByRole('button',{name:'ข้อมูลหลัก',exact:false}).filter({visible:true}).click();
 await page.getByRole('button',{name:'หน่วย',exact:true}).click();await page.getByRole('button',{name:'เพิ่มรายการ',exact:true}).click();const master=page.getByRole('form',{name:'แบบฟอร์มข้อมูลหลัก'});await master.getByLabel('Code',{exact:true}).fill('PC');await master.getByLabel('ชื่อ (ไทย)',{exact:true}).fill('ชิ้น');await master.getByLabel('ชื่อ (EN)',{exact:true}).fill('Piece');await master.getByRole('button',{name:'บันทึก',exact:true}).click();await page.getByRole('status').filter({hasText:'บันทึกเฉพาะโหมดทดลอง'}).waitFor();await page.getByRole('button',{name:'กลับไปหน้าตั้งค่าทั้งหมด',exact:true}).click();await page.locator('.crm-category-card').getByText('สินค้าและคลัง',{exact:true}).click();await page.getByRole('heading',{name:'สินค้าและคลัง',exact:true}).waitFor();
 const dialog=page.getByRole('dialog',{name:'จัดการสินค้าและคลัง'});const save=async()=>{await dialog.getByRole('button',{name:'บันทึก',exact:true}).click();await Promise.race([dialog.waitFor({state:'hidden'}),dialog.getByRole('alert').waitFor()]);assert.equal(await dialog.getByRole('alert').count(),0,await dialog.getByRole('alert').allTextContents());};
 await page.getByRole('button',{name:'คลังสินค้า',exact:true}).click();for(const code of ['WH-A','WH-B']){await page.getByRole('button',{name:'เพิ่มคลังสินค้า',exact:true}).click();await dialog.getByLabel('รหัสคลัง',{exact:true}).fill(code);await dialog.getByLabel('ชื่อคลัง',{exact:true}).fill(code);await save();}
 await page.getByRole('button',{name:'ตั้งค่าคลัง',exact:true}).click();await page.getByRole('button',{name:'แก้ไขการตั้งค่าคลัง',exact:true}).click();await dialog.getByLabel('เปิดการควบคุมสต็อก',{exact:true}).check();await dialog.getByLabel('คลังเริ่มต้น',{exact:true}).selectOption({label:'WH-A · WH-A'});await save();
 await page.getByRole('button',{name:'สินค้าและบริการ',exact:true}).click();await page.getByRole('button',{name:'เพิ่มสินค้าและบริการ',exact:true}).click();await dialog.getByLabel('รหัส (ว่างเพื่อสร้างอัตโนมัติ)',{exact:true}).fill('INV-001');await dialog.getByLabel('ชื่อ',{exact:true}).fill('อะไหล่ทดสอบ');await dialog.getByLabel('การควบคุมสต็อก',{exact:true}).selectOption('stock');await dialog.getByLabel('หน่วยสินค้าหลัก',{exact:true}).selectOption('ชิ้น');await dialog.getByLabel('ราคาขาย',{exact:true}).fill('500');await page.screenshot({path:`test-artifacts/inventory-item-${width}.png`,fullPage:true});await save();
 async function movement(kind,qty,destination){await page.getByRole('button',{name:'รับ–จ่าย / โอนสินค้า',exact:true}).click();await dialog.getByLabel('ประเภทรายการ',{exact:true}).selectOption(kind);await dialog.getByLabel('สินค้า',{exact:true}).selectOption({label:'INV-001 · อะไหล่ทดสอบ'});await dialog.getByLabel('จำนวน (ปรับปรุงใช้ค่าบวก/ลบ)',{exact:true}).fill(String(qty));await dialog.getByLabel('เหตุผล / เลขเอกสารอ้างอิง',{exact:true}).fill('QA movement');if(destination)await dialog.getByLabel('คลังปลายทาง',{exact:true}).selectOption({label:'WH-B · WH-B'});}
 await movement('opening',10);await save();await movement('transfer',4,true);await save();await movement('issue',7);await dialog.getByRole('button',{name:'บันทึก',exact:true}).click();await dialog.getByRole('alert').filter({hasText:'Insufficient stock'}).waitFor();await dialog.getByRole('button',{name:'ยกเลิก',exact:true}).click();
 await page.getByRole('button',{name:'ยอดคงเหลือและจุดแจ้งเตือน',exact:true}).click();const row=page.getByRole('row').filter({hasText:'WH-A'}).filter({hasText:'INV-001'});await row.getByRole('cell',{name:'6',exact:true}).waitFor();await page.getByRole('button',{name:'กำหนดจุดแจ้งเตือน',exact:true}).click();await dialog.getByLabel('สินค้า',{exact:true}).selectOption({label:'INV-001 · อะไหล่ทดสอบ'});await dialog.getByLabel('จำนวนแจ้งเตือน',{exact:true}).fill('6');await save();await row.getByRole('cell',{name:'ควรเติมสินค้า',exact:true}).waitFor();await page.getByRole('button',{name:'โหลดใหม่',exact:true}).click();await row.getByRole('cell',{name:'6',exact:true}).first().waitFor();await page.screenshot({path:`test-artifacts/inventory-balances-${width}.png`,fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'no page overflow');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'ส่งออก CSV',exact:true}).click();await download;await page.getByRole('button',{name:'ประวัติรับ–จ่าย',exact:true}).click();assert.equal(await page.locator('.crm-inventory tbody tr').count(),2);assert.deepEqual(errors,[]);await page.close();
}console.log('PASS inventory desktop/mobile: shared master unit, warehouses, item modal, settings, opening, transfer, insufficient stock, alerts, reload and export; production untouched.');}finally{await browser.close();}
