import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import sanitize from 'sanitize-html';import {webcrypto} from 'node:crypto';
const raw=fs.readFileSync('supabase/functions/marketing-email/index.ts','utf8').replace(/^import .*;\r?\n/gm,'').replace('export function cleanHTML','function cleanHTML');
const code=stripTypeScriptTypes(raw,{mode:'strip'});
function harness({providerStatus=200,providerError=false,optedOut=false,enabled=true}={}){
 const mutations=[],calls=[];const campaign={id:'campaign',owner_id:'user',status:'queued',subject:'News',preview_text:'Preview',html:'<p>Hello {{name}}</p>',text:'Hello {{name}}'},recipient={id:'recipient',campaign_id:'campaign',name:'<Alice>',email:'alice@example.invalid',unsubscribe_token:'00000000-0000-4000-8000-000000000001',attempts:1};
 const cfg={enabled,verified_at:'2026-10-01',from_name:'Test company',from_email:'news@example.invalid',reply_to:'reply@example.invalid',postal_address:'123 Example Street'};
 const db={auth:{getUser:async()=>({data:{user:{id:'user'}},error:null})},rpc:async(name,args)=>({data:name==='kc_get_integration_secret'?(args.p_name==='KC_MARKETING_CRON_TOKEN'?'worker-token':'fake-api-key'):name==='crm_email_claim'?[recipient]:null,error:null}),from(table){let column='',update;const q={select(c){column=c;return q;},eq(){return q;},in(){return q;},lte(){return q;},update(v){update=v;return q;},maybeSingle(){return q;},single(){return q;},upsert(v){update=v;return q;},then(resolve){if(update)mutations.push({table,value:update});const data=table==='crm_email_sender'?cfg:table==='profiles'?{id:'user',role:'admin',is_active:true}:table==='crm_email_campaigns'?(column==='id'?[{id:campaign.id}]:campaign):table==='crm_email_opt_outs'?(optedOut?{email:recipient.email}:null):null;return Promise.resolve({data,error:null}).then(resolve);}};return q;}};
 const fetch=async(url,options)=>{calls.push({url,options});if(providerError)throw Error('Network lost');return new Response(JSON.stringify(providerStatus===200?{id:'provider-id'}:{message:'Rate limit'}),{status:providerStatus,headers:{'Content-Type':'application/json','retry-after':'120'}});};
 const Deno={env:{get:n=>n==='SUPABASE_URL'?'https://project.example.invalid':n==='SUPABASE_ANON_KEY'?'anon':'service'},serve:fn=>{Deno.handler=fn;}};
 const result=new Function('createClient','sanitize','Deno','fetch','crypto','setTimeout',code+';return {handler:Deno.handler,cleanHTML};')(()=>db,sanitize,Deno,fetch,webcrypto,fn=>{fn();return 0;});
 return {...result,calls,mutations,request:(body,token)=>new Request('https://project.example.invalid/functions/v1/marketing-email',{method:'POST',headers:{'Content-Type':'application/json',...(token?{'x-marketing-worker':token}:{})},body:JSON.stringify(body)})};
}
test('Anonymous and invalid worker calls are denied before provider access',async()=>{const h=harness();assert.equal((await h.handler(h.request({action:'queue',id:'campaign'}))).status,401);assert.equal((await h.handler(h.request({action:'worker'},'wrong-token'))).status,401);assert.equal(h.calls.length,0);});
test('HTML sanitizer strips scripts, handlers, javascript links, insecure images and unsafe CSS while retaining email tables',()=>{const h=harness(),html=h.cleanHTML('<script>alert(1)</script><table><tr><td style="color:#123456;background:url(https://bad.invalid)">Hello</td></tr></table><a href="javascript:alert(1)" onclick="bad()">link</a><img src="http://bad.invalid" onerror="bad()">');assert.ok(html.includes('<table>'));assert.ok(html.includes('color:#123456'));assert.ok(!/script|onclick|onerror|javascript:|http:\/\/|background:url/.test(html));});
test('Worker sends privately with idempotency, escaped personalization and unsubscribe; only provider acceptance sets sent',async()=>{const h=harness();assert.equal((await h.handler(h.request({action:'worker'},'worker-token'))).status,200);assert.equal(h.calls.length,1);const call=h.calls[0],body=JSON.parse(call.options.body);assert.deepEqual(body.to,['alice@example.invalid']);assert.equal(call.options.headers['Idempotency-Key'],'crm/campaign/recipient');assert.ok(body.html.includes('&lt;Alice&gt;'));assert.ok(body.html.includes('Unsubscribe'));assert.ok(body.headers['List-Unsubscribe-Post']);const state=h.mutations.find(m=>m.table==='crm_email_recipients').value;assert.equal(state.status,'sent');assert.equal(state.provider_id,'provider-id');});
test('Opt-out skips provider, unconfigured sender stays idle, rate limits delay retry and ambiguous failures do not resend',async()=>{const skip=harness({optedOut:true});await skip.handler(skip.request({action:'worker'},'worker-token'));assert.equal(skip.calls.length,0);assert.equal(skip.mutations[0].value.status,'skipped');const idle=harness({enabled:false});await idle.handler(idle.request({action:'worker'},'worker-token'));assert.equal(idle.calls.length,0);const rate=harness({providerStatus:429});await rate.handler(rate.request({action:'worker'},'worker-token'));assert.equal(rate.mutations[0].value.status,'pending');assert.ok(Date.parse(rate.mutations[0].value.next_attempt_at)>Date.now()+110000);const unknown=harness({providerError:true});await unknown.handler(unknown.request({action:'worker'},'worker-token'));assert.equal(unknown.mutations[0].value.status,'failed');assert.match(unknown.mutations[0].value.error,/unknown/);assert.equal(unknown.calls.length,1);});

 test('Email Studio output survives the existing delivery sanitizer without design metadata',async()=>{const {starterDesign,renderDesign}=await import('../src/email-studio-model.mjs');const d=starterDesign();d.blocks[2].url='https://example.com/news';const html=harness().cleanHTML(renderDesign(d));assert.ok(html.includes('ไอเดียใหม่'));assert.ok(html.includes('https://example.com/news'));assert.ok(html.includes('background:#102f3d'));assert.ok(!html.includes('KC_EMAIL_V1'));});
