import test from 'node:test';
import assert from 'node:assert/strict';
import {fullPersonName,profileDraft,reportingOptions,hydrateRelations,convertDemoLead} from '../src/record-profile.mjs';
import {validateRecord} from '../src/internal-model.mjs';
test('new profiles require a surname, compose the shared display name and retain address fields',()=>{
 const input={salutation:'นาย',first_name:'สมชาย',last_name:'ใจดี',customer_id:'account',email:'user@example.test',mobile:'0800000000',mailing_street:'1 ถนนทดสอบ',mailing_country:'Thailand',reports_to_id:'manager'};
 const c=validateRecord('contacts',input);assert.equal(c.name,'นาย สมชาย ใจดี');assert.equal(c.mailing_street,input.mailing_street);assert.equal(c.reports_to_id,'manager');
 const l=validateRecord('leads',{...input,company_name:'Account'});assert.equal(l.contact_name,c.name);assert.equal(l.mobile,c.mobile);assert.equal(l.reports_to_id,undefined);
 assert.throws(()=>validateRecord('contacts',{...input,last_name:''}),/Required: last_name/);assert.throws(()=>validateRecord('contacts',{...input,customer_id:''}),/Required: customer_id/);
});
test('legacy unsplit names survive an edit without guessing their parts',()=>{const old={name:'Dr Alex van den Berg',customer_id:'a'};const draft=profileDraft('contacts',old);assert.equal(draft.last_name,old.name);assert.equal(validateRecord('contacts',draft).name,old.name);assert.equal(fullPersonName({first_name:' Ann ',last_name:' Lee '}),'Ann Lee');assert.deepEqual(old,{name:'Dr Alex van den Berg',customer_id:'a'});});
test('reporting options exclude self, descendants and other accounts',()=>{const contacts=[{id:'a',customer_id:'one'},{id:'b',customer_id:'one',reports_to_id:'a'},{id:'c',customer_id:'one',reports_to_id:'b'},{id:'d',customer_id:'one'},{id:'e',customer_id:'two'}];assert.deepEqual(reportingOptions(contacts,contacts[0]).map(x=>x.id),['d']);});
test('linked record displays follow current names by ID without mutating records',()=>{const row={id:'x',customer_id:'a',contact_id:'c',owner_id:'o',company:'Old'};const refs={customers:[{id:'a',name:'New Account'}],contacts:[{id:'c',name:'New Contact'}],profiles:[{id:'o',display_name:'Owner'}]};const contact=hydrateRelations('contacts',[row],refs)[0];assert.equal(contact.company,'New Account');assert.equal(contact.contact_name,'New Contact');assert.equal(contact.owner_name,'Owner');assert.equal(row.company,'Old');});
test('demo conversion shares the same account, contact and lead IDs and does not convert twice',()=>{const records={customers:[{id:'account',name:'Account'}],contacts:[],leads:[{id:'lead',customer_id:'account',company_name:'Account',contact_name:'First Last',first_name:'First',last_name:'Last',mobile:'0800000000',mailing_postal_code:'10100',note:'Description'}]};let n=0;const uuid=()=>String(++n);assert.equal(convertDemoLead(records,'lead',uuid,'2026-09-30'), 'account');assert.equal(records.contacts[0].mobile,'0800000000');assert.equal(records.contacts[0].mailing_postal_code,'10100');assert.equal(records.contacts[0].description,'Description');assert.equal(records.leads[0].converted_contact_id,records.contacts[0].id);convertDemoLead(records,'lead',uuid,'2026-10-01');assert.equal(records.contacts.length,1);assert.equal(records.customers.length,1);});
