import {test} from 'node:test';
import assert from 'node:assert/strict';
import {canAccess,effectiveRole,permitsPage,filterModules} from '../src/role-access.mjs';
import {saveRolePermissions} from '../src/role-permission-save.mjs';
const member={is_active:true,role:'custom',custom_role_key:'support'};
test('effective role never trusts missing/inactive profiles',()=>{assert.equal(effectiveRole(null),null);assert.equal(effectiveRole({...member,is_active:false}),null);assert.equal(effectiveRole(member),'support');assert.equal(canAccess({...member,role:'admin',is_active:false},[],'customers'),false);});
test('permissions fail closed and distinguish actions',()=>{const rows=[{module:'customers',can_view:true,can_edit:false}];assert.equal(canAccess(member,rows,'customers'),true);assert.equal(canAccess(member,rows,'customers','edit'),false);assert.equal(canAccess(member,rows,'settings'),false);assert.equal(canAccess({role:'admin',is_active:true},[],'settings','edit'),true);});
test('menu and direct route use the same permission and dashboard checks',()=>{const rows=[{module:'customers',can_view:true,can_import:false},{module:'dashboard',can_view:true}];const access={profile:member,dashboards:[{dashboard_type:'my',visible:true}],can:(m,a)=>canAccess(member,rows,m,a)};assert.equal(permitsPage(access,'customers','import-customers'),false);assert.equal(permitsPage(access,'dashboard','dash-exec'),false);assert.equal(permitsPage(access,'dashboard','dash-my'),true);assert.deepEqual(filterModules([{id:'settings'},{id:'customers',subs:[{id:'customer-list'},{id:'import-customers'}]}],access),[{id:'customers',subs:[{id:'customer-list'}]}]);});
test('save sends baseline and requires matching server readback',async()=>{const rows=[{module:'customers',can_view:true}];let request;const client={rpc:async(name,args)=>{request={name,args};return {data:rows,error:null};}};assert.deepEqual(await saveRolePermissions(client,'support',rows,[]),rows);assert.equal(request.name,'crm_set_role_permissions');assert.deepEqual(request.args.p_expected,[]);await assert.rejects(saveRolePermissions({rpc:async()=>({data:[]})},'support',rows,[]),/could not be verified/);await assert.rejects(saveRolePermissions({rpc:async()=>({error:{code:'40001'}})},'support',rows,[]),/Reload before saving/);});
