import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import {webcrypto,createHash} from 'node:crypto';
import {enrichmentRequest,staleSO} from '../supabase/functions/kc-dw-sales-sync/so-sync-model.mjs';
const code=stripTypeScriptTypes(fs.readFileSync('supabase/functions/kc-dw-sales-sync/index.ts','utf8').replace(/^import .*;\r?\n/gm,''),{mode:'strip'}),token='test-integration-key-0000000000000000000001';
function harness(previous=[]){
 const facts=[],performance=[],queries=[];let saved=[];
 const db={from(table){const filters=[],q={select(){return q;},eq(k,v){filters.push([k,v]);return q;},in(){return q;},maybeSingle(){return q;},update(){return q;},insert(){return q;},upsert(v){if(table==='kc_dw_sales_order_facts'){facts.push(...v);saved=v;}if(table==='kc_dw_sales_performance')performance.push(v);return q;},then(resolve){queries.push(table);const data=table==='kc_dw_integration_keys'?{active:true,key_hash:createHash('sha256').update(token).digest('hex')}:table==='kc_dw_sales_identity_map'?[{sales_email:'seller@example.invalid'}]:table==='customers'?{id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',code:'C-001',name:'Exact customer'}:table==='kc_dw_sales_order_facts'?(filters.some(f=>f[0]==='source_system')?previous:filters.some(f=>f[0]==='sales_email')?saved.filter(r=>filters.every(([key,value])=>r[key]===value)):saved):table==='kc_dw_sales_performance'?null:null;return Promise.resolve({data,error:null}).then(resolve);}};return q;}};
 const Deno={env:{get:()=>''},serve(fn){Deno.handler=fn;}};new Function('createClient','Deno','crypto','enrichmentRequest','staleSO',code)(()=>db,Deno,webcrypto,enrichmentRequest,staleSO);
 return {facts,performance,queries,request:(rows,extra={},key=token)=>new Request('https://example.invalid/functions/v1/kc-dw-sales-sync',{method:'POST',headers:{'x-kc-integration-key':key,'Content-Type':'application/json'},body:JSON.stringify({sourceBasis:'converted_so',rows,...extra})}),handler:Deno.handler};
}
const row={soId:'source-1',soNumber:'SO-001',salesEmail:'seller@example.invalid',salesName:'Seller',convertedAt:'2026-09-30T18:00:00Z',netAmount:100,grossProfit:10,sourceUpdatedAt:'2026-10-01T01:00:00Z'};
test('Invalid integration key, non-SO basis and explicit draft status never write facts',async()=>{for(const [r,b,k]of [[[row],{},'bad'],[[row],{sourceBasis:'won_opportunity'},token],[[{...row,status:'draft'}],{},token]]){const h=harness();const response=await h.handler(h.request(r,b,k));assert.ok(response.status>=400);assert.equal(h.facts.length,0);}});
test('Converted SO resolves exact CRM customer, preserves product net values and Bangkok period, and calculates actual SO only',async()=>{const h=harness(),response=await h.handler(h.request([{...row,customerCode:'C-001',productLines:[{product:'Cloud',netAmount:30},{product:'Printer',netAmount:70}]}]));assert.equal(response.status,200);assert.equal(h.facts[0].customer_id,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');assert.equal(h.facts[0].customer_name,'Exact customer');assert.equal(h.facts[0].period_month,'2026-10-01');assert.equal(h.facts[0].product_lines[0].net_amount,30);assert.equal(h.performance[0].actual_revenue,100);});
test('Legacy cancellation keeps customer and product metadata, clears SO actuals, and stale updates do not resurrect orders',async()=>{const previous=[{source_so_id:row.soId,sales_email:row.salesEmail,period_month:'2026-10-01',customer_id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',product_lines:[{product:'Cloud',net_amount:100}],currency:'THB',source_updated_at:'2026-10-01T01:00:00Z'}];const h=harness(previous);assert.equal((await h.handler(h.request([{...row,status:'cancelled',sourceUpdatedAt:'2026-10-02T01:00:00Z'}]))).status,200);assert.equal(h.facts[0].customer_id,previous[0].customer_id);assert.equal(h.facts[0].product_lines[0].net_amount,100);assert.equal(h.performance[0].actual_revenue,0);const stale=harness([{...previous[0],source_updated_at:'2026-10-02T01:00:00Z',status:'cancelled'}]);const response=await stale.handler(stale.request([row]));assert.equal(response.status,200);assert.equal((await response.json()).ignored_stale,1);assert.equal(stale.facts.length,0);});
test('Moving an SO to another period refreshes both old and new buckets; duplicate source IDs and excess product amounts reject the whole batch',async()=>{const h=harness([{source_so_id:row.soId,sales_email:row.salesEmail,period_month:'2026-09-01',currency:'THB'}]);assert.equal((await h.handler(h.request([row]))).status,200);assert.deepEqual(h.performance.map(r=>r.period_month).sort(),['2026-09-01','2026-10-01']);assert.equal(h.performance.find(r=>r.period_month==='2026-09-01').actual_revenue,0);assert.equal(h.performance.find(r=>r.period_month==='2026-10-01').actual_revenue,100);for(const rows of [[row,row],[{...row,productLines:[{product:'Cloud',netAmount:101}]}]]){const invalid=harness();assert.equal((await invalid.handler(invalid.request(rows))).status,400);assert.equal(invalid.facts.length,0);}});
