import {SOURCES,duplicateReasons,identityGroup,overview,timeline} from './customer360-model.mjs?v=20261004';
const columns={contacts:'id,name,customer_id,position,email,phone,created_at,updated_at',branches:'id,name,customer_id,address,status,created_at,updated_at',leads:'id,company_name,customer_id,status,created_at,updated_at,converted_at',opportunities:'id,name,customer_id,stage,amount,status,created_at,updated_at',quotations:'id,code,customer_id,status,created_at,updated_at',contracts:'id,code,name,customer_id,status,end_date,created_at,updated_at',assets:'id,name,customer_id,status,serial_number,created_at,updated_at',tickets:'id,code,subject,customer_id,status,created_at,updated_at,resolved_at',activities:'id,subject,type,customer_id,status,created_at,updated_at,scheduled_at',documents:'id,name,customer_id,status,created_at,updated_at',orders:'id,so_number,customer_id,net_amount,currency,status,converted_at,source_system,source_so_id,customer_source_id,source_updated_at,synced_at'};
const customerColumns='id,code,name,tax_id,email,phone,owner_name,status,industry,tier,address,billing_city,province,created_at,updated_at';
export function createCustomer360({React,client,useApp,records}){
 const h=React.createElement;
 async function unwrap(q){const {data,error}=await q;if(error)throw error;return data;}
 async function pages(table,cols,configure=q=>q){let rows=[];for(let n=0;n<20000;n+=500){const batch=await unwrap(configure(client.from(table).select(cols)).order('id').range(n,n+499));rows.push(...batch);if(batch.length<500)return rows;}throw Error('รายการเกินขอบเขต 20,000 รายการ / More than 20,000 records');}
 return function Customer360({record,lang='th'}){
  const {demoMode,profile,navigate}=useApp(),th=lang==='th',t=(a,b)=>th?a:b;
  const [state,State]=React.useState(null),[busy,Busy]=React.useState(false),[error,ErrorText]=React.useState(''),[tab,Tab]=React.useState('overview'),[detail,Detail]=React.useState(null),[filter,Filter]=React.useState(''),[search,Search]=React.useState(''),[review,Review]=React.useState(null),[reason,Reason]=React.useState(''),[confirmed,Confirmed]=React.useState(false),[reload,Reload]=React.useState(0);
  const saving=React.useRef(false),isAdmin=profile?.role==='admin';
  React.useEffect(()=>{let active=true;State(null);ErrorText('');Busy(true);Review(null);Detail(null);
   (async()=>{try{
    let rights=[];if(!demoMode&&!isAdmin)rights=await unwrap(client.from('role_permissions').select('module,can_view').eq('role_key',profile?.role==='custom'?profile.custom_role_key:profile?.role||''));
    const can=m=>demoMode||isAdmin||rights.some(x=>x.module===m&&x.can_view);
    if(!can('customers'))throw Error(t('ไม่มีสิทธิ์ดูลูกค้า','Customer access denied'));
    const customers=demoMode?records.customers:await pages('customers',customerColumns);
    const links=demoMode?(records.customer360_links||[]):await pages('crm_customer_identity_links','customer_id,canonical_id,linked_at',q=>q);
    const group=identityGroup(record.id,links),members=customers.filter(c=>group.ids.includes(c.id));
    if(!members.some(c=>c.id===record.id))throw Error(t('ไม่พบลูกค้าหรือไม่มีสิทธิ์','Customer unavailable'));
    const data={},issues=[];
    await Promise.all(Object.keys(SOURCES).map(async key=>{const module=key==='branches'?'customers':key==='orders'?'quotations':key;if(!can(module)){data[key]=null;issues.push(key+': '+t('ไม่มีสิทธิ์','Access denied'));return;}try{data[key]=demoMode?(records[key==='orders'?'sales_orders':key]||[]).filter(r=>group.ids.includes(r.customer_id)):await pages(key==='branches'?'crm_branches':key==='orders'?'kc_dw_sales_order_facts':key,columns[key],q=>q.in('customer_id',group.ids));}catch(e){data[key]=null;issues.push(key+': '+e.message);}}));
    let events=[],history=[];try{events=demoMode?(records.customer360_events||[]).filter(e=>group.ids.includes(e.customer_id)):await pages('crm_customer360_events','id,module,record_id,customer_id,action,title,status,created_at',q=>q.in('customer_id',group.ids));history=demoMode?[]:await pages('crm_customer_identity_events','id,customer_id,canonical_id,action,reason,actor_id,created_at',q=>q.in('canonical_id',group.ids));}catch(e){issues.push(t('ประวัติ: ','History: ')+e.message);}
    if(active)State({customers,links,group,members,data,issues,events,history,asOf:new Date().toISOString()});
   }catch(e){if(active)ErrorText(e.message);}finally{if(active)Busy(false);}})();return()=>{active=false;};
  },[record.id,profile?.id,profile?.role,profile?.custom_role_key,demoMode,reload,lang]);
  const button=(name,fn,extra={})=>h('button',{type:'button',onClick:fn,...extra},name),cash=n=>new Intl.NumberFormat(th?'th-TH':'en-GB',{maximumFractionDigits:2,minimumFractionDigits:2}).format(n),date=v=>v?new Date(v).toLocaleString(th?'th-TH':'en-GB',{timeZone:'Asia/Bangkok'}):'—';
  const label=k=>SOURCES[k]?.[th?0:1]||k;
  function open(source,r){if(source==='orders'){Detail({source,rows:[state.data.orders?.find(x=>x.id===r.id)||r],title:r.so_number||r.id});Tab('overview');return;}navigate(source==='branches'?'customers':source,SOURCES[source][2],{recordId:r.id});}
  function beginReview(customer,unlink=false){Review({customer,unlink});Reason('');Confirmed(false);ErrorText('');}
  async function saveLink(){if(!review||saving.current||!confirmed||reason.trim().length<5)return;saving.current=true;Busy(true);ErrorText('');try{if(demoMode){records.customer360_links??=[];records.customer360_links=records.customer360_links.filter(x=>x.customer_id!==review.customer.id);if(!review.unlink)records.customer360_links.push({customer_id:review.customer.id,canonical_id:state.group.root});}else await unwrap(client.rpc('crm_customer_identity_link',{p_customer:review.customer.id,p_canonical:review.unlink?null:state.group.root,p_reason:reason.trim()}));Review(null);Reload(x=>x+1);}catch(e){ErrorText(e.message);Busy(false);}finally{saving.current=false;}}
  const list=(source,rows)=>rows===null?h('p',{className:'c360-alert'},t('ไม่มีสิทธิ์หรือโหลดไม่สำเร็จ — ไม่ใช่ยอดศูนย์','Unavailable or denied — not a zero balance')):h('div',{className:'c360-list'},rows.length?rows.map(r=>h('article',{className:'c360-row',key:r.id},button(r.code||r.so_number||r.name||r.subject||r.company_name||r.id,()=>open(source,r)),h('small',null,' · '+(r.status||'')+' · '+(state.members.find(c=>c.id===r.customer_id)?.name||'')),source==='orders'&&h('p',null,cash(Number(r.net_amount||0))+' '+(r.currency||'THB')+' · '+date(r.converted_at)),source==='orders'&&h('small',null,(r.source_system||'')+' / '+(r.source_so_id||'')+' · '+t('รหัสลูกค้าต้นทาง: ','Source customer ID: ')+(r.customer_source_id||'—')+' · '+t('ซิงก์ ','Synced ')+date(r.synced_at)))):h('p',null,t('ไม่มีรายการ','No records')));
  if(!state)return h('section',{className:'c360','aria-label':'Customer 360'},h('h2',null,'Customer 360'),error?h('p',{role:'alert'},error):h('p',{role:'status'},t('กำลังรวมข้อมูลลูกค้า…','Loading customer overview…')),error&&button(t('ลองใหม่','Retry'),()=>Reload(x=>x+1)));
  const root=state.members.find(x=>x.id===state.group.root)||record,summary=overview(state.data),events=timeline(state.data,state.events).filter(e=>(!filter||e.source===filter)&&[e.title,e.action,e.status].join(' ').toLowerCase().includes(search.toLowerCase())),candidates=state.customers.filter(c=>!state.group.ids.includes(c.id)).map(c=>({customer:c,reasons:duplicateReasons(root,c)})).filter(c=>c.reasons.length),metricLabels={sales:t('ยอดขาย SO ปีนี้ · บาท','YTD SO sales · THB'),pipeline:t('Pipeline เปิด · บาท','Open pipeline · THB'),quotes:t('ใบเสนอราคาที่ต้องติดตาม','Quotes to follow up'),cases:t('เคสที่ยังไม่ปิด','Open cases'),renewal:t('สัญญาครบกำหนด 90 วัน','Contracts due in 90 days')};
  const actions={created:t('สร้างรายการ','Created'),last_updated:t('แก้ไขล่าสุด','Last updated'),scheduled:t('นัดหมาย','Scheduled'),converted:t('แปลงเป็นลูกค้า / SO','Converted'),resolved:t('แก้ไขเคสแล้ว','Resolved'),INSERT:t('สร้างรายการ','Created'),UPDATE:t('เปลี่ยนแปลงข้อมูล','Updated'),DELETE:t('นำรายการออก','Deleted')};
  return h('section',{className:'c360','aria-label':'Customer 360'},
   h('header',{className:'c360-hero'},h('div',{className:'c360-identity'},h('small',{className:'c360-eyebrow'},'CUSTOMER INTELLIGENCE / 360'),h('h2',null,root.name),h('p',null,t('รหัสลูกค้าหลัก: ','Canonical account: ')+(root.code||'—')),h('details',{className:'c360-id'},h('summary',null,t('ดูรหัสกลาง','View canonical ID')),h('code',null,state.group.root)),h('p',null,[root.owner_name,root.industry,root.tier,root.status].filter(Boolean).join(' · '))),button(t('รีเฟรช Customer 360','Refresh Customer 360'),()=>Reload(x=>x+1),{disabled:busy})),
   h('small',{className:'c360-sync'},t('ข้อมูลตามสิทธิ์ · โหลดเมื่อ ','Permission-scoped data · Loaded ')+date(state.asOf)+' · '+state.members.length+t(' รายการในกลุ่ม',' linked accounts')),
   error&&h('p',{role:'alert',className:'c360-alert'},error),state.issues.length>0&&h('details',{className:'c360-alert'},h('summary',null,t('บางข้อมูลไม่พร้อมใช้งาน','Some data is unavailable')),state.issues.map(x=>h('p',{key:x},x))),
   h('nav',{className:'c360-tabs','aria-label':t('มุมมอง Customer 360','Customer 360 views')},...[[ 'overview','ภาพรวม','Overview'],['records','ข้อมูลที่เกี่ยวข้อง','Related records'],['timeline','Timeline','Timeline'],['identity','รหัสกลางและข้อมูลซ้ำ','Identity & duplicates']].map(([id,a,b])=>button(t(a,b),()=>{Tab(id);Detail(null);},{key:id,'aria-pressed':tab===id}))),
   tab==='overview'&&h(React.Fragment,null,h('h3',{className:'c360-section-title'},t('ภาพรวมลูกค้า','Account overview')),h('div',{className:'c360-kpis'},summary.metrics.map(m=>button(h(React.Fragment,null,h('span',null,metricLabels[m.key]),h('strong',null,m.value===null?'—':m.money?cash(m.value):m.value),h('small',null,t('ดูรายการต้นทาง','View source records'))),()=>Detail({...m,title:metricLabels[m.key]}),{key:m.key,'data-metric':m.key,disabled:m.value===null}))),h('p',null,t('ซื้อครั้งล่าสุด: ','Last purchase: ')+((summary.lastPurchase??t('ข้อมูลไม่พร้อม','Unavailable'))||'—')),h('small',null,t('ยอดขายใช้ SO converted สกุล THB สุทธิก่อน VAT ตั้งแต่ 1 ม.ค. ถึงวันนี้ (เวลาไทย) ไม่รวมใบเสนอราคา ยอดรับชำระ และ SO ที่ยังไม่ได้ผูกรหัสลูกค้า','Sales: converted THB orders, net before VAT, January 1 through today in Bangkok. Quotes, payments and orders without a linked customer ID are excluded.')),summary.excludedOrders>0&&h('p',{className:'c360-alert'},t('SO ที่ไม่รวมในการคำนวณ (สกุลเงิน/วันที่/ยอดไม่ถูกต้อง): ','Orders excluded (currency/date/invalid amount): ')+summary.excludedOrders),h('div',{className:'c360-overview-grid'},h('section',{className:'c360-panel'},h('h3',null,t('ข้อมูลลูกค้า','Account information')),h('dl',null,...[[t('ผู้รับผิดชอบ','Owner'),root.owner_name],[t('อีเมล','Email'),root.email],[t('โทรศัพท์','Phone'),root.phone],[t('ที่อยู่','Address'),[root.address,root.billing_city,root.province].filter(Boolean).join(' ')]].map(([name,value])=>h('div',{key:name},h('dt',null,name),h('dd',null,value||'—'))))),h('section',{className:'c360-panel'},h('div',{className:'c360-panel-heading'},h('h3',null,t('เหตุการณ์ล่าสุด','Recent activity')),button(t('ดูทั้งหมด','View all'),()=>{Filter('');Search('');Tab('timeline');})),timeline(state.data,state.events).slice(0,3).map(e=>h('article',{className:'c360-recent',key:e.id},h('small',null,date(e.at)+' · '+label(e.source)),h('p',null,(actions[e.action]||e.action)+' · '+e.title))),!timeline(state.data,state.events).length&&h('p',null,t('ยังไม่มีเหตุการณ์','No events')))),detail&&h('section',null,h('h3',null,detail.title),list(detail.source,detail.rows))),
   tab==='records'&&h(React.Fragment,null,h('label',null,t('หมวดข้อมูล','Record type'),h('select',{value:filter,onChange:e=>Filter(e.target.value)},h('option',{value:''},t('ทุกหมวด','All types')),...Object.keys(SOURCES).map(k=>h('option',{key:k,value:k},label(k))))),...Object.keys(SOURCES).filter(k=>!filter||filter===k).map(k=>h('details',{key:k},h('summary',null,label(k)+' ('+(state.data[k]?.length??'—')+')'),list(k,state.data[k])))),
   tab==='timeline'&&h(React.Fragment,null,h('p',null,t('รวมวันสร้าง/แก้ไขล่าสุด/นัดหมาย และประวัติการเปลี่ยนแปลงที่เริ่มเก็บตั้งแต่เปิด Customer 360 ไม่มีการสร้างประวัติย้อนหลังที่ระบบไม่เคยบันทึก','Includes record dates and captured changes since Customer 360 was enabled. Historical transitions not previously recorded are not reconstructed.')),h('div',{className:'c360-columns'},h('label',null,t('ค้นหาเหตุการณ์','Search events'),h('input',{value:search,onChange:e=>Search(e.target.value)})),h('label',null,t('หมวดเหตุการณ์','Event type'),h('select',{value:filter,onChange:e=>Filter(e.target.value)},h('option',{value:''},t('ทุกหมวด','All types')),...Object.keys(SOURCES).map(k=>h('option',{key:k,value:k},label(k)))))),h('ol',{className:'c360-timeline c360-list'},events.length?events.map(e=>h('li',{key:e.id},h('small',null,date(e.at)+' · '+label(e.source)),h('p',null,(actions[e.action]||e.action)+' · '+e.title+(e.status?' · '+e.status:'')),e.derived&&h('small',null,t('จากวันที่ในรายการต้นทาง','From source record date')),SOURCES[e.source]&&e.action!=='DELETE'&&button(t('เปิดรายการ','Open record'),()=>open(e.source,{id:e.record_id,so_number:e.title})))):h('li',null,t('ยังไม่มีเหตุการณ์','No events')))),
   tab==='identity'&&h(React.Fragment,null,h('p',null,t('รหัสกลางใช้ ID ถาวรของลูกค้าหลัก การเชื่อมรวมเฉพาะมุมมอง Customer 360 เก็บชื่อ รหัส และเอกสารต้นฉบับไว้ครบ ยกเลิกการเชื่อมได้ ไม่ใช่การลบลูกค้า','The canonical ID is the primary account UUID. Linking combines the Customer 360 view while preserving original accounts and documents; links can be undone.')),
    h('h3',null,t('ลูกค้าในกลุ่ม','Group members')),state.members.map(c=>h('article',{className:'c360-row',key:c.id},h('strong',null,c.name),h('p',null,(c.code||'—')+' · '+(c.tax_id||'—')+' · '+(c.email||'—')),c.id===state.group.root?h('small',null,t('ลูกค้าหลัก','Canonical account')):isAdmin&&button(t('ทบทวนการยกเลิกเชื่อม','Review unlink'),()=>beginReview(c,true),{disabled:busy}))),
    h('h3',null,t('รายการที่อาจซ้ำ — ต้องตรวจสอบก่อนเชื่อม','Possible duplicates — review before linking')),h('p',null,t('เทียบเลขผู้เสียภาษี อีเมล โทรศัพท์ และชื่อที่ตรงกัน ไม่รวมอัตโนมัติ','Matches tax ID, email, phone or name. No automatic merge.')),candidates.length?candidates.map(({customer:c,reasons})=>h('article',{className:'c360-row',key:c.id},h('strong',null,c.name),h('p',null,(c.code||'')+' · '+reasons.map(x=>({tax_id:t('เลขผู้เสียภาษีตรงกัน','Same tax ID'),email:t('อีเมลตรงกัน','Same email'),phone:t('โทรศัพท์ตรงกัน','Same phone'),name:t('ชื่อตรงกัน','Same name')}[x])).join(' / ')),isAdmin&&button(t('เปรียบเทียบก่อนเชื่อม','Compare before linking'),()=>beginReview(c),{disabled:busy||state.links.some(x=>x.customer_id===c.id||x.canonical_id===c.id)}))):h('p',null,t('ไม่พบรายการที่ตรงเงื่อนไข','No matching candidates')),
    !isAdmin&&h('p',null,t('การเชื่อม/ยกเลิกเชื่อมสงวนสำหรับผู้ดูแลระบบ','Only administrators can link or unlink accounts')),
    review&&h('section',{className:'c360-review','aria-label':t('ตรวจสอบการเชื่อมลูกค้า','Review customer identity')},h('h3',null,review.unlink?t('ยกเลิกการเชื่อม','Unlink account'):t('ยืนยันลูกค้าหลักและรายการซ้ำ','Review primary and duplicate accounts')),h('table',null,h('thead',null,h('tr',null,h('th',null,t('ข้อมูล','Field')),h('th',null,t('ลูกค้าหลัก','Primary')),h('th',null,t('รายการที่เลือก','Selected')))),h('tbody',null,...['code','name','tax_id','email','phone','owner_name'].map(k=>h('tr',{key:k},h('th',null,({code:t('รหัสลูกค้า','Account code'),name:t('ชื่อ','Name'),tax_id:t('เลขผู้เสียภาษี','Tax ID'),email:t('อีเมล','Email'),phone:t('โทรศัพท์','Phone'),owner_name:t('ผู้รับผิดชอบ','Owner')}[k])),h('td',null,root[k]||'—'),h('td',null,review.customer[k]||'—'))))),h('p',null,t('ไม่มีการทับชื่อ ที่อยู่ หรือเอกสารเดิม การยกเลิกเชื่อมจะแยกยอดและ Timeline กลับตามเจ้าของต้นฉบับ','Names, addresses and documents are preserved. Unlinking separates totals and timeline by original account.')),h('label',null,t('เหตุผล (อย่างน้อย 5 ตัวอักษร)','Reason (at least 5 characters)'),h('input',{value:reason,maxLength:500,onChange:e=>Reason(e.target.value),disabled:busy})),h('label',null,h('input',{type:'checkbox',checked:confirmed,onChange:e=>Confirmed(e.target.checked),disabled:busy}),t('ตรวจสอบแล้วและยืนยันการเปลี่ยนแปลงนี้','I reviewed and confirm this change')),button(t('ยืนยันและบันทึก','Confirm and save'),saveLink,{disabled:busy||!confirmed||reason.trim().length<5,className:'c360-primary'}),button(t('ยกเลิก','Cancel'),()=>Review(null),{disabled:busy})),
    h('details',null,h('summary',null,t('ประวัติการเชื่อมรหัสกลาง','Identity change history')),state.history.length?state.history.map(e=>h('p',{key:e.id},date(e.created_at)+' · '+e.action+' · '+e.customer_id+' · '+e.reason+' · '+e.actor_id)):h('p',null,t('ยังไม่มีประวัติ','No history')))));
 }
}
