import {financeSummary,validateFinance} from './customer360-finance-model.mjs?v=20261005';
import {createRecordPopup} from './record-popup.mjs?v=20261004';
export function createCustomerFinance({React,client,records}){
 const h=React.createElement,Popup=createRecordPopup(React);
 return function CustomerFinance({customer,ids,lang='th',demoMode,canWrite}){
 const t=(a,b)=>lang==='th'?a:b,[rows,Rows]=React.useState(null),[draft,Draft]=React.useState(null),[voidRow,VoidRow]=React.useState(null),[reason,Reason]=React.useState(''),[error,E]=React.useState(''),[message,M]=React.useState(''),[busy,B]=React.useState(false),[revision,R]=React.useState(0),lock=React.useRef(false),idsKey=ids.join(',');
 React.useEffect(()=>{let alive=true;Rows(null);E('');(async()=>{try{let data=[];if(demoMode)data=(records.financeEntries||[]).filter(x=>ids.includes(x.customer_id));else for(let n=0;n<20000;n+=500){const r=await client.from('crm_customer_finance_entries').select('*').in('customer_id',ids).order('id').range(n,n+499);if(r.error)throw r.error;data.push(...r.data);if(r.data.length<500)break;if(n===19500)throw Error('Too many records; narrow the customer group');}if(alive)Rows(data);}catch(e){if(alive)E(e.message);}})();return()=>{alive=false;};},[idsKey,demoMode,revision]);
 const summary=financeSummary(rows||[]),money=v=>Number(v).toLocaleString(lang==='th'?'th-TH':'en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
 const start=invoice=>{E('');M('');Draft({id:crypto.randomUUID(),kind:invoice?'payment':'invoice',customer_id:invoice?.customer_id||customer.id,invoice_id:invoice?.id||null,reference:'',amount:invoice?String(invoice.balance):'',currency:invoice?.currency||'THB',issued_on:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'}),due_on:'',note:''});};
 async function save(e){e.preventDefault();if(lock.current)return;lock.current=true;B(true);E('');try{let saved;
 if(voidRow){if(reason.trim().length<5)throw Error(t('ระบุเหตุผลอย่างน้อย 5 ตัวอักษร','Enter a reason of at least 5 characters'));if(demoMode){if(voidRow.kind==='invoice'&&rows.some(p=>p.invoice_id===voidRow.id&&p.status==='active'))throw Error('Void active payments first');saved={...voidRow,status:'void',void_reason:reason.trim(),updated_at:new Date().toISOString()};records.financeEntries=records.financeEntries.map(x=>x.id===saved.id?saved:x);}else{const r=await client.from('crm_customer_finance_entries').update({status:'void',void_reason:reason.trim()}).eq('id',voidRow.id).eq('updated_at',voidRow.updated_at).select().single();if(r.error)throw r.error;saved=r.data;}Rows(old=>old.map(x=>x.id===saved.id?saved:x));VoidRow(null);}
 else{const data=validateFinance(draft);if(demoMode){if((records.financeEntries||[]).some(x=>x.customer_id===data.customer_id&&x.kind===data.kind&&x.reference===data.reference))throw Error('Duplicate reference');if(data.kind==='payment'){const invoice=summary.invoices.find(x=>x.id===data.invoice_id);if(!invoice||data.amount>invoice.balance||data.currency!==invoice.currency||data.issued_on<invoice.issued_on)throw Error('Invalid payment or amount exceeds outstanding balance');}saved={...data,status:'active',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};records.financeEntries??=[];records.financeEntries.push(saved);}else{const r=await client.from('crm_customer_finance_entries').insert(data).select().single();if(r.error)throw r.error;saved=r.data;}Rows(old=>[...old,saved]);Draft(null);}
 M(t('บันทึกรายการอ้างอิงแล้ว','Reference saved'));
 }catch(e){E(e.code==='23505'?t('เลขอ้างอิงซ้ำหรือรายการนี้บันทึกแล้ว กรุณาโหลดใหม่เพื่อตรวจสอบ','Duplicate reference or already saved. Refresh to verify.'):e.code==='PGRST116'?t('รายการเปลี่ยนแปลงแล้ว กรุณาโหลดใหม่','Record changed. Refresh before editing.'):e.message);}finally{lock.current=false;B(false);}}
 const field=(key,a,b,type='text')=>h('label',{key},t(a,b),h('input',{'aria-label':t(a,b),type,value:draft[key]||'',required:key!=='note',disabled:busy||key==='currency'&&draft.kind==='payment',maxLength:key==='reference'?150:key==='note'?2000:undefined,min:type==='number'?0.01:undefined,step:type==='number'?'0.01':undefined,onChange:e=>Draft(v=>({...v,[key]:e.target.value}))}));
 const editor=draft&&h(Popup,{title:draft.kind==='invoice'?t('เพิ่มใบแจ้งหนี้อ้างอิง','Add invoice reference'):t('บันทึกการรับชำระอ้างอิง','Record payment reference'),lang,busy,error,onClose:()=>Draft(null)},h('form',{'aria-label':'Finance reference form',onSubmit:save},h('p',null,t('บันทึกจากเอกสารที่ตรวจสอบแล้ว ไม่ได้ออกใบกำกับภาษีหรือทำรายการรับเงินจริง','Record verified source documents. This does not issue tax invoices or process payments.')),h('div',{className:'c360-columns'},field('reference','เลขเอกสารอ้างอิง','Reference'),field('amount','จำนวนเงิน','Amount','number'),field('issued_on','วันที่เอกสาร','Document date','date'),draft.kind==='invoice'&&field('due_on','วันครบกำหนด','Due date','date'),h('label',null,t('สกุลเงิน','Currency'),h('select',{'aria-label':'Currency',value:draft.currency,disabled:busy||draft.kind==='payment',onChange:e=>Draft(v=>({...v,currency:e.target.value}))},['THB','USD','EUR','JPY'].map(v=>h('option',{key:v,value:v},v)))),field('note','หมายเหตุ / แหล่งเอกสาร','Source note')),
 h('div',{className:'crm-actions'},h('button',{type:'button',disabled:busy,onClick:()=>Draft(null)},t('ยกเลิก','Cancel')),h('button',{type:'submit',disabled:busy},t('บันทึก','Save')))));
 return h('section',{className:'c360-panel','aria-label':t('ยอดคงค้างอ้างอิง','Receivable references')},h('h3',null,t('ใบแจ้งหนี้และการรับชำระอ้างอิง','Invoice & payment references')),h('p',null,t('ข้อมูลกรอกเองจากเอกสารต้นทาง ยังไม่ซิงก์ระบบบัญชี ยอดนี้รวมเฉพาะรายการที่บันทึกไว้และแยกตามสกุลเงิน','Manually recorded source documents; accounting sync is not connected. Totals cover recorded entries only, separated by currency.')),error&&!draft&&!voidRow&&h('p',{role:'alert'},error),message&&h('p',{role:'status'},message),h('button',{type:'button',disabled:busy,onClick:()=>R(n=>n+1)},t('โหลดข้อมูลการเงินใหม่','Refresh finance')),
 rows===null?h('p',null,error?t('ข้อมูลไม่พร้อม — ไม่ใช่ยอดศูนย์','Unavailable — not a zero balance'):t('กำลังโหลด…','Loading…')):h(React.Fragment,null,
 canWrite&&h('button',{type:'button',onClick:()=>start(),disabled:busy},t('เพิ่มใบแจ้งหนี้อ้างอิง','Add invoice reference')),!rows.length&&h('p',null,t('ยังไม่มีเอกสารอ้างอิง ยอดคงค้างจริงยังไม่ทราบ','No source documents recorded. Actual outstanding balance is unknown.')),
 Object.entries(summary.currencies).map(([currency,totals])=>h('div',{key:currency,className:'c360-row'},h('strong',null,currency),h('p',null,t('ยอดเอกสาร: ','Billed: ')+money(totals.billed)+' · '+t('รับชำระ: ','Paid: ')+money(totals.paid)),h('p',null,t('คงค้าง: ','Outstanding: ')+money(totals.outstanding)+' · '+t('เกินกำหนด: ','Overdue: ')+money(totals.overdue)))),
 h('div',{className:'c360-list'},(rows||[]).map(r=>h('article',{key:r.id,className:'c360-row'},h('strong',null,r.reference+' · '+(r.kind==='invoice'?t('ใบแจ้งหนี้','Invoice'):t('รับชำระ','Payment'))),h('p',null,r.issued_on+' · '+money(r.amount)+' '+r.currency+' · '+r.status),r.due_on&&h('p',null,t('ครบกำหนด: ','Due: ')+r.due_on),r.invoice_id&&h('p',null,t('อ้างอิงใบแจ้งหนี้: ','Invoice: ')+(rows.find(x=>x.id===r.invoice_id)?.reference||r.invoice_id)),r.note&&h('p',null,r.note),r.void_reason&&h('p',null,t('เหตุผลยกเลิก: ','Void reason: ')+r.void_reason),canWrite&&r.status==='active'&&h('div',null,r.kind==='invoice'&&summary.invoices.find(x=>x.id===r.id)?.balance>0&&h('button',{type:'button',onClick:()=>start(summary.invoices.find(x=>x.id===r.id))},t('บันทึกรับชำระ ','Record payment ')+r.reference),h('button',{type:'button',onClick:()=>{E('');Reason('');VoidRow(r);}},t('ยกเลิกรายการ ','Void ')+r.reference))))),editor,
 voidRow&&h(Popup,{title:t('ยกเลิกรายการอ้างอิง','Void reference'),lang,busy,error,onClose:()=>VoidRow(null)},h('form',{onSubmit:save},h('p',null,voidRow.reference),h('label',null,t('เหตุผลการยกเลิก','Void reason'),h('input',{'aria-label':'Void reason',required:true,minLength:5,maxLength:500,value:reason,onChange:e=>Reason(e.target.value)})),h('button',{type:'submit',disabled:busy},t('ยืนยันยกเลิกรายการ','Confirm void'))))));
 };
}
