import {OPTIONS} from './internal-options.mjs';
import {ENTITIES,LABELS,MASTER_FIELDS,RELATIONS,fieldsFor} from './internal-model.mjs';
import {PROFILE_LABELS,CUSTOMER_LABELS,parentCustomerOptions,reportingOptions} from './record-profile.mjs';
export function createCustomerDialog(React){const h=React.createElement;return function CustomerDialog({lang,editing,setEditing:Edit,lookup={},masters=[],busy=false,error='',onSave:save}){
const entity='customers',profileEntity=false,def=ENTITIES.customers,t=(a,b)=>lang==='th'?a:b;
const label=k=>entity==='activities'&&({subject:t('หัวข้อกิจกรรม','Subject'),type:t('ประเภทกิจกรรม','Activity Type'),status:t('สถานะ','Status'),priority:t('ความสำคัญ','Priority'),customer_id:t('ลูกค้า','Account'),contact_id:t('ผู้ติดต่อ','Contact'),owner_id:t('ผู้รับผิดชอบ','Owner'),scheduled_at:t('วันเวลานัดหมาย','Scheduled at'),reminder_at:t('วันเวลาเตือน','Reminder at'),meeting_url:t('ลิงก์ประชุม','Meeting URL'),next_action:t('งานถัดไป','Next Action')}[k])||entity==='customers'&&({name:t('ชื่อลูกค้า','Account Name'),billing_city:t('เมืองสำหรับเรียกเก็บเงิน','Billing City'),province:t('รัฐ/จังหวัดสำหรับเรียกเก็บเงิน','Billing State / Province'),owner_id:t('ผู้รับผิดชอบลูกค้า','Account Owner')}[k])||(entity==='customers'&&CUSTOMER_LABELS[k]?.[lang==='th'?0:1])||PROFILE_LABELS[k]?.[lang==='th'?0:1]||(profileEntity&&k==='customer_id'?t('บัญชีลูกค้า','Account'):profileEntity&&k==='owner_id'?t(entity==='contacts'?'เจ้าของผู้ติดต่อ':'เจ้าของลีด',entity==='contacts'?'Contact Owner':'Lead Owner'):lang==='th'?(LABELS[k]||k):k.replaceAll('_',' '));
const btn=(text,onClick,disabled=false,props={})=>h('button',{type:'button',onClick,disabled,...props},text);
const profileDialogRef=React.useRef(null);
React.useEffect(()=>{const d=profileDialogRef.current;d.showModal();return()=>{if(d.open)d.close();};},[]);
  function formField(f){if(entity==='prices'&&f.key==='cost'&&!can('approve'))return null;const value=editing[f.key]??'',options=OPTIONS[entity]?.[f.key]||(f.key==='status'?def.statuses:null);let category=(f.key==='status'&&entity==='assets'?'asset_status':MASTER_FIELDS[f.key])||(f.key==='type'&&entity==='customers'?'customer_type':f.key==='category'&&entity==='assets'?'asset_type':f.key==='category'&&entity==='prices'?'product_category':f.key==='unit'?'unit':null);const refs=masters.filter(x=>x.category===category);const props={'aria-label':label(f.key),required:f.required,disabled:busy,value:f.type==='datetime-local'&&value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):value,onChange:e=>Edit(v=>({...v,[f.key]:f.type==='checkbox'?e.target.checked:e.target.value,...(f.key==='customer_id'?{contact_id:'',reports_to_id:'',...(entity==='leads'&&e.target.value?{company_name:lookup.customers?.find(x=>x.id===e.target.value)?.name||v.company_name}:{})}:{})}))};let control;
   if(f.type==='relation'){const rr=f.key==='parent_customer_id'?parentCustomerOptions(lookup.customers||[],editing):f.key==='reports_to_id'?reportingOptions(lookup.contacts||[],editing):(lookup[RELATIONS[f.key]]||[]).filter(x=>!['contact_id','opportunity_id','contract_id','asset_id','branch_id','assigned_user_id'].includes(f.key)||!editing.customer_id||x.customer_id===editing.customer_id);control=h('select',props,h('option',{value:''},'—'),rr.map(x=>h('option',{key:x.id,value:x.id},x.display_name||x.name||x.code)));}
   else if(f.key==='salutation'||['mailing_country','billing_country','shipping_country'].includes(f.key)){const vals=f.key==='salutation'?['นาย','นาง','นางสาว','ดร.','Mr.','Ms.','Mrs.','Dr.','Prof.']:['Thailand','United States','United Kingdom','Singapore','Malaysia','Vietnam','China','Japan','Australia'];if(value&&!vals.includes(value))vals.push(value);control=f.key==='salutation'?h('select',props,h('option',{value:''},t('ไม่มี','None')),vals.map(v=>h('option',{key:v,value:v},v))):h(React.Fragment,null,h('input',{...props,list:'crm-profile-countries'}),h('datalist',{id:'crm-profile-countries'},vals.map(v=>h('option',{key:v,value:v},v))));}
   else if(options||refs.length){const vals=[...(options||[]).map(v=>[v,v]),...refs.filter(r=>!options?.includes(r.name_en)).map(r=>[r.name_en,lang==='th'?r.name_th:r.name_en])];if(value&&!vals.some(x=>x[0]===value))vals.unshift([value,value]);control=h('select',props,h('option',{value:''},'—'),vals.map(([v,n])=>h('option',{key:v,value:v},n)));}
   else if(f.type==='checkbox')control=h('input',{...props,type:'checkbox',checked:!!value,value:undefined});else if(f.type==='textarea')control=h('textarea',{...props,rows:3});else control=h('input',{...props,type:f.key==='email'?'email':['phone','mobile'].includes(f.key)?'tel':f.type==='number'?'number':f.type,min:f.type==='number'?0:undefined,step:f.type==='number'?'any':undefined});return h('label',{key:f.key,className:'crm-field'+(['description','note','mailing_street','address','shipping_street'].includes(f.key)||entity==='activities'&&['subject','meeting_url','next_action'].includes(f.key)?' crm-profile-wide':'')},h('span',null,label(f.key)+(f.required?' *':'')),control);}

  const profileField=key=>formField(fieldsFor(entity).find(f=>f.key===key));
  const profileSection=(title,keys)=>h('section',{className:'crm-profile-section'},h('h3',null,title),h('div',{className:'crm-profile-grid'},keys.map(profileField)));
  return h('dialog',{ref:profileDialogRef,className:'crm-profile-dialog crm-customer-dialog',style:{'--kc-section-icon':'#95bfff','--kc-section-action':'#2e64aa'},'aria-labelledby':'crm-customer-title',onCancel:e=>{e.preventDefault();e.stopPropagation();if(!busy)Edit(null);}},
   h('form',{'aria-label':t('ฟอร์มลูกค้า','Customer form'),onSubmit:save},
    h('header',{className:'crm-profile-header'},h('span',{className:'crm-profile-symbol','aria-hidden':true},'▦'),h('div',null,h('h2',{id:'crm-customer-title'},editing.id?t('แก้ไขลูกค้า','Edit Account'):t('สร้างลูกค้า','New Account')),h('p',null,t('ข้อมูลที่มี * จำเป็นต้องระบุ','* Required fields'))),btn('×',()=>Edit(null),busy,{'aria-label':t('ปิดฟอร์ม','Close form'),className:'crm-profile-close'})),
    h('div',{className:'crm-profile-body'},error&&h('p',{role:'alert',className:'crm-error'},error),
     profileSection(t('เกี่ยวกับลูกค้า','About'),['name','website','type','description','parent_customer_id','owner_id']),
     profileSection(t('ข้อมูลติดต่อ','Get in Touch'),['phone','email']),
     !editing.id&&h('section',{className:'crm-profile-section'},h('h3',null,t('ผู้ติดต่อหลัก','Primary Contact')),h('p',null,t('กรอกเพื่อสร้างผู้ติดต่อและเชื่อมกับลูกค้านี้ หรือเว้นว่างทั้งหมดเพื่อเพิ่มภายหลัง','Fill in to create a linked contact, or leave all fields blank to add later')),h('div',{className:'crm-profile-grid'},[['first_name','ชื่อผู้ติดต่อ','Contact First Name'],['last_name','นามสกุลผู้ติดต่อ','Contact Last Name'],['position','ตำแหน่งผู้ติดต่อ','Contact Position'],['phone','เบอร์โทรผู้ติดต่อ','Contact Phone'],['email','อีเมลผู้ติดต่อ','Contact Email']].map(([key,th,en])=>h('label',{key,className:'crm-field'},h('span',null,t(th,en)),h('input',{'aria-label':t(th,en),type:key==='email'?'email':key==='phone'?'tel':'text',maxLength:250,disabled:busy,value:editing.primary_contact?.[key]||'',onChange:e=>Edit(v=>({...v,primary_contact:{...v.primary_contact,[key]:e.target.value}}))}))))),
     profileSection(t('ที่อยู่สำหรับเรียกเก็บเงิน','Billing Address'),['billing_country','address','billing_city','province','billing_postal_code']),
     h('div',{className:'crm-customer-copy'},btn(t('ใช้ที่อยู่เรียกเก็บเงินเป็นที่อยู่จัดส่ง','Copy billing to shipping'),()=>Edit(v=>({...v,shipping_country:v.billing_country,shipping_street:v.address,shipping_city:v.billing_city,shipping_state:v.province,shipping_postal_code:v.billing_postal_code})),busy)),
     profileSection(t('ที่อยู่สำหรับจัดส่ง','Shipping Address'),['shipping_country','shipping_street','shipping_city','shipping_state','shipping_postal_code']),
     h('details',{className:'crm-profile-additional'},h('summary',null,t('ข้อมูลเพิ่มเติมใน CRM','Additional CRM Information')),h('div',{className:'crm-profile-grid'},['name_en','industry','tier','tax_id','status'].map(profileField)))),
    h('footer',{className:'crm-profile-footer'},btn(t('ยกเลิก','Cancel'),()=>Edit(null),busy),!editing.id&&h('button',{type:'submit',value:'save-new',disabled:busy},t('บันทึกและเพิ่มใหม่','Save & New')),h('button',{type:'submit',value:'save',disabled:busy,className:'crm-save'},t('บันทึก','Save')))));

};}
