import {BLOCKS,newBlock,readDesign,renderDesign,designPayload,safeURL} from './email-studio-model.mjs?v=20261004';
export function createEmailStudio(React){const h=React.createElement;
 return function EmailStudio({value,onChange,lang,busy}){
 const tr=(a,b)=>lang==='th'?a:b,[history,H]=React.useState(()=>[readDesign(value.html)]),[at,A]=React.useState(0),[selected,S]=React.useState(()=>readDesign(value.html)?.blocks[0]?.id),[device,D]=React.useState('desktop'),[preview,P]=React.useState(false);
 const design=history[at],block=design.blocks.find(b=>b.id===selected),index=design.blocks.findIndex(b=>b.id===selected);
 function commit(next){H(old=>[...old.slice(0,at+1),next].slice(-60));A(Math.min(at+1,59));onChange(designPayload(next));}
 function travel(next){A(next);onChange(designPayload(history[next]));}
 function patch(p){commit({...design,blocks:design.blocks.map(b=>b.id===selected?{...b,...p}:b)});}
 function add(type){if(design.blocks.length>=60)return;const b=newBlock(type,lang);commit({...design,blocks:[...design.blocks,b]});S(b.id);P(false);}
 function move(offset){const items=[...design.blocks],target=index+offset;if(target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];commit({...design,blocks:items});}
 const button=(label,fn,extra={})=>h('button',{type:'button',disabled:busy,onClick:fn,...extra},label);
 const field=(label,key,type='text')=>h('label',null,h('span',null,label),h(type==='textarea'?'textarea':'input',{'aria-label':label,type:type==='textarea'?undefined:type,rows:type==='textarea'?5:undefined,value:block?.[key]||'',disabled:busy,onChange:e=>patch({[key]:e.target.value})}));
 const label=type=>{const b=BLOCKS.find(x=>x[0]===type);return b?.[lang==='th'?1:2]||type;};
 const content=b=>b.type==='heading'?h('h2',null,b.text):b.type==='text'?h('p',null,b.text):b.type==='list'?h('ul',null,b.text.split('\n').map((x,i)=>h('li',{key:i},x))):b.type==='image'?(safeURL(b.url,true)?h('img',{src:safeURL(b.url,true),alt:b.alt,referrerPolicy:'no-referrer'}):h('div',{className:'es-image-empty'},tr('รูปภาพ · เพิ่ม URL ในแผงปรับแต่ง','Image · Add a URL in properties'))):b.type==='button'?h('span',{className:'es-email-cta',style:{background:design.brand}},b.text):b.type==='divider'?h('hr',{style:{borderColor:design.brand}}):h('div',{className:'es-spacer','aria-label':label('spacer')});
 return h('section',{className:'email-studio','aria-label':'Email Studio'},
 h('div',{className:'es-toolbar'},h('div',null,h('strong',null,'Email Studio'),h('small',null,tr('ออกแบบเรื่องราวที่น่าจดจำ','Make every message meaningful'))),h('div',{className:'es-tools'},button(tr('คอมพิวเตอร์','Desktop'),()=>D('desktop'),{'aria-pressed':device==='desktop'}),button(tr('มือถือ','Mobile'),()=>D('mobile'),{'aria-pressed':device==='mobile'}),button(tr('ย้อนการแก้ไข','Undo'),()=>travel(at-1),{disabled:busy||at===0}),button(tr('ทำซ้ำการแก้ไข','Redo'),()=>travel(at+1),{disabled:busy||at===history.length-1}),button(preview?tr('กลับไปออกแบบ','Back to design'):tr('ดูตัวอย่าง','Preview'),()=>P(v=>!v),{'aria-pressed':preview}))),
 h('div',{className:'es-workspace'},h('aside',{className:'es-palette'},h('h3',null,tr('เพิ่มเนื้อหา','Add content')),h('p',null,tr('เลือกบล็อกเพื่อเพิ่มในอีเมล','Choose a block for your email')),h('div',{className:'es-block-tools'},BLOCKS.map(([type,th,en])=>button(h(React.Fragment,null,h('b',{'aria-hidden':true},({heading:'H',text:'Aa',image:'▧',button:'↗',list:'☷',divider:'—',spacer:'↕'})[type]),h('span',null,tr(th,en))),()=>add(type),{key:type,'aria-label':tr('เพิ่ม','Add ')+tr(th,en),disabled:busy||design.blocks.length>=60}))),h('label',null,h('span',null,tr('สีแบรนด์','Brand color')),h('input',{type:'color',value:design.brand,'aria-label':tr('สีแบรนด์','Brand color'),disabled:busy,onChange:e=>commit({...design,brand:e.target.value})})),h('label',null,h('span',null,tr('สีพื้นหลัง','Background color')),h('input',{type:'color',value:design.background,'aria-label':tr('สีพื้นหลัง','Background color'),disabled:busy,onChange:e=>commit({...design,background:e.target.value})})),h('small',null,tr('ใช้ {{name}} เพื่อแทนชื่อผู้รับ','Use {{name}} for recipient name'))),
 h('div',{className:'es-canvas',style:{background:design.background}},h('div',{className:'es-device-label'},device==='mobile'?'MOBILE · 375 PX':'DESKTOP · 600 PX'),preview?h('iframe',{title:tr('ตัวอย่างแม่แบบ','Template preview'),className:'es-preview','data-device':device,sandbox:'',referrerPolicy:'no-referrer',srcDoc:'<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src https:;"><style>body{margin:0}table{border-collapse:collapse}p{line-height:1.7}img{height:auto}</style>'+renderDesign(design,false)}):h('div',{className:'es-email','data-device':device},!design.blocks.length&&h('p',{className:'es-empty'},tr('เพิ่มบล็อกเพื่อเริ่มออกแบบ','Add a block to start designing')),design.blocks.map((b,i)=>h('div',{key:b.id,className:'es-block','data-selected':selected===b.id,'data-tone':b.tone,style:{textAlign:b.align},role:'button',tabIndex:busy?-1:0,'aria-label':label(b.type)+' '+(i+1),'aria-pressed':selected===b.id,onClick:()=>!busy&&S(b.id),onKeyDown:e=>{if(!busy&&['Enter',' '].includes(e.key)){e.preventDefault();S(b.id);}}},content(b))))),
 h('aside',{className:'es-properties'},h('h3',null,tr('ปรับแต่งบล็อก','Block properties')),block?h(React.Fragment,null,h('small',null,label(block.type)+' · '+(index+1)+' / '+design.blocks.length),!['image','divider','spacer'].includes(block.type)&&field(tr('เนื้อหาบล็อก','Block content'),'text','textarea'),block.type==='image'&&h(React.Fragment,null,field(tr('URL รูปภาพ HTTPS','Image HTTPS URL'),'url','url'),field(tr('คำอธิบายรูปภาพ','Image description'),'alt'),block.url&&!safeURL(block.url,true)&&h('p',{role:'alert'},tr('กรุณาใช้ URL รูปภาพ HTTPS','Use an HTTPS image URL'))),block.type==='button'&&field(tr('ลิงก์ปลายทาง','Destination URL'),'url'),h('label',null,h('span',null,tr('จัดตำแหน่ง','Alignment')),h('select',{'aria-label':tr('จัดตำแหน่ง','Alignment'),value:block.align,disabled:busy,onChange:e=>patch({align:e.target.value})},['left','center','right'].map((v,i)=>h('option',{key:v,value:v},[tr('ซ้าย','Left'),tr('กึ่งกลาง','Center'),tr('ขวา','Right')][i])))),h('label',null,h('span',null,tr('พื้นบล็อก','Block tone')),h('select',{'aria-label':tr('พื้นบล็อก','Block tone'),value:block.tone,disabled:busy,onChange:e=>patch({tone:e.target.value})},h('option',{value:'light'},tr('สว่าง','Light')),h('option',{value:'dark'},tr('กรมท่า','Navy')))),h('div',{className:'es-block-actions'},button(tr('เลื่อนขึ้น','Move up'),()=>move(-1),{disabled:busy||index===0}),button(tr('เลื่อนลง','Move down'),()=>move(1),{disabled:busy||index===design.blocks.length-1}),button(tr('ทำสำเนาบล็อก','Duplicate block'),()=>{const b={...block,id:crypto.randomUUID()},items=[...design.blocks];items.splice(index+1,0,b);commit({...design,blocks:items});S(b.id);},{disabled:busy||design.blocks.length>=60}),button(tr('ลบบล็อก','Delete block'),()=>{const items=design.blocks.filter(b=>b.id!==selected);commit({...design,blocks:items});S(items[Math.min(index,items.length-1)]?.id);},{className:'es-delete'}))):h('p',null,tr('เลือกบล็อกในอีเมลเพื่อแก้ไข','Select an email block to edit')))),
 h('p',{className:'es-note'},tr('บันทึกแม่แบบเพื่อนำกลับมาใช้ · ลิงก์ยกเลิกรับอีเมลจะเพิ่มเมื่อส่งจริง','Save a reusable template · Unsubscribe link is added when sending')));
 };
}
