import {ENTITIES,LABELS,summarizePipeline} from './internal-model.mjs';
import {DEMO_RECORDS} from './internal-workspace.mjs?v=20261001-template-assets';
import {toCSV} from './settings-model.mjs';
export function createInternalReports({React,client,useApp}){
 const h=React.createElement;
 return function Reports({lang}){
  const {demoMode,profile,navigate}=useApp(),t=(th,en)=>lang==='th'?th:en;
  const [entity,Entity]=React.useState('opportunities'),[rows,Rows]=React.useState([]),[error,ErrorText]=React.useState(''),[busy,Busy]=React.useState(false),[owner,Owner]=React.useState(''),[from,From]=React.useState(''),[to,To]=React.useState(''),[group,Group]=React.useState('status'),[refresh,Refresh]=React.useState(0),[canExport,CanExport]=React.useState(false);
  React.useEffect(()=>{let active=true;Busy(true);ErrorText('');Rows([]);(async()=>{try{let data=[];if(demoMode)data=DEMO_RECORDS[entity];else{for(let page=0;page<20000;page+=500){const r=await client.from(entity).select('*').order('id').range(page,page+499);if(r.error)throw r.error;data.push(...r.data);if(r.data.length<500)break;if(page===19500)throw Error('More than 20,000 rows; use narrower reporting scope');}}let allowed=demoMode||profile?.role==='admin';if(!allowed){const r=await client.from('role_permissions').select('can_export').eq('role_key',profile?.role==='custom'?profile.custom_role_key:profile?.role||'').eq('module',entity).maybeSingle();if(r.error)throw r.error;allowed=!!r.data?.can_export;}if(active){Rows(data);CanExport(allowed);}}catch(e){if(active)ErrorText(e.message);}finally{if(active)Busy(false);}})();return()=>{active=false;};},[entity,demoMode,profile?.id,refresh]);
  const valueKey={opportunities:'amount',quotations:'total',contracts:'value'}[entity],dateKey={opportunities:'close_date',contracts:'end_date',activities:'scheduled_at'}[entity]||'created_at';
  const filtered=rows.filter(r=>(!owner||(r.owner_name||r.assigned_to_name)===owner)&&(!from||String(r[dateKey]||'').slice(0,10)>=from)&&(!to||String(r[dateKey]||'').slice(0,10)<=to));
  const groups={};for(const r of filtered){const key=String(r[group]||t('ไม่ระบุ','Unspecified'));groups[key]??={count:0,value:0};groups[key].count++;groups[key].value+=Number(r[valueKey]||0);}
  const select=(title,value,set,opts)=>h('label',{className:'crm-field'},h('span',null,title),h('select',{'aria-label':title,value,onChange:e=>set(e.target.value)},opts.map(([v,n])=>h('option',{key:v,value:v},n))));
  const format=n=>new Intl.NumberFormat(lang==='th'?'th-TH':'en-US',{maximumFractionDigits:2}).format(n);
  function exportCSV(){const columns=[...new Set(['code',ENTITIES[entity].name,'customer_name','owner_name','status',dateKey,...(valueKey?[valueKey]:[])])];const url=URL.createObjectURL(new Blob([toCSV(filtered,columns)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='report-'+entity+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const metric=entity==='opportunities'?summarizePipeline(filtered):null;
  return h('section',{className:'crm-settings crm-internal'},h('h1',null,t('รายงานและการวิเคราะห์','Reports and analytics')),h('p',null,t('คำนวณจากรายการที่คุณมีสิทธิ์เห็น ยอดโอกาสขายไม่ใช่รายได้ลงบัญชี','Computed from records you can access. Opportunity values are not recognized accounting revenue.')),error&&h('p',{role:'alert',className:'crm-error'},error),h('div',{className:'crm-grid'},select(t('ชุดข้อมูล','Dataset'),entity,v=>{Entity(v);Owner('');Group('status');},['leads','customers','contacts','opportunities','quotations','contracts','assets','tickets','activities','documents'].map(k=>[k,ENTITIES[k].title[lang==='th'?0:1]])),select(t('ผู้รับผิดชอบ','Owner'),owner,Owner,[['',t('ทุกคน','All')],...[...new Set(rows.map(r=>r.owner_name||r.assigned_to_name).filter(Boolean))].map(x=>[x,x])]),select(t('จัดกลุ่มตาม','Group by'),group,Group,[['status',t('สถานะ','Status')],['owner_name',t('ผู้รับผิดชอบ','Owner')],['customer_name',t('ลูกค้า','Customer')],...(entity==='opportunities'?[['stage',t('ขั้นตอนขาย','Stage')]]:[])]),...[[t('ตั้งแต่วันที่','From date'),from,From],[t('ถึงวันที่','To date'),to,To]].map(([label,value,set])=>h('label',{className:'crm-field',key:label},h('span',null,label),h('input',{type:'date','aria-label':label,value,onChange:e=>set(e.target.value)})))),h('div',{className:'crm-actions'},h('button',{onClick:()=>Refresh(v=>v+1),disabled:busy},t('โหลดใหม่','Reload')),canExport&&h('button',{onClick:exportCSV,disabled:busy},t('ส่งออก CSV','Export CSV'))),h('p',{role:'status'},busy?t('กำลังโหลด…','Loading…'):filtered.length+' '+t('รายการ','records')),metric&&h('div',{className:'crm-grid'},Object.entries(metric).map(([key,n])=>h('div',{key,className:'crm-master-form'},key,h('p',null,format(n))))),h('table',{className:'crm-master-table'},h('thead',null,h('tr',null,h('th',null,t('กลุ่ม','Group')),h('th',null,t('จำนวน','Count')),valueKey&&h('th',null,t('มูลค่า','Value')))),h('tbody',null,Object.entries(groups).map(([key,v])=>h('tr',{key},h('td',null,key),h('td',null,v.count),valueKey&&h('td',null,format(v.value)))))),h('h2',null,t('รายการประกอบรายงาน (100 รายการแรก)','Supporting records (first 100)')),h('div',{className:'crm-table-scroll'},h('table',{className:'crm-master-table'},h('tbody',null,filtered.slice(0,100).map(r=>h('tr',{key:r.id},h('td',null,r.code||r[ENTITIES[entity].name]),h('td',null,r.customer_name||r.name||r.subject||r.company_name),h('td',null,r.status),h('td',null,h('button',{onClick:()=>navigate(entity,{leads:'lead-inbox',customers:'customer-list',contacts:'contact-list',opportunities:'opp-kanban',quotations:'quot-list',contracts:'con-all',assets:'asset-all',tickets:'tk-all',activities:'act-my',documents:'doc-all'}[entity],{recordId:r.id})},t('รายละเอียด','Details')))))))));
 };
}
