import {resolvePaymentTerm} from './quotation-payment-terms.mjs';
import {OPTIONS} from './internal-options.mjs';
import {fullPersonName} from './record-profile.mjs?v=20260930-accounts';
export const ENTITIES={
 branches:{table:'crm_branches',module:'customers',title:['สาขาลูกค้า','Customer branches'],name:'name',fields:'name*,code,customer_id@,address~,phone,status',statuses:['active','inactive']},
 prices:{table:'crm_price_items',module:'quotations',title:['รายการสินค้าและราคา','Products and prices'],name:'name',fields:'name*,code*,category,unit,price#,cost#,description~,status',statuses:['active','inactive']},
 templates:{table:'crm_templates',module:'documents',title:['แม่แบบเอกสาร','Document templates'],name:'name',fields:'name*,type,description~,header~,footer~,status',statuses:['active','inactive']},
 knowledge:{table:'crm_knowledge_articles',module:'tickets',title:['ฐานความรู้','Knowledge base'],name:'name',fields:'name*,category,description~,status',statuses:['draft','published','archived']},
 documents:{title:['เอกสาร','Documents'],name:'name',fields:'name*,customer_id@,type,version,status,owner_id@',statuses:['draft','active','archived']},
 leads:{title:['ลูกค้าเป้าหมาย','Leads'],name:'company_name',fields:'company_name*,salutation,first_name,last_name*,contact_name,position,phone,mobile,email,website,line_id,customer_id@,source,product_interest,budget,score#,status,priority,owner_id@,mailing_country,mailing_street~,mailing_city,mailing_state,mailing_postal_code,next_action,note~',statuses:['new','contacted','qualified','disqualified','follow-up','converted'],create:'new-lead'},
 customers:{title:['ลูกค้า','Accounts'],name:'name',fields:'name*,name_en,type,industry,tier,tax_id,phone,email,website,description~,parent_customer_id@,address~,billing_country,billing_city,province,billing_postal_code,shipping_country,shipping_street~,shipping_city,shipping_state,shipping_postal_code,status,owner_id@',statuses:['active','inactive']},
 contacts:{title:['ผู้ติดต่อ','Contacts'],name:'name',fields:'salutation,first_name,last_name*,name*,customer_id@,position,reports_to_id@,department,role,phone,mobile,email,line_id,is_primary?,influence_level,status,owner_id@,description~,mailing_country,mailing_street~,mailing_city,mailing_state,mailing_postal_code,next_action',statuses:['active','inactive']},
 opportunities:{title:['โอกาสการขาย','Opportunities'],name:'name',fields:'name*,customer_id*@,contact_id@,product,solution~,stage*,amount#,probability#,close_date*:,forecast_category*,owner_id*@,competitor,lost_reason,next_action,status,priority',statuses:['open','won','lost']},
 quotations:{title:['ใบเสนอราคา','Quotations'],name:'code',fields:'customer_id@,contact_id@,opportunity_id@,issue_date*:,valid_until:,payment_terms#,payment_term_code,tax_rate#,wht_rate#,project_name,prepared_by,prepared_by_email,prepared_by_phone,counterparty_address~,counterparty_tax_id,reference_document,payment_instructions~,document_language,currency,document_discount#,reviewed_by,approved_by,owner_id*@,note~',statuses:['draft','submitted','approved','rejected','sent','accepted','expired']},
 contracts:{title:['สัญญาและการต่ออายุ','Contracts and renewal'],name:'name',fields:'name*,customer_id@,quotation_id@,opportunity_id@,type,product,value#,start_date:,end_date:,owner_id@,renewal_owner_id@,renewal_status,sla_level,service_sla_id@,auto_renew?,status',statuses:['active','expired','renewed','lost','cancelled']},
 assets:{title:['สินทรัพย์ลูกค้า','Customer assets'],name:'name',fields:'name*,customer_id@,contract_id@,category,brand,model,serial_number,product_id@,branch_id@,assigned_user_id@,location,purchase_date:,installation_date:,warranty_start:,warranty_end:,warranty_type,warranty_provider,vendor,distributor,next_maintenance:,status,owner_id@',statuses:['active','inactive','maintenance','retired']},
 tickets:{title:['งานบริการ','Service tickets'],name:'subject',fields:'subject*,customer_id@,contact_id@,type,priority,status,assigned_to_id@,asset_id@,contract_id@,sla_policy,sla_deadline;,description~,resolution~',statuses:['open','in-progress','pending','resolved','closed']},
 activities:{title:['กิจกรรมและงานติดตาม','Activities and follow-ups'],name:'subject',fields:'subject*,customer_id@,contact_id@,type,status,priority,scheduled_at*;,reminder_at;,owner_id@,description~,next_action,meeting_url',statuses:['planned','in-progress','completed','cancelled']}
};
for(const [key,value] of Object.entries(OPTIONS))if(ENTITIES[key]&&value.status)ENTITIES[key].statuses=value.status;
export const LABELS={company_name:'ชื่อบริษัท',name:'ชื่อ',name_en:'ชื่อภาษาอังกฤษ',subject:'หัวข้อ',contact_name:'ชื่อผู้ติดต่อ',position:'ตำแหน่ง',phone:'โทรศัพท์',email:'อีเมล',source:'แหล่งที่มา',product_interest:'สินค้าที่สนใจ',budget:'งบประมาณ',score:'คะแนน',status:'สถานะ',priority:'ความสำคัญ',owner_id:'พนักงานขาย/ผู้รับผิดชอบ',next_action:'งานถัดไป',note:'หมายเหตุ',type:'ประเภท',industry:'ธุรกิจ',tier:'ระดับลูกค้า',tax_id:'เลขผู้เสียภาษี',website:'เว็บไซต์',address:'ที่อยู่',province:'จังหวัด',customer_id:'ลูกค้า',contact_id:'ผู้ติดต่อ',department:'แผนก',role:'บทบาท',is_primary:'ผู้ติดต่อหลัก',influence_level:'ระดับอำนาจตัดสินใจ',product:'สินค้า/บริการ',solution:'รายละเอียดโซลูชัน',stage:'ขั้นตอนการขาย',amount:'มูลค่า',probability:'โอกาสชนะ (%)',close_date:'วันที่คาดว่าจะปิด',forecast_category:'หมวดคาดการณ์',competitor:'คู่แข่ง',lost_reason:'เหตุผลที่แพ้',opportunity_id:'โอกาสการขาย',valid_until:'วันหมดอายุ',value:'มูลค่าสัญญา',start_date:'วันที่เริ่ม',end_date:'วันที่สิ้นสุด',renewal_owner_id:'ผู้รับผิดชอบต่ออายุ',renewal_status:'สถานะต่ออายุ',sla_level:'ระดับ SLA',auto_renew:'ติดตามต่ออายุอัตโนมัติ',contract_id:'สัญญา',category:'หมวดหมู่',brand:'ยี่ห้อ',model:'รุ่น',serial_number:'หมายเลขเครื่อง',location:'สถานที่',warranty_start:'วันเริ่มประกัน',warranty_end:'วันสิ้นสุดประกัน',assigned_to_id:'ผู้รับผิดชอบ',asset_id:'สินทรัพย์',sla_policy:'นโยบาย SLA',sla_deadline:'กำหนด SLA',description:'รายละเอียด',resolution:'วิธีแก้ไข',scheduled_at:'วันเวลานัดหมาย',reminder_at:'วันเวลาเตือน',meeting_url:'ลิงก์ประชุม',header:'ข้อความหัวเอกสาร',footer:'ข้อความท้ายเอกสาร',price:'ราคา',cost:'ต้นทุน',unit:'หน่วย',version:'เวอร์ชัน',code:'รหัส',total:'ยอดรวม',approval_status:'สถานะอนุมัติ',issue_date:'วันที่เอกสาร',payment_terms:'เครดิต (วัน)',tax_rate:'VAT (%)',wht_rate:'หัก ณ ที่จ่าย (%)',project_name:'แผนก / โครงการ',prepared_by:'ผู้จัดทำ',prepared_by_email:'อีเมลผู้จัดทำ',prepared_by_phone:'เบอร์โทรผู้จัดทำ',counterparty_address:'ที่อยู่ลูกค้า',counterparty_tax_id:'เลขผู้เสียภาษีลูกค้า',reference_document:'อ้างอิงเอกสาร',payment_instructions:'เงื่อนไข / ข้อมูลการชำระเงิน',document_language:'ภาษาเอกสาร',currency:'สกุลเงิน',document_discount:'ส่วนลดรวม',reviewed_by:'ผู้ตรวจสอบ',approved_by:'ผู้อนุมัติ',quotation_id:'ใบเสนอราคา',customer_name:'ลูกค้า',owner_name:'ผู้รับผิดชอบ',updated_at:'แก้ไขล่าสุด'};
export const MASTER_FIELDS={source:'lead_source',industry:'industry',tier:'tier',stage:'sales_stage',lost_reason:'loss_reason',brand:'asset_brand',model:'asset_model',location:'asset_location'};
export const RELATIONS={product_id:'products',branch_id:'crm_branches',assigned_user_id:'contacts',service_sla_id:'crm_service_sla_policies',parent_customer_id:'customers',customer_id:'customers',contact_id:'contacts',reports_to_id:'contacts',opportunity_id:'opportunities',quotation_id:'quotations',contract_id:'contracts',asset_id:'assets',owner_id:'profiles',assigned_to_id:'profiles',renewal_owner_id:'profiles'};
export function fieldsFor(entity){return ENTITIES[entity].fields.split(',').map(raw=>({key:raw.replace(/[*!#@?:;~]/g,''),required:raw.includes('*')||raw==='customer_id@'&&['quotations','contacts','branches'].includes(entity),type:raw.includes('#')?'number':raw.includes('@')?'relation':raw.includes('?')?'checkbox':raw.includes(';')?'datetime-local':raw.includes(':')?'date':raw.includes('~')?'textarea':'text'}));}
export function validateRecord(entity,input){if(['leads','contacts'].includes(entity)){input={...input};const key=entity==='leads'?'contact_name':'name';if(input.last_name===undefined&&input[key])input.last_name=input[key];input[key]=fullPersonName(input);}const out={};for(const f of fieldsFor(entity)){let v=input[f.key];if(f.type==='checkbox')v=!!v;else if(f.type==='number'){if(v===''||v==null)v=0;v=Number(v);if(!Number.isFinite(v)||v<0||(['score','probability'].includes(f.key)&&v>100))throw Error('Invalid number: '+f.key);}else{v=String(v??'').trim();if(f.required&&!v)throw Error('Required: '+f.key);if(v.length>10000)throw Error('Value too long: '+f.key);if(['date','datetime-local'].includes(f.type)){if(v&&Number.isNaN(Date.parse(v)))throw Error('Invalid date: '+f.key);v=v?(f.type==='date'?v.slice(0,10):new Date(v).toISOString()):null;}if(f.type==='relation')v=v||null;}out[f.key]=v;}
 if(entity==='quotations'){const term=resolvePaymentTerm(out.payment_term_code,out.payment_terms);out.payment_term_code=term.code;out.payment_terms=term.days;}
 if(out.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out.email))throw Error('Invalid email');
 if(out.end_date&&out.start_date&&out.end_date<out.start_date)throw Error('End date precedes start date');
 if(entity==='opportunities'){if(!Number.isInteger(out.probability)||out.amount>=1e15)throw Error('Invalid opportunity amount or probability');if(!OPTIONS.opportunities.forecast_category.includes(out.forecast_category))throw Error('Invalid forecast category');out.weighted_amount=Math.round(out.amount*out.probability)/100;if(out.stage==='Won')out.status='won';if(out.stage==='Lost')out.status='lost';if(out.status==='won'){out.stage='Won';out.probability=100;out.weighted_amount=out.amount;out.forecast_category='Closed Won';}if(out.status==='lost'){out.stage='Lost';out.probability=0;out.weighted_amount=0;out.forecast_category='Closed Lost';if(!out.lost_reason)throw Error('Lost reason required');}if(out.status==='open'&&out.forecast_category.startsWith('Closed'))throw Error('Open opportunity cannot use a closed forecast category');}
 if(entity==='tickets'&&['resolved','closed'].includes(out.status)&&!out.resolution)throw Error('Resolution required');
 return out;
}
export function quoteTotals(items,{taxRate=7,withholdingRate=0,documentDiscount=0}={}){if(!Array.isArray(items)||!items.length)throw Error('At least one item required');const round=n=>Math.round((Number(n)+Number.EPSILON)*100)/100;taxRate=Number(taxRate??7);withholdingRate=Number(withholdingRate??0);documentDiscount=Number(documentDiscount??0);if(![taxRate,withholdingRate,documentDiscount].every(Number.isFinite)||taxRate<0||taxRate>100||withholdingRate<0||withholdingRate>100||documentDiscount<0)throw Error('Invalid quotation totals');const clean=items.map(i=>{const x={price_item_id:String(i.price_item_id??''),code:String(i.code??''),name:String(i.name??'').trim(),desc:String(i.desc??''),unit:String(i.unit||'Unit'),qty:Number(i.qty),price:Number(i.price),discount:Number(i.discount||0),cost:Number(i.cost||0)};if(!x.name||!Number.isFinite(x.qty)||x.qty<=0||![x.price,x.discount,x.cost].every(n=>Number.isFinite(n)&&n>=0)||x.discount>x.qty*x.price)throw Error('Invalid quotation item');const gross=x.qty*x.price,lineNet=gross-x.discount,lineCost=x.qty*x.cost;x.total=round(lineNet);x.gp=round(lineNet-lineCost);x.margin=lineNet?round(x.gp/lineNet*100):0;return x;});const subtotal=round(clean.reduce((sum,item)=>sum+item.qty*item.price,0)),lineDiscount=round(clean.reduce((sum,item)=>sum+item.discount,0)),available=round(subtotal-lineDiscount);if(documentDiscount>available)throw Error('Document discount exceeds quotation value');const discount=round(lineDiscount+documentDiscount),net_before_tax=round(subtotal-discount),vat=round(net_before_tax*taxRate/100),total=round(net_before_tax+vat),withholding_tax=round(net_before_tax*withholdingRate/100),net_total=round(total-withholding_tax),cost_total=round(clean.reduce((sum,item)=>sum+item.qty*item.cost,0)),gp_amount=round(net_before_tax-cost_total),gp_margin=net_before_tax?round(gp_amount/net_before_tax*100):0;return {items:clean,subtotal,line_discount:lineDiscount,document_discount:round(documentDiscount),discount,net_before_tax,tax_rate:taxRate,vat,total,wht_rate:withholdingRate,withholding_tax,net_total,cost_total,gp_amount,gp_margin};}
export function duplicateIds(rows,entity){const fields=entity==='leads'?['email','phone','company_name']:entity==='customers'?['tax_id','name']:['email','phone'];const seen=new Map(),ids=new Set();for(const r of rows)for(const f of fields){let v=String(r[f]||'').normalize('NFKC').trim().toLowerCase();if(f==='phone')v=v.replace(/\D/g,'');if(!v)continue;const k=f+':'+v;if(seen.has(k)){ids.add(r.id);ids.add(seen.get(k));}else seen.set(k,r.id);}return ids;}
export function summarizePipeline(rows){const won=rows.filter(x=>x.status==='won'),lost=rows.filter(x=>x.status==='lost'),open=rows.filter(x=>!['won','lost'].includes(x.status));const sum=rs=>rs.reduce((n,r)=>n+Number(r.amount||0),0);return {count:rows.length,won:sum(won),pipeline:sum(open),weighted:open.reduce((n,r)=>n+Number(r.amount||0)*Number(r.probability||0)/100,0),winRate:won.length+lost.length?won.length/(won.length+lost.length)*100:0,averageDeal:won.length?sum(won)/won.length:0};}
export function filterRows(rows,{query='',status='',mine=false,ownerId,duplicates=false,entity,from='',to=''}={}){const dupes=duplicates?duplicateIds(rows,entity):null;return rows.filter(r=>(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()))&&(!status||r.status===status)&&(!mine||(r.owner_id||r.assigned_to_id)===ownerId)&&(!dupes||dupes.has(r.id))&&(!from||String(r.close_date||r.scheduled_at||r.end_date||r.created_at||'').slice(0,10)>=from)&&(!to||String(r.close_date||r.scheduled_at||r.end_date||r.created_at||'').slice(0,10)<=to));}

