import {ENTITIES,LABELS,summarizePipeline} from './internal-model.mjs';
import {DEMO_RECORDS} from './internal-workspace.mjs?v=20261001-master-popup';
import {toCSV} from './settings-model.mjs';
export function createInternalReports({React,client,useApp,TargetSummary}){
 const h=React.createElement;
 function Records({lang,tabs}){
  const {demoMode,profile,navigate}=useApp(),t=(th,en)=>lang==='th'?th:en;
  const [page,Page]=React.useState(0);
  const [entity,Entity]=React.useState('opportunities'),[rows,Rows]=React.useState([]),[error,ErrorText]=React.useState(''),[busy,Busy]=React.useState(false),[owner,Owner]=React.useState(''),[from,From]=React.useState(''),[to,To]=React.useState(''),[group,Group]=React.useState('status'),[refresh,Refresh]=React.useState(0),[canExport,CanExport]=React.useState(false);
  React.useEffect(()=>{let active=true;Busy(true);ErrorText('');Rows([]);(async()=>{try{let data=[];if(demoMode)data=DEMO_RECORDS[entity];else{for(let page=0;page<20000;page+=500){const r=await client.from(entity).select('*').order('id').range(page,page+499);if(r.error)throw r.error;data.push(...r.data);if(r.data.length<500)break;if(page===19500)throw Error('More than 20,000 rows; use narrower reporting scope');}}let allowed=demoMode||profile?.is_super_admin===true;if(!allowed){const r=await client.from('role_permissions').select('can_export').eq('role_key',profile?.role==='custom'?profile.custom_role_key:profile?.role||'').eq('module',entity).maybeSingle();if(r.error)throw r.error;allowed=!!r.data?.can_export;}if(active){Rows(data);CanExport(allowed);}}catch(e){if(active)ErrorText(e.message);}finally{if(active)Busy(false);}})();return()=>{active=false;};},[entity,demoMode,profile?.id,refresh]);
  const valueKey={opportunities:'amount',quotations:'total',contracts:'value'}[entity],dateKey={opportunities:'close_date',contracts:'end_date',activities:'scheduled_at'}[entity]||'created_at';
  const filtered=rows.filter(r=>(!owner||(r.owner_name||r.assigned_to_name)===owner)&&(!from||String(r[dateKey]||'').slice(0,10)>=from)&&(!to||String(r[dateKey]||'').slice(0,10)<=to));
  const groups={};for(const r of filtered){const key=String(r[group]||t('ไม่ระบุ','Unspecified'));groups[key]??={count:0,value:0};groups[key].count++;groups[key].value+=Number(r[valueKey]||0);}
  const select=(title,value,set,opts)=>h('label',{className:'crm-field'},h('span',null,title),h('select',{'aria-label':title,value,onChange:e=>set(e.target.value)},opts.map(([v,n])=>h('option',{key:v,value:v},n))));
  const format=n=>new Intl.NumberFormat(lang==='th'?'th-TH':'en-US',{maximumFractionDigits:2}).format(n);
  function exportCSV(){const columns=[...new Set(['code',ENTITIES[entity].name,'customer_name','owner_name','status',dateKey,...(valueKey?[valueKey]:[])])];const url=URL.createObjectURL(new Blob([toCSV(filtered,columns)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='report-'+entity+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const metric=entity==='opportunities'?summarizePipeline(filtered):null;
  React.useEffect(()=>Page(0),[entity,owner,from,to,group,refresh]);
  const pageSize=20,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(page,totalPages-1),start=currentPage*pageSize;
  const display=v=>String(v||'—').replace(/^\p{Ll}/u,c=>c.toUpperCase());
  const groupLabel={status:t('สถานะ','Status'),owner_name:t('ผู้รับผิดชอบ','Owner'),customer_name:t('ลูกค้า','Customer'),stage:t('ขั้นตอนขาย','Stage')}[group];
  const metrics=metric?[
   ['count',t('โอกาสทั้งหมด','Total opportunities'),metric.count,t('รายการ','records')],
   ['won',t('ชนะการขาย','Won'),filtered.filter(r=>r.status==='won').length,t('รายการ','records')],
   ['pipeline',t('มูลค่า Pipeline','Pipeline value'),metric.pipeline,t('โอกาสที่เปิดอยู่ · บาท','Open opportunities · THB')],
   ['weighted',t('มูลค่าถ่วงน้ำหนัก','Weighted value'),metric.weighted,t('บาท','THB')],
   ['winRate',t('อัตราชนะ','Win rate'),metric.winRate,t('จากดีลที่ปิดแล้ว','Of closed deals')],
   ['averageDeal',t('มูลค่าเฉลี่ยต่อดีล','Average deal'),metric.averageDeal,t('ดีลที่ชนะ · บาท','Won deals · THB')]
  ]:[];
  return h('section',{className:'kc-reports','aria-busy':busy},
   h('header',{className:'kc-reports-heading'},h('div',null,h('h1',null,t('รายงานและการวิเคราะห์','Reports and analytics')),h('p',null,t('ภาพรวมข้อมูล และรายละเอียดสำหรับติดตามผล','Your data overview and details to follow up'))),h('div',{className:'kc-report-actions'},h('button',{onClick:()=>Refresh(v=>v+1),disabled:busy},t('โหลดใหม่','Reload')),canExport&&h('button',{className:'kc-report-primary',onClick:exportCSV,disabled:busy},t('ส่งออก CSV','Export CSV')))),
   tabs,error&&h('p',{role:'alert',className:'crm-error'},error),
   h('div',{className:'kc-report-filters'},select(t('ชุดข้อมูล','Dataset'),entity,v=>{Entity(v);Owner('');Group('status');},['leads','customers','contacts','opportunities','quotations','contracts','assets','tickets','activities','documents'].map(k=>[k,ENTITIES[k].title[lang==='th'?0:1]])),select(t('ผู้รับผิดชอบ','Owner'),owner,Owner,[['',t('ทุกคน','All')],...[...new Set(rows.map(r=>r.owner_name||r.assigned_to_name).filter(Boolean))].map(x=>[x,x])]),select(t('จัดกลุ่มตาม','Group by'),group,Group,[['status',t('สถานะ','Status')],['owner_name',t('ผู้รับผิดชอบ','Owner')],['customer_name',t('ลูกค้า','Customer')],...(entity==='opportunities'?[['stage',t('ขั้นตอนขาย','Stage')]]:[])]),...[[t('ตั้งแต่วันที่','From date'),from,From],[t('ถึงวันที่','To date'),to,To]].map(([label,value,set])=>h('label',{className:'crm-field',key:label},h('span',null,label),h('input',{type:'date','aria-label':label,value,onChange:e=>set(e.target.value)})))),
   h('span',{className:'kc-report-live',role:'status'},busy?t('กำลังโหลด…','Loading…'):filtered.length+' '+t('รายการ','records')),
   metric&&h('div',{className:'kc-report-metrics'},metrics.map(([key,label,value,note])=>h('div',{key,className:'kc-report-metric'+(key==='pipeline'?' is-highlight':'')},h('span',null,label),h('strong',null,format(value)+(key==='winRate'?'%':'')),h('small',null,note)))),
   h('div',{className:'kc-report-body'},
   h('section',{className:'kc-report-panel kc-report-summary'},h('div',{className:'kc-report-panel-title'},h('h2',null,t('สรุปตาม','Summary by ')+groupLabel),h('span',null,format(filtered.length)+' '+t('รายการ','records'))),
    h('div',{className:'kc-report-summary-list'},Object.entries(groups).map(([key,v])=>h('div',{key,className:'kc-report-summary-item'},
     h('div',{className:'kc-report-summary-row'},h('span',{className:'kc-report-summary-name'},display(key)),h('strong',null,format(v.count)+' '+t('รายการ','records'))),
     h('div',{className:'kc-report-summary-track','aria-hidden':true},h('span',{className:['lost','cancelled','rejected'].includes(key)?'is-negative':'',style:{width:(filtered.length?v.count/filtered.length*100:0)+'%'}})),
     h('div',{className:'kc-report-summary-row kc-report-summary-meta'},h('span',null,format(filtered.length?v.count/filtered.length*100:0)+'%'),valueKey&&h('span',null,format(v.value)+' '+t('บาท','THB'))))),
     !filtered.length&&h('p',{className:'kc-report-empty'},t('ไม่พบข้อมูลตามตัวกรอง','No records match your filters')))),
   h('section',{className:'kc-report-panel'},h('div',{className:'kc-report-panel-title'},h('h2',null,t('รายการประกอบรายงาน','Supporting records')),h('span',null,format(filtered.length)+' '+t('รายการ','records'))),h('div',{className:'kc-report-scroll'},h('table',{className:'kc-report-table kc-report-records'},h('colgroup',null,...['18%','46%','18%','18%'].map((width,i)=>h('col',{key:i,style:{width}}))),h('thead',null,h('tr',null,...[t('รหัส / รายการ','Code / Record'),t('ลูกค้า / บริษัท / ชื่อ','Customer / Company / Name'),t('สถานะ','Status'),t('การจัดการ','Actions')].map(label=>h('th',{key:label,scope:'col'},label)))),h('tbody',null,filtered.slice(start,start+pageSize).map(r=>h('tr',{key:r.id},h('td',{className:'kc-report-code'},r.code||r[ENTITIES[entity].name]||'—'),h('td',null,r.customer_name||r.name||r.subject||r.company_name||r[ENTITIES[entity].name]||'—'),h('td',null,h('span',{className:'kc-report-badge '+(['lost','cancelled','rejected'].includes(r.status)?'is-negative':['won','completed','active'].includes(r.status)?'is-positive':'')},display(r.status))),h('td',null,h('button',{onClick:()=>navigate(entity,{leads:'lead-inbox',customers:'customer-list',contacts:'contact-list',opportunities:'opp-kanban',quotations:'quot-list',contracts:'con-all',assets:'asset-all',tickets:'tk-all',activities:'act-my',documents:'doc-all'}[entity],{recordId:r.id})},t('รายละเอียด','Details'))))),!filtered.length&&h('tr',null,h('td',{colSpan:4,className:'kc-report-empty'},t('ไม่พบข้อมูลตามตัวกรอง','No records match your filters')))))),
    h('footer',{className:'kc-report-pagination'},h('span',null,t('แสดง ','Showing ')+(filtered.length?start+1:0)+'–'+Math.min(start+pageSize,filtered.length)+t(' จาก ',' of ')+format(filtered.length)),h('nav',{'aria-label':t('หน้ารายงาน','Report pages')},h('button',{disabled:currentPage===0,onClick:()=>Page(currentPage-1)},t('ก่อนหน้า','Previous')),h('span',null,(currentPage+1)+' / '+totalPages),h('button',{disabled:currentPage+1>=totalPages,onClick:()=>Page(currentPage+1)},t('ถัดไป','Next'))))),
   ),
   h('p',{className:'kc-report-note'},t('คำนวณจากข้อมูลที่คุณมีสิทธิ์เห็น • มูลค่าโอกาสขายไม่ใช่รายได้ทางบัญชี','Computed from records you can access • Opportunity values are not recognized accounting revenue')));

 };
 return function Reports({lang}){const [tab,T]=React.useState('records');const tabs=h('nav',{className:'kc-report-tabs','aria-label':lang==='th'?'ประเภทรายงาน':'Report type'},h('button',{'aria-pressed':tab==='records',onClick:()=>T('records')},lang==='th'?'รายงานข้อมูล':'Record reports'),h('button',{'aria-pressed':tab==='targets',onClick:()=>T('targets')},lang==='th'?'รายงานเป้ายอดขาย':'Sales target report'));return tab==='targets'?h('div',{className:'kc-reports'},tabs,h(TargetSummary,{lang})):h(Records,{lang,tabs});};
}
