import {createAccountInventory} from './account360-inventory.mjs?v=20261002';
import {createMasterData} from './master-data.mjs?v=20261001-master-popup';
import {masterDemo,ensureMasterSamples,SAMPLE_PRODUCTS} from './master-data-model.mjs?v=20261001-master-popup';
import {ITEM_DEFAULTS,validateInventoryItem,validateMovement,stockSummary,postDemoMovement} from './inventory-model.mjs?v=20261001-inventory';
export function setInventoryMasterRows(rows){masterDemo.rows=rows;}
let sharedRecords={prices:[],products:[],service_parts:[]};
export function bindInventoryRecords(records){sharedRecords=records;}
export const inventoryDemo={items:[],warehouses:[],balances:[],movements:[],levels:[],settings:{enabled:false,allow_negative:false,default_warehouse_id:''}};
function createLocalInventory({React,client,useApp}){
 const MasterData=createMasterData({React,client,useApp}),h=React.createElement,unwrap=async q=>{const {data,error}=await q;if(error)throw error;return data;};
 async function all(table){let rows=[];for(let n=0;n<20000;n+=500){const batch=await unwrap(client.from(table).select('*').order('id').range(n,n+499));rows.push(...batch);if(batch.length<500)return rows;}throw Error('เกิน 20,000 รายการ กรุณาจำกัดข้อมูลก่อนโหลด');}
 return function Inventory({lang='th',onClose}){
  const {demoMode,profile}=useApp(),t=(th,en)=>lang==='th'?th:en,admin=demoMode||profile?.role==='admin';
  const [state,S]=React.useState({...inventoryDemo}),[tab,T]=React.useState('items'),[query,Q]=React.useState(''),[warehouse,W]=React.useState(''),[lowOnly,L]=React.useState(false),[edit,E]=React.useState(null),[busy,B]=React.useState(false),[error,Err]=React.useState(''),[message,M]=React.useState(''),[loaded,Loaded]=React.useState(false),[masters,Masters]=React.useState([]),[products,Products]=React.useState([]),[parts,Parts]=React.useState([]);
  const lock=React.useRef(false),dialog=React.useRef(null);
  const run=async fn=>{if(lock.current)return;lock.current=true;B(true);Err('');M('');try{await fn();}catch(e){Err(e.message);}finally{lock.current=false;B(false);}};
  async function load(){if(demoMode){ensureMasterSamples();if(!inventoryDemo.samplesInitialized){inventoryDemo.samplesInitialized=true;for(const sample of SAMPLE_PRODUCTS)if(!sharedRecords.prices.some(p=>p.code===sample.code)){const p={...ITEM_DEFAULTS,...sample,id:crypto.randomUUID()};sharedRecords.prices.push(p);inventoryDemo.items.push(p);}}inventoryDemo.items=(sharedRecords.prices||[]).map(p=>({...ITEM_DEFAULTS,...inventoryDemo.items.find(x=>x.id===p.id),...p}));S(structuredClone(inventoryDemo));Products(sharedRecords.products||[]);Parts(sharedRecords.service_parts||[]);Masters(masterDemo.rows);}else{const [prices,details,warehouses,balances,movements,levels,settings,refs,prods,serviceParts]=await Promise.all([unwrap(client.rpc('crm_price_catalog')),all('crm_item_details'),all('crm_warehouses'),all('crm_stock_balances'),all('crm_stock_movements'),all('crm_stock_levels'),unwrap(client.from('crm_inventory_settings').select('*').single()),all('master_data_items'),all('products'),admin?all('crm_service_parts'):Promise.resolve([])]);S({items:prices.map(p=>({...ITEM_DEFAULTS,...p,...details.find(x=>x.id===p.id)})),warehouses,balances,movements:movements.sort((a,b)=>b.created_at.localeCompare(a.created_at)),levels,settings});Masters(refs);Products(prods);Parts(serviceParts);}Loaded(true);}
  React.useEffect(()=>{run(load);},[demoMode]);
  React.useEffect(()=>{if(!edit)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';if(dialog.current&&!dialog.current.open)dialog.current.showModal();return()=>{document.body.style.overflow=previous;};},[!!edit]);
  const button=(label,fn,disabled=false,extra={})=>h('button',{type:'button',onClick:fn,disabled:disabled||busy,...extra},label);
  const open=(kind,row={})=>{Err('');M('');E({kind,data:kind==='item'?{...ITEM_DEFAULTS,...row}:kind==='warehouse'?{code:'',name:'',address:'',active:true,...row}:kind==='movement'?{id:crypto.randomUUID(),kind:'receipt',item_id:'',warehouse_id:state.settings.default_warehouse_id||'',to_warehouse_id:'',quantity:1,serial_number:'',reason:'',service_part_id:'',...row}:kind==='level'?{warehouse_id:state.settings.default_warehouse_id||'',item_id:'',reorder_point:0,...row}:{...state.settings}});};
  const set=(key,value)=>E(e=>{const data={...e.data,[key]:value};if(e.kind==='item'&&key==='category'){const category=masters.find(r=>r.category==='product_category'&&r.name_th===value);for(const key of ['income','expense','inventory','asset','deferred']){const account=masters.find(r=>r.id===category?.[key+'_account_id']);if(account)data[key+'_account']=account.name_th;}}return {...e,data};});
  const options=cat=>masters.filter(x=>x.category===cat&&(x.status==='active'||x.name_th===edit?.data[cat])).map(x=>[x.name_th,lang==='th'?x.name_th:x.name_en]);
  function field(key,th,en,type='text',opts,required=false){const label=t(th,en),value=edit.data[key]??'';const props={'aria-label':label,value,required,disabled:busy,onChange:e=>set(key,type==='checkbox'?e.target.checked:e.target.value)};let control=opts?h('select',props,h('option',{value:''},t('เลือก / ไม่ระบุ','Select / None')),...opts.map(([v,l])=>h('option',{key:v,value:v},l)),value&&!opts.some(([v])=>v===value)&&h('option',{value},value)):type==='textarea'?h('textarea',{...props,rows:3}):h('input',{...props,type,checked:type==='checkbox'?!!value:undefined,value:type==='checkbox'?undefined:value,step:type==='number'?'any':undefined,onFocus:type==='number'?e=>e.target.select():undefined});return h('label',{className:'crm-field'+(type==='textarea'?' crm-inventory-wide':''),key},h('span',null,label+(required?' *':'')),control);}
  const whOptions=state.warehouses.filter(w=>w.active).map(w=>[w.id,w.code+' · '+w.name]),itemOptions=state.items.filter(p=>p.stock_mode==='stock'&&p.status==='active').map(p=>[p.id,p.code+' · '+p.name]),kindNames={opening:t('ยอดยกมา','Opening'),receipt:t('รับเข้า','Receipt'),issue:t('จ่ายออก','Issue'),transfer:t('โอนคลัง','Transfer'),adjustment:t('ปรับปรุง','Adjustment')};
  async function save(e){e.preventDefault();await run(async()=>{const kind=edit.kind;let p={...edit.data};if(!admin)throw Error('Administrator required');if(kind==='item'){p=validateInventoryItem(p);if(demoMode){p.id=p.id||crypto.randomUUID();p.code=p.code||'ITEM-'+p.id.slice(0,8).toUpperCase();if(inventoryDemo.items.some(x=>x.code===p.code&&x.id!==p.id))throw Error('Duplicate item code');const old=inventoryDemo.items.find(x=>x.id===p.id);if(old&&inventoryDemo.movements.some(x=>x.item_id===p.id)&&['unit','stock_mode','track_serial'].some(k=>old[k]!==p[k]))throw Error('Stock mode, unit and serial are locked after movements');p.updated_at=new Date().toISOString();inventoryDemo.items=inventoryDemo.items.filter(x=>x.id!==p.id).concat(p);sharedRecords.prices=sharedRecords.prices.filter(x=>x.id!==p.id).concat(p);}else await unwrap(client.rpc('crm_inventory_save_item',{p}));}
   else if(kind==='movement'){p=validateMovement(p);if(demoMode){const part=parts.find(x=>x.id===p.service_part_id),item=state.items.find(x=>x.id===p.item_id);if(p.service_part_id&&(!part||p.kind!=='issue'||Number(part.quantity)!==p.quantity||![item.code,item.part_number].includes(part.part_no)||String(part.serial_number||'')!==p.serial_number||(part.product_id&&part.product_id!==item.product_id)))throw Error('Service part item, quantity and serial must match');postDemoMovement(inventoryDemo,p);if(part){part.inventory_reference=p.id;part.stock_location=state.warehouses.find(x=>x.id===p.warehouse_id)?.code;}}else await unwrap(client.rpc('crm_inventory_post',{p}));}
   else if(kind==='settings'){p={id:true,enabled:!!p.enabled,allow_negative:!!p.allow_negative,default_warehouse_id:p.default_warehouse_id||null,updated_at:new Date().toISOString()};if(demoMode)inventoryDemo.settings=p;else await unwrap(client.from('crm_inventory_settings').update(p).eq('id',true).select().single());}
   else if(kind==='warehouse'){p.code=String(p.code).trim().toUpperCase();p.name=String(p.name).trim();if(!p.name||!/^[A-Z0-9][A-Z0-9_-]{0,39}$/.test(p.code))throw Error('Invalid warehouse name or code');if(demoMode){if(inventoryDemo.warehouses.some(x=>x.code===p.code&&x.id!==p.id))throw Error('Duplicate warehouse code');p.id=p.id||crypto.randomUUID();inventoryDemo.warehouses=inventoryDemo.warehouses.filter(x=>x.id!==p.id).concat(p);}else{const {id,...values}=p;await unwrap((id?client.from('crm_warehouses').update(values).eq('id',id):client.from('crm_warehouses').insert(values)).select().single());}}
   else if(kind==='level'){p.reorder_point=Number(p.reorder_point);if(!p.warehouse_id||!p.item_id||!Number.isFinite(p.reorder_point)||p.reorder_point<0||p.reorder_point>=1e9)throw Error('Invalid reorder point');if(demoMode){p.id=p.id||crypto.randomUUID();inventoryDemo.levels=inventoryDemo.levels.filter(x=>!(x.item_id===p.item_id&&x.warehouse_id===p.warehouse_id)).concat(p);}else await unwrap(client.from('crm_stock_levels').upsert(p,{onConflict:'warehouse_id,item_id'}).select().single());}
   E(null);await load();M(t(demoMode?'บันทึกเฉพาะโหมดทดลอง':'บันทึกเรียบร้อย',demoMode?'Saved in demo memory only':'Saved successfully'));});}
  const summary=stockSummary(state.items,state.warehouses,state.balances,state.levels),filter=rows=>rows.filter(x=>(!warehouse||x.warehouse_id===warehouse||x.to_warehouse_id===warehouse)&&JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),name=id=>state.items.find(x=>x.id===id)?.name||id,wh=id=>state.warehouses.find(x=>x.id===id)?.code||'—';
  function table(headers,rows){return h('div',{className:'crm-inventory-scroll'},h('table',{className:'crm-master-table'},h('thead',null,h('tr',null,headers.map((x,i)=>h('th',{key:i},x)))),h('tbody',null,rows.map((cells,i)=>h('tr',{key:i},cells.map((c,j)=>h('td',{key:j},c)))),!rows.length&&h('tr',null,h('td',{colSpan:headers.length},t('ยังไม่มีรายการ','No records yet'))))));}
  function exportRows(){const rows=tab==='history'?filter(state.movements).map(({request,...x})=>({...x,item:name(x.item_id),warehouse:wh(x.warehouse_id),destination:wh(x.to_warehouse_id)})):filter(summary).filter(x=>!lowOnly||x.low);const keys=Object.keys(rows[0]||{}),cell=x=>'"'+String(x??'').replace(/^[=+@\-]/,"'" ).replaceAll('"','""')+'"',csv='\uFEFF'+[keys,...rows.map(x=>keys.map(k=>x[k]))].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='inventory-'+tab+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return h('section',{className:'crm-settings crm-inventory'},h('div',{className:'crm-actions'},onClose&&button(t('กลับ','Back'),onClose),h('h1',null,t('สินค้าและคลัง','Products & Inventory'))),h('p',null,t('สินค้าใช้ร่วมกับรายการราคาและใบเสนอราคา • ประวัติสต็อกบันทึกผู้ทำรายการและเวลา','Shared quotation price book • Stock history records operator and time')),demoMode&&h('p',{className:'crm-notice'},t('โหมดทดลอง: ไม่กระทบข้อมูลและสต็อกจริง','Demo: production stock is unchanged')),
   h('div',{className:'crm-inventory-metrics'},[[t('สินค้า/บริการ','Items'),state.items.length],[t('คลังสินค้า','Warehouses'),state.warehouses.filter(x=>x.active).length],[t('ถึงจุดแจ้งเตือน','Low-stock alerts'),summary.filter(x=>x.low).length],[t('การควบคุมสต็อก','Stock control'),state.settings.enabled?t('เปิด','On'):t('ปิด','Off')]].map(([label,value])=>h('article',{key:label},h('span',null,label),h('strong',null,value)))),
   h('div',{className:'crm-tabs'},[['items','สินค้าและบริการ','Products & Services'],['product_kind','ชนิดสินค้าและบริการ','Product kinds'],['product_category','หมวดสินค้าและบริการ','Product categories'],['unit','หน่วยสินค้า','Units'],['asset_brand','แบรนด์','Brands'],['warehouses','คลังสินค้า','Warehouses'],['balances','ยอดคงเหลือและจุดแจ้งเตือน','Balances & Alerts'],['history','ประวัติรับ–จ่าย','Movement History'],['settings','ตั้งค่าคลัง','Inventory Settings']].map(([id,th,en])=>button(t(th,en),()=>{T(id);Q('');W('');},false,{'aria-pressed':tab===id,key:id}))),
   error&&!edit&&h('p',{role:'alert',className:'crm-error'},error),message&&h('p',{role:'status',className:'crm-notice'},message),!loaded&&h('p',{role:'status'},t('กำลังโหลด…','Loading…')),
   !['product_kind','product_category','unit','asset_brand'].includes(tab)&&h('div',{className:'crm-actions'},h('input',{type:'search','aria-label':t('ค้นหาสินค้าและคลัง','Search inventory'),placeholder:t('ค้นหาชื่อ รหัส หรือ Serial Number','Search name, code or serial'),value:query,onChange:e=>Q(e.target.value)}),button(t('โหลดใหม่','Reload'),()=>run(load)),['balances','history'].includes(tab)&&h('select',{'aria-label':t('กรองคลัง','Filter warehouse'),value:warehouse,onChange:e=>W(e.target.value)},h('option',{value:''},t('ทุกคลัง','All warehouses')),state.warehouses.map(w=>h('option',{key:w.id,value:w.id},w.name))),admin&&button(t('รับ–จ่าย / โอนสินค้า','Post stock movement'),()=>open('movement'),!loaded),admin&&['balances','history'].includes(tab)&&button(t('ส่งออก CSV','Export CSV'),exportRows)),
   ['product_kind','product_category','unit','asset_brand'].includes(tab)&&h(MasterData,{key:tab,lang,fixedCategory:tab,compact:true,onChanged:()=>run(load)}),
   tab==='items'&&h(React.Fragment,null,admin&&button(t('เพิ่มสินค้าและบริการ','Add product or service'),()=>open('item'),!loaded,{className:'crm-save'}),table([t('รหัส','Code'),t('ชื่อ','Name'),t('ประเภทสต็อก','Stock mode'),t('หน่วย','Unit'),t(admin?'ราคาขาย / ราคาซื้อ':'ราคาขาย',admin?'Selling / Purchase price':'Selling price'),t('สถานะ','Status'),''],filter(state.items).map(p=>[p.code,h('div',null,p.name,p.description&&h('small',{className:'crm-master-description'},p.description)),p.stock_mode,h('div',null,p.unit,h('small',{className:'crm-master-description'},p.category)),admin?p.price.toLocaleString()+' / '+Number(p.cost||0).toLocaleString():p.price,p.status,admin&&button(t('แก้ไข ','Edit ')+p.code,()=>open('item',p))]))),
   tab==='warehouses'&&h(React.Fragment,null,admin&&button(t('เพิ่มคลังสินค้า','Add warehouse'),()=>open('warehouse'),false,{className:'crm-save'}),table([t('รหัส','Code'),t('ชื่อคลัง','Name'),t('ที่อยู่','Address'),t('ใช้งาน','Active'),''],filter(state.warehouses).map(w=>[w.code,w.name,w.address,w.active?'✓':'—',admin&&button(t('แก้ไข ','Edit ')+w.code,()=>open('warehouse',w))]))),
   tab==='balances'&&h(React.Fragment,null,admin&&button(t('กำหนดจุดแจ้งเตือน','Set reorder point'),()=>open('level')),h('label',null,h('input',{type:'checkbox',checked:lowOnly,onChange:e=>L(e.target.checked)}),t(' แสดงเฉพาะถึงจุดแจ้งเตือน',' Only low stock')),table([t('คลัง','Warehouse'),t('สินค้า','Item'),t('คงเหลือ','On hand'),t('หน่วย','Unit'),t('จุดแจ้งเตือน','Reorder point'),t('สถานะ','Status')],filter(summary).filter(x=>!lowOnly||x.low).map(x=>[x.warehouse,x.code+' · '+x.name,x.quantity,x.unit,x.reorder_point,x.low?t('ควรเติมสินค้า','Reorder'):'—'])),h('details',null,h('summary',null,'Serial Number'),table([t('คลัง','Warehouse'),t('สินค้า','Item'),'Serial Number',t('คงเหลือ','On hand')],filter(state.balances).filter(x=>x.serial_number&&x.quantity!==0).map(x=>[wh(x.warehouse_id),name(x.item_id),x.serial_number,x.quantity])))),
   tab==='history'&&table([t('วันที่','Date'),t('ประเภท','Type'),t('สินค้า','Item'),t('ต้นทาง','Source'),t('ปลายทาง','Destination'),t('จำนวน','Quantity'),'Serial Number',t('อ้างอิง/เหตุผล','Reference / Reason'),t('ผู้ทำรายการ','Operator')],filter(state.movements.map(x=>({...x,item:name(x.item_id)}))).map(x=>[new Date(x.created_at).toLocaleString(lang==='th'?'th-TH':'en-GB'),kindNames[x.kind],x.item,wh(x.warehouse_id),wh(x.to_warehouse_id),x.quantity,x.serial_number,x.reason+(x.service_part_id?' · Service part '+x.service_part_id:''),x.created_by||t('ผู้ใช้ทดลอง','Demo user')])),
   tab==='settings'&&h('section',{className:'crm-master-form'},h('h2',null,t('การควบคุมสต็อก','Stock control')),h('p',null,t('เปิดใช้งานก่อนบันทึกยอดยกมาและรับ–จ่าย สินค้าบริการไม่ตัดสต็อก','Enable before posting opening balances or movements. Service items do not affect stock.')),h('p',null,t('อนุญาตสต็อกติดลบ: ','Allow negative stock: ')+(state.settings.allow_negative?t('ใช่ (ยกเว้นสินค้ามี Serial)','Yes (except serialized items)'):t('ไม่','No'))),h('p',null,t('คลังเริ่มต้น: ','Default warehouse: ')+wh(state.settings.default_warehouse_id)),admin&&button(t('แก้ไขการตั้งค่าคลัง','Edit inventory settings'),()=>open('settings')),h('p',null,t('บัญชีรายได้/ค่าใช้จ่ายเป็นข้อมูลอ้างอิง ยังไม่ลงบัญชีแยกประเภทอัตโนมัติ','Account mappings are references; no automatic general-ledger postings.'))),
   edit&&h('dialog',{ref:dialog,className:'crm-inventory-dialog','data-kind':edit.kind,'aria-label':t('จัดการสินค้าและคลัง','Inventory form'),onCancel:e=>{if(busy)e.preventDefault();else E(null);}},h('form',{onSubmit:save},h('header',null,h('h2',null,({item:t('สินค้าและบริการ','Product / Service'),warehouse:t('คลังสินค้า','Warehouse'),movement:t('บันทึกการเคลื่อนไหว','Post stock movement'),settings:t('ตั้งค่าคลัง','Inventory settings'),level:t('จุดแจ้งเตือนสินค้า','Reorder point')})[edit.kind]),button('×',()=>E(null),false,{'aria-label':t('ปิด','Close')})),error&&h('p',{role:'alert',className:'crm-error'},error),h('div',{className:'crm-inventory-grid'},
   edit.kind==='item'&&h(React.Fragment,null,field('code','รหัส (ว่างเพื่อสร้างอัตโนมัติ)','Code (blank for automatic)'),field('name','ชื่อ','Name','text',null,true),field('stock_mode','การควบคุมสต็อก','Stock mode','select',[['stock',t('สินค้าในสต็อก','Stock item')],['nonstock',t('ไม่ควบคุมสต็อก','Non-stock')],['service',t('บริการ','Service')]],true),field('product_type','ประเภทสินค้าและบริการ','Product type','select',options('product_type')),field('product_kind','ชนิดสินค้าและบริการ','Product kind','select',options('product_kind')),field('unit','หน่วยสินค้าหลัก','Unit','select',options('unit'),true),field('category','หมวดสินค้า','Category','select',options('product_category')),field('brand','แบรนด์','Brand','select',options('asset_brand')),field('part_number','รหัสชิ้นส่วน','Part number'),field('barcode','บาร์โค้ด','Barcode'),field('price','ราคาขาย','Selling price','number',null,true),field('cost','ราคาซื้อ','Purchase price','number',null,true),field('vat_mode','รูปแบบ VAT เริ่มต้น','Default VAT mode','select',[['exclusive',t('ราคายังไม่รวม VAT','VAT exclusive')],['inclusive',t('ราคารวม VAT','VAT inclusive')],['exempt',t('ยกเว้น VAT','VAT exempt')]],true),field('subscription','รอบ Subscription','Subscription cycle'),field('contract_start','เริ่มสัญญา','Contract start','date'),field('contract_end','สิ้นสุดสัญญา','Contract end','date'),field('track_serial','ติดตาม Serial Number','Track serial number','checkbox'),field('status','สถานะ','Status','select',[['active',t('ใช้งาน','Active')],['inactive',t('ปิดใช้งาน','Inactive')]],true),field('product_id','เชื่อมสินค้าที่ใช้ในงานบริการ','Linked service catalog product','select',products.map(p=>[p.id,p.name])),h('h3',{className:'crm-inventory-wide'},t('กำหนดการลงบัญชี','Account mappings')),...['income','expense','inventory','asset','deferred'].map((k,i)=>field(k+'_account',['บัญชีรายได้','บัญชีค่าใช้จ่าย','บัญชีสินค้าคงเหลือ','บัญชีสินทรัพย์','รายได้รับล่วงหน้า'][i],['Income account','Expense account','Inventory account','Asset account','Deferred revenue account'][i],'select',options('accounting_account'))),field('description','รายละเอียด','Description','textarea'),h('p',{className:'crm-inventory-wide'},t('จัดการหน่วย หมวด แบรนด์ และบัญชีที่หน้า Master Data • การแก้ไขไม่เปลี่ยนเอกสารเดิม','Maintain units, categories, brands and accounts in Master Data. Existing documents keep their snapshots.'))),
   edit.kind==='warehouse'&&h(React.Fragment,null,field('code','รหัสคลัง','Warehouse code','text',null,true),field('name','ชื่อคลัง','Warehouse name','text',null,true),field('address','ที่อยู่/ตำแหน่ง','Address / Location','textarea'),field('active','ใช้งานคลัง','Active warehouse','checkbox')),
   edit.kind==='settings'&&h(React.Fragment,null,field('enabled','เปิดการควบคุมสต็อก','Enable stock control','checkbox'),field('allow_negative','อนุญาตสต็อกติดลบ','Allow negative stock','checkbox'),field('default_warehouse_id','คลังเริ่มต้น','Default warehouse','select',whOptions)),
   edit.kind==='level'&&h(React.Fragment,null,field('warehouse_id','คลังสินค้า','Warehouse','select',whOptions,true),field('item_id','สินค้า','Item','select',itemOptions,true),field('reorder_point','จำนวนแจ้งเตือน','Reorder quantity','number',null,true)),
   edit.kind==='movement'&&h(React.Fragment,null,field('kind','ประเภทรายการ','Movement type','select',Object.entries(kindNames),true),field('item_id','สินค้า','Item','select',itemOptions,true),field('warehouse_id','คลังต้นทาง','Source warehouse','select',whOptions,true),edit.data.kind==='transfer'&&field('to_warehouse_id','คลังปลายทาง','Destination warehouse','select',whOptions,true),field('quantity','จำนวน (ปรับปรุงใช้ค่าบวก/ลบ)','Quantity (signed for adjustment)','number',null,true),field('serial_number','Serial Number','Serial Number'),edit.data.kind==='issue'&&field('service_part_id','เชื่อมอะไหล่งานบริการ','Service part reference','select',parts.filter(x=>!x.inventory_reference).map(x=>[x.id,x.part_no+' · '+x.name+' × '+x.quantity])),field('reason','เหตุผล / เลขเอกสารอ้างอิง','Reason / Document reference','textarea',null,true),h('p',{className:'crm-inventory-wide'},t('บันทึกแล้วไม่สามารถลบประวัติได้ หากผิดให้สร้างรายการปรับปรุงพร้อมเหตุผล','Posted history cannot be deleted. Correct mistakes with a new adjustment and reason.')))),h('footer',null,button(t('ยกเลิก','Cancel'),()=>E(null)),h('button',{type:'submit',className:'crm-save',disabled:busy},t(busy?'กำลังบันทึก…':'บันทึก',busy?'Saving…':'Save')))))
  );
 };
}

export function createInventory(deps){const Local=createLocalInventory(deps),Account=createAccountInventory(deps);return function Inventory(props){const {demoMode}=deps.useApp();return deps.React.createElement(demoMode?Local:Account,props);};}
