import {EMAIL_LAYOUTS,EMAIL_STATUSES,audience,uniqueRecipients,starterEmail,validateCampaign,bangkokToUTC,escapeHTML} from './marketing-model.mjs';
const DEMO={campaigns:[],templates:[],groups:[],members:[],sender:{enabled:false,from_name:'',from_email:'',reply_to:'',postal_address:''}};
export function createMarketingEmails({React,client,useApp,records}){
 const h=React.createElement;
 async function all(table){const rows=[];for(let n=0;n<20000;n+=500){const r=await client.from(table).select('*').order('id').range(n,n+499);if(r.error)throw r.error;rows.push(...r.data);if(r.data.length<500)return rows;}throw Error('Too many records; narrow your scope');}
 const unwrap=async q=>{const r=await q;if(r.error)throw r.error;return r.data;};
 return function MarketingEmails({lang,route}){
  const {demoMode,profile,navigate}=useApp(),t=(th,en)=>lang==='th'?th:en;
  const [data,Data]=React.useState({...DEMO,customers:[],contacts:[]}),[permissions,Permissions]=React.useState({}),[busy,Busy]=React.useState(false),[error,Err]=React.useState(''),[notice,Notice]=React.useState(''),[search,Search]=React.useState(''),[status,Status]=React.useState(''),[refresh,Refresh]=React.useState(0);
  const [compose,Compose]=React.useState(null),[step,Step]=React.useState(0),[tab,Tab]=React.useState('layouts'),[choice,Choice]=React.useState('sales'),[schedule,Schedule]=React.useState(''),[timing,Timing]=React.useState('now'),[groupEdit,GroupEdit]=React.useState(null),[groupSearch,GroupSearch]=React.useState(''),[tier,Tier]=React.useState(''),[sender,Sender]=React.useState(null),[details,Details]=React.useState(null);
  const lock=React.useRef(false),dialog=React.useRef(null),view=route==='act-email-groups'?'groups':route==='act-email-templates'?'templates':'campaigns',mine=route==='act-email-my';
  const can=a=>demoMode||profile?.role==='admin'||!!permissions['can_'+a];
  async function api(body){const r=await client.functions.invoke('marketing-email',{body});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg;}catch{}throw Error(msg);}if(r.data?.error)throw Error(r.data.error);return r.data;}
  async function load(){
   if(demoMode){Data({...DEMO,customers:records.customers,contacts:records.contacts});return;}
   const [campaigns,templates,groups,members,customers,contacts,config]=await Promise.all([all('crm_email_campaigns'),all('crm_email_templates'),all('crm_email_groups'),all('crm_email_group_members'),all('customers'),all('contacts'),api({action:'status'})]);
   Data({campaigns,templates,groups,members,customers,contacts,sender:config});
   if(profile?.role!=='admin')Permissions(await unwrap(client.from('role_permissions').select('*').eq('role_key',profile?.role==='custom'?profile.custom_role_key:profile?.role||'').eq('module','activities').maybeSingle())||{});
  }
  React.useEffect(()=>{let active=true;Busy(true);Err('');load().catch(e=>{if(active)Err(e.message);}).finally(()=>{if(active)Busy(false);});return()=>{active=false;};},[demoMode,profile?.id,refresh]);
  const modalOpen=!!(compose||groupEdit||sender||details);
  React.useEffect(()=>{if(modalOpen&&dialog.current&&!dialog.current.open)dialog.current.showModal();return()=>{if(dialog.current?.open)dialog.current.close();};},[modalOpen]);
  const close=()=>{Compose(null);GroupEdit(null);Sender(null);Details(null);Err('');};
  async function run(fn){if(lock.current)return;lock.current=true;Busy(true);Err('');Notice('');try{await fn();}catch(e){Err(e.message);}finally{lock.current=false;Busy(false);}}
  const btn=(label,fn,props={})=>h('button',{type:'button',disabled:busy,onClick:fn,...props},label);
  const field=(label,value,fn,type='text',props={})=>h('label',{className:'crm-field'},h('span',null,label),h(type==='textarea'?'textarea':'input',{'aria-label':label,type:type==='textarea'?undefined:type,value:value??'',onChange:e=>fn(e.target.value),...props}));
  const check=(label,checked,fn)=>h('label',{className:'email-check'},h('input',{type:'checkbox',checked,onChange:e=>fn(e.target.checked)}),label);
  const people=audience(data.customers,data.contacts),selectedRecipients=uniqueRecipients(data.members.filter(m=>compose?.group_ids.includes(m.group_id))),patch=v=>Compose(c=>({...c,...v}));
  const formatDate=v=>v?new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(v)):'—';
  const preview=value=>h('iframe',{title:t('ตัวอย่างอีเมล','Email preview'),sandbox:'',referrerPolicy:'no-referrer',srcDoc:'<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src https:;">'+(value?.html||'<pre style="white-space:pre-wrap;font:16px Arial;padding:24px">'+escapeHTML(value?.text||'')+'</pre>'),className:'email-preview'});
  function start(value=null){Err('');Notice('');Compose(value?{...value,group_ids:[...value.group_ids]}:starterEmail('sales',lang));Step(value?1:0);Choice('sales');Tab('layouts');Schedule('');Timing('now');}
  function choose(){const item=tab==='layouts'?starterEmail(choice,lang):(tab==='templates'?data.templates:data.campaigns.filter(c=>c.status==='draft')).find(x=>x.id===choice);if(!item)throw Error('Choose an email layout');Compose({...starterEmail(item.layout,lang),title:item.title,subject:item.subject,preview_text:item.preview_text,html:item.html,text:item.text,group_ids:[]});Step(1);}
  async function saveDraft(){const v=validateCampaign(compose),payload={title:v.title,subject:v.subject,preview_text:v.preview_text,html:v.html,text:v.text,layout:v.layout,group_ids:v.group_ids,updated_at:new Date().toISOString()};let saved;
   if(demoMode){saved={...payload,id:v.id||crypto.randomUUID(),owner_id:profile?.id||'demo',status:'draft',recipient_count:0,sent_count:0,failed_count:0,created_at:v.created_at||new Date().toISOString()};const i=DEMO.campaigns.findIndex(c=>c.id===saved.id);if(i<0)DEMO.campaigns.unshift(saved);else DEMO.campaigns[i]=saved;}
   else saved=await unwrap(v.id?client.from('crm_email_campaigns').update(payload).eq('id',v.id).select().single():client.from('crm_email_campaigns').insert(payload).select().single());
   Compose(saved);await load();Notice(t('บันทึกฉบับร่างแล้ว','Draft saved'));return saved;
  }
  async function queue(){validateCampaign(compose);if(!compose.group_ids.length)throw Error('เลือกกลุ่มผู้รับ / Choose recipient groups');const when=timing==='schedule'?bangkokToUTC(schedule):null;
   if(!demoMode&&!data.sender.enabled)throw Error('ตั้งค่าบัญชีผู้ส่งก่อน / Configure a verified sender first');
   const saved=await saveDraft();if(demoMode){if(!selectedRecipients.length)throw Error('ไม่มีผู้รับที่มีอีเมล / No valid recipients');Object.assign(DEMO.campaigns.find(c=>c.id===saved.id),{status:when?'scheduled':'queued',scheduled_at:when||new Date().toISOString(),recipient_count:selectedRecipients.length});}
   else await api({action:'queue',id:saved.id,scheduled_at:when});close();await load();Notice(demoMode?t('โหมดทดลอง: บันทึกคิวจำลอง ไม่มีการส่งจริง','Demo queue saved. No email was sent.'):t(when?'ตั้งเวลาส่งแล้ว':'เพิ่มอีเมลเข้าคิวส่งแล้ว',when?'Email scheduled':'Email queued'));
  }
  async function saveTemplate(){const v=validateCampaign(compose),payload={title:v.title,subject:v.subject,preview_text:v.preview_text,html:v.html,text:v.text,layout:v.layout};if(demoMode)DEMO.templates.unshift({...payload,id:crypto.randomUUID(),owner_id:profile?.id||'demo'});else await unwrap(client.from('crm_email_templates').insert(payload));await load();Notice(t('บันทึกแม่แบบแล้ว','Template saved'));}
  async function saveGroup(){if(!groupEdit.name.trim())throw Error('ระบุชื่อกลุ่ม / Group name is required');const members=uniqueRecipients(people.filter(p=>groupEdit.selected.includes(p.id)));
   if(demoMode){const id=groupEdit.id||crypto.randomUUID(),v={id,name:groupEdit.name,description:groupEdit.description,owner_id:profile?.id||'demo'};const i=DEMO.groups.findIndex(g=>g.id===id);if(i<0)DEMO.groups.push(v);else DEMO.groups[i]=v;DEMO.members=DEMO.members.filter(m=>m.group_id!==id).concat(members.map(m=>({...m,id:crypto.randomUUID(),group_id:id})));}
   else await unwrap(client.rpc('crm_email_save_group',{p_id:groupEdit.id||null,p_name:groupEdit.name,p_description:groupEdit.description,p_members:members.map(({email,name,source_type,source_id})=>({email,name,source_type,source_id}))}));
   close();await load();Notice(t('บันทึกกลุ่มผู้รับแล้ว','Recipient group saved'));
  }
  function editGroup(g){Err('');GroupSearch('');Tier('');GroupEdit({id:g?.id,name:g?.name||'',description:g?.description||'',selected:g?data.members.filter(m=>m.group_id===g.id).map(m=>m.source_type+':'+m.source_id):[]});}
  const groupPeople=people.filter(p=>(!tier||p.tier===tier)&&(!groupSearch||[p.name,p.customer_name,p.email,p.industry].join(' ').toLowerCase().includes(groupSearch.toLowerCase())));
  const statusName=s=>EMAIL_STATUSES[s]?.[lang==='th'?0:1]||s;
  const rows=(view==='campaigns'?data.campaigns:view==='groups'?data.groups:data.templates).filter(r=>(!mine||r.owner_id===(profile?.id||'demo'))&&(!status||r.status===status)&&(!search||[r.title,r.name,r.subject].join(' ').toLowerCase().includes(search.toLowerCase())));
  const title=view==='groups'?t('กลุ่มผู้รับอีเมล','Recipient groups'):view==='templates'?t('แม่แบบอีเมล','Email templates'):t(mine?'อีเมลของฉัน':'อีเมลทั้งหมด',mine?'My emails':'All emails');
  return h('section',{className:'crm-internal crm-settings email-workspace'},h('header',{className:'email-heading'},h('div',null,h('p',null,'✉ '+t('กิจกรรม / อีเมลการตลาด','Activities / Marketing email')),h('h1',null,title)),h('div',{className:'crm-actions'},can('create')&&btn(t('สร้างอีเมล','Send Email'),()=>start(),{className:'crm-save'}),profile?.role==='admin'||demoMode?btn(t('ตั้งค่าผู้ส่ง','Sender settings'),()=>Sender({...data.sender,api_key:''})):null)),
   h('nav',{className:'email-tabs','aria-label':t('เมนูอีเมล','Email navigation')},[['act-my','กิจกรรม','Activities'],['act-email-all','อีเมลทั้งหมด','All emails'],['act-email-my','อีเมลของฉัน','My emails'],['act-email-templates','แม่แบบอีเมล','Email templates'],['act-email-groups','กลุ่มผู้รับ','Recipient groups']].map(([id,th,en])=>btn(t(th,en),()=>{Search('');Status('');navigate('activities',id);},{key:id,'aria-current':route===id?'page':undefined}))),
   error&&!modalOpen&&h('p',{role:'alert',className:'crm-error'},error),notice&&h('p',{role:'status',className:'email-notice'},notice),
   h('div',{className:'email-toolbar'},field(t('ค้นหาอีเมลหรือกลุ่ม','Search emails or groups'),search,Search,'search'),view==='campaigns'&&h('label',{className:'crm-field'},t('สถานะ','Status'),h('select',{'aria-label':t('สถานะ','Status'),value:status,onChange:e=>Status(e.target.value)},h('option',{value:''},t('ทั้งหมด','All')),...Object.keys(EMAIL_STATUSES).map(s=>h('option',{key:s,value:s},statusName(s))))),view==='groups'&&can('create')&&btn(t('สร้างกลุ่ม','New group'),()=>editGroup()),btn(t('โหลดใหม่','Refresh'),()=>Refresh(n=>n+1))),
   h('p',{className:'email-count',role:'status'},busy?t('กำลังโหลด…','Loading…'):rows.length+' '+t('รายการ','records')),
   view==='templates'?h('div',{className:'email-layout-grid'},rows.map(r=>h('article',{key:r.id,className:'email-template-card'},h('h2',null,r.title),h('p',null,r.subject),btn(t('ใช้แม่แบบ','Use template'),()=>start({...starterEmail(r.layout,lang),...r,id:undefined,group_ids:[]})),can('delete')&&btn(t('ลบแม่แบบ','Delete template'),()=>run(async()=>{if(demoMode)DEMO.templates=DEMO.templates.filter(x=>x.id!==r.id);else await unwrap(client.from('crm_email_templates').delete().eq('id',r.id));await load();}))))):
   h('div',{className:'crm-table-scroll'},h('table',{className:'crm-master-table email-list'},h('thead',null,h('tr',null,...(view==='groups'?[t('ชื่อกลุ่ม','Group name'),t('สมาชิก','Members'),t('รายละเอียด','Description'),t('จัดการ','Actions')]:[t('ชื่ออีเมล / หัวข้อ','Email / subject'),t('สถานะ','Status'),t('ผู้รับ','Recipients'),t('เวลาไทย','Bangkok time'),t('ผลการส่ง','Sending result'),t('จัดการ','Actions')]).map(label=>h('th',{key:label},label)))),h('tbody',null,rows.map(r=>view==='groups'?h('tr',{key:r.id},h('td',null,r.name),h('td',null,data.members.filter(m=>m.group_id===r.id).length),h('td',null,r.description),h('td',null,can('edit')&&btn(t('แก้ไขกลุ่ม','Edit group'),()=>editGroup(r)))):h('tr',{key:r.id},h('td',null,h('strong',null,r.title),h('small',null,r.subject)),h('td',null,h('span',{className:'email-status','data-status':r.status},statusName(r.status))),h('td',null,r.recipient_count||0),h('td',null,formatDate(r.scheduled_at||r.created_at)),h('td',null,(r.sent_count||0)+' / '+(r.recipient_count||0),r.failed_count>0&&h('small',null,t('ไม่สำเร็จ ','Failed: ')+r.failed_count)),h('td',null,btn(t('รายละเอียด','Details'),()=>run(async()=>{let recipients=[];if(!demoMode)recipients=await unwrap(client.from('crm_email_recipients').select('id,email,name,status,error,provider_id,sent_at').eq('campaign_id',r.id).limit(100));Details({...r,recipients});})),r.status==='draft'&&r.owner_id===(profile?.id||'demo')&&can('edit')&&btn(t('แก้ไข','Edit'),()=>start(r)),['queued','scheduled','sending'].includes(r.status)&&can('edit')&&btn(t('ยกเลิกการส่ง','Cancel sending'),()=>run(async()=>{if(demoMode)r.status='cancelled';else await api({action:'cancel',id:r.id});await load();Notice(t('ยกเลิกคิวที่ยังไม่ส่งแล้ว รายการที่ส่งไปแล้วเรียกคืนไม่ได้','Unsent queue cancelled. Already submitted email cannot be recalled.'));}))))))),
   !rows.length&&!busy&&h('div',{className:'email-empty'},h('span',null,'✉'),h('h2',null,t('ยังไม่มีรายการ','No records yet')),h('p',null,t('เริ่มจากสร้างกลุ่มผู้รับ แล้วเลือกแม่แบบเพื่อสร้างอีเมล','Create a recipient group, then choose a layout for your email'))),
   modalOpen&&h('dialog',{ref:dialog,className:'crm-profile-dialog email-dialog',onCancel:e=>{e.preventDefault();if(!busy)close();},'aria-label':compose?t('สร้างอีเมลการตลาด','Create marketing email'):groupEdit?t('จัดการกลุ่มผู้รับ','Manage recipient group'):sender?t('ตั้งค่าผู้ส่ง','Sender settings'):t('รายละเอียดอีเมล','Email details')},
    h('header',{className:'email-dialog-head'},h('h2',null,compose?t('สร้างอีเมลการตลาด','Create marketing email'):groupEdit?t('จัดการกลุ่มผู้รับ','Manage recipient group'):sender?t('ตั้งค่าผู้ส่ง','Sender settings'):details.title),btn('×',close,{'aria-label':t('ปิด','Close')})),
    h('div',{className:'email-dialog-body'},notice&&h('p',{role:'status',className:'email-notice'},notice),error&&h('p',{role:'alert',className:'crm-error'},error),
     compose&&h(React.Fragment,null,h('ol',{className:'email-steps'},[t('เลือกเค้าโครง','Choose layout'),t('เนื้อหา','Content'),t('ผู้รับและเวลา','Audience & timing'),t('ตรวจทาน','Review')].map((label,i)=>h('li',{key:label,'aria-current':step===i?'step':undefined},(i+1)+' · '+label))),
      step===0?h(React.Fragment,null,h('div',{className:'email-tabs'},[['layouts','ตัวเลือกเค้าโครง','Layout options'],['templates','แม่แบบอีเมล','Email templates'],['drafts','อีเมลที่บันทึก','Saved emails']].map(([id,th,en])=>btn(t(th,en),()=>{Tab(id);Choice(id==='layouts'?'sales':'');},{key:id,'aria-pressed':tab===id}))),h('div',{className:'email-chooser'},h('div',{className:'email-layout-grid'},(tab==='layouts'?EMAIL_LAYOUTS.map(l=>({id:l[0],title:l[lang==='th'?1:2],layout:l[0]})):tab==='templates'?data.templates:data.campaigns.filter(c=>c.status==='draft')).map(l=>h('button',{key:l.id,type:'button',className:'email-layout-card','aria-pressed':choice===l.id,onClick:()=>Choice(l.id)},h('div',{className:'email-layout-thumb','data-layout':l.layout},h('i'),h('b'),h('span'),h('span'),h('em')),h('strong',null,l.title)))),preview(tab==='layouts'?starterEmail(choice,lang):(tab==='templates'?data.templates:data.campaigns).find(c=>c.id===choice)))):
      step===1?h('div',{className:'email-editor-grid'},h('div',null,field(t('ชื่ออีเมล','Email name'),compose.title,v=>patch({title:v}),'text',{maxLength:160}),field(t('หัวข้ออีเมล','Email subject'),compose.subject,v=>patch({subject:v}),'text',{maxLength:200}),field(t('ข้อความตัวอย่าง','Preview text'),compose.preview_text,v=>patch({preview_text:v})),compose.layout!=='plain'&&field(t('เนื้อหา HTML','HTML content'),compose.html,v=>patch({html:v}),'textarea',{rows:12}),field(t('เนื้อหาข้อความธรรมดา','Plain text content'),compose.text,v=>patch({text:v}),'textarea',{rows:7}),h('p',{className:'email-hint'},t('ใช้ {{name}} แทนชื่อผู้รับ ลิงก์ยกเลิกรับอีเมลจะเพิ่มให้อัตโนมัติ','Use {{name}} for recipient name. An unsubscribe link is added automatically.')),btn(t('บันทึกเป็นแม่แบบ','Save as template'),()=>run(saveTemplate))),preview(compose)):
      step===2?h(React.Fragment,null,h('h3',null,t('เลือกกลุ่มผู้รับ','Choose recipient groups')),data.groups.map(g=>check(g.name+' ('+data.members.filter(m=>m.group_id===g.id).length+')',compose.group_ids.includes(g.id),yes=>patch({group_ids:yes?[...compose.group_ids,g.id]:compose.group_ids.filter(x=>x!==g.id)}))),!data.groups.length&&h('p',null,t('ยังไม่มีกลุ่มผู้รับ บันทึกฉบับร่างแล้วสร้างกลุ่มที่เมนูกลุ่มผู้รับ','No groups yet. Save a draft and create a recipient group.')),h('p',null,t('อีเมลไม่ซ้ำในกลุ่มที่เลือก: ','Unique selected email addresses: ')+selectedRecipients.length),h('div',{className:'email-recipient-preview'},selectedRecipients.slice(0,30).map(p=>h('span',{key:p.email},p.name+' <'+p.email+'>'))),h('h3',null,t('กำหนดเวลาส่ง','Sending time')),h('label',{className:'email-check'},h('input',{type:'radio',name:'timing',checked:timing==='now',onChange:()=>Timing('now')}),t('ส่งเข้าคิวทันที','Queue now')),h('label',{className:'email-check'},h('input',{type:'radio',name:'timing',checked:timing==='schedule',onChange:()=>Timing('schedule')}),t('ตั้งเวลาล่วงหน้า','Schedule ahead')),timing==='schedule'&&field(t('วันเวลาส่ง (เวลาไทย UTC+7)','Send at (Bangkok UTC+7)'),schedule,Schedule,'datetime-local'),h('p',{className:'email-hint'},t('จำนวนผู้รับจริงจะตัดรายชื่อที่ยกเลิกรับข่าวสารและอีเมลที่เปลี่ยนไปก่อนเข้าคิว','Unsubscribed and changed email addresses are excluded when queued.'))):
      h(React.Fragment,null,h('div',{className:'email-review'},h('h3',null,compose.subject),h('p',null,t('กลุ่มผู้รับ: ','Recipient groups: ')+data.groups.filter(g=>compose.group_ids.includes(g.id)).map(g=>g.name).join(', ')),h('p',null,t('ผู้รับไม่ซ้ำ: ','Unique recipients: ')+selectedRecipients.length),h('p',null,t('เวลาส่ง: ','Sending time: ')+(timing==='schedule'?schedule.replace('T',' ')+' (UTC+7)':t('เข้าคิวทันที','Queue now'))),h('p',null,t('ผู้ส่ง: ','Sender: ')+(data.sender.from_email||t('ยังไม่ได้ตั้งค่า','Not configured'))),!demoMode&&!data.sender.enabled&&h('p',{className:'crm-error'},t('ผู้ดูแลระบบต้องตั้งค่าผู้ส่งก่อนส่งจริง','An administrator must configure the sender before sending'))),preview(compose))),
     groupEdit&&h(React.Fragment,null,field(t('ชื่อกลุ่ม','Group name'),groupEdit.name,v=>GroupEdit(g=>({...g,name:v})),'text',{maxLength:160}),field(t('รายละเอียดกลุ่ม','Group description'),groupEdit.description,v=>GroupEdit(g=>({...g,description:v})),'textarea'),h('div',{className:'email-toolbar'},field(t('ค้นหารายชื่อลูกค้า','Search customer names'),groupSearch,GroupSearch,'search'),h('label',{className:'crm-field'},t('ระดับลูกค้า','Customer tier'),h('select',{'aria-label':t('ระดับลูกค้า','Customer tier'),value:tier,onChange:e=>Tier(e.target.value)},h('option',{value:''},t('ทุกระดับ','All tiers')),...[...new Set(people.map(p=>p.tier).filter(Boolean))].map(v=>h('option',{key:v,value:v},v))))),btn(t('เลือกทั้งหมดที่กรอง','Select all filtered'),()=>GroupEdit(g=>({...g,selected:[...new Set([...g.selected,...groupPeople.map(p=>p.id)])]}))),btn(t('ล้างการเลือก','Clear selection'),()=>GroupEdit(g=>({...g,selected:[]}))),h('p',null,t('เลือก ','Selected: ')+groupEdit.selected.length),h('div',{className:'email-people'},groupPeople.map(p=>h('div',{key:p.id},check(p.name+' · '+p.customer_name+' · '+p.email,groupEdit.selected.includes(p.id),yes=>GroupEdit(g=>({...g,selected:yes?[...g.selected,p.id]:g.selected.filter(x=>x!==p.id)}))))))),
     sender&&h(React.Fragment,null,h('p',null,t('เชื่อมต่อ Resend ด้วยโดเมนผู้ส่งที่ยืนยันแล้ว คีย์จะเก็บบนเซิร์ฟเวอร์','Connect Resend with a verified sending domain. The key is stored on the server.')),field(t('ชื่อผู้ส่ง','Sender name'),sender.from_name,v=>Sender(s=>({...s,from_name:v}))),field(t('อีเมลผู้ส่ง','Sender email'),sender.from_email,v=>Sender(s=>({...s,from_email:v})),'email'),field('Reply-to',sender.reply_to,v=>Sender(s=>({...s,reply_to:v})),'email'),field(t('ที่อยู่บริษัทท้ายอีเมล','Company postal address'),sender.postal_address,v=>Sender(s=>({...s,postal_address:v})),'textarea'),field(t('Resend API key (เว้นว่างเพื่อใช้คีย์เดิม)','Resend API key (blank keeps current)'),sender.api_key,v=>Sender(s=>({...s,api_key:v})),'password',{autoComplete:'new-password'}),h('p',{className:'email-hint'},t('คีย์ต้องเข้าถึง Domains ได้ การบันทึกจะตรวจยืนยันโดเมนโดยไม่ส่งอีเมล','The key needs Domains access. Saving checks the domain without sending an email.'))),
     details&&h(React.Fragment,null,h('p',null,statusName(details.status)+' · '+formatDate(details.scheduled_at||details.created_at)),preview(details),h('h3',null,t('ผลการส่ง (100 รายชื่อแรก)','Sending results (first 100 recipients)')),details.recipients.map(r=>h('p',{key:r.id},r.email+' · '+r.status+(r.error?' · '+r.error:''))))),
    h('footer',{className:'email-dialog-footer'},btn(t('ยกเลิก','Cancel'),close),compose&&h(React.Fragment,null,step>0&&btn(t('ย้อนกลับ','Back'),()=>Step(s=>s-1)),step>0&&btn(t('บันทึกฉบับร่าง','Save draft'),()=>run(async()=>{await saveDraft();close();})),step<3?btn(t('ถัดไป','Next'),()=>run(async()=>{if(step===0)choose();else{validateCampaign(compose);if(step===2&&(!compose.group_ids.length||!selectedRecipients.length))throw Error('เลือกกลุ่มผู้รับที่มีอีเมล / Choose a group with valid emails');if(step===2&&timing==='schedule')bangkokToUTC(schedule);Step(s=>s+1);}}),{className:'crm-save'}):btn(t(timing==='schedule'?'ยืนยันตั้งเวลาส่ง':'ยืนยันส่งอีเมล',timing==='schedule'?'Confirm schedule':'Confirm sending'),()=>run(queue),{className:'crm-save',disabled:busy||(!demoMode&&!data.sender.enabled)})),groupEdit&&btn(t('บันทึกกลุ่ม','Save group'),()=>run(saveGroup),{className:'crm-save'}),sender&&btn(t('บันทึกและตรวจสอบ','Save and verify'),()=>run(async()=>{if(demoMode){DEMO.sender={...sender,api_key:undefined,enabled:false};Notice(t('บันทึกค่าทดลอง ไม่มีการเชื่อมต่อหรือส่งจริง','Demo settings saved; no connection or email sent'));}else await api({action:'configure',...sender});close();await load();}),{className:'crm-save'})))));
 };
}
