import {createSellerRanking} from './seller-ranking.mjs?v=20261004';
import {THAI_PROVINCES} from './thailand-map-data.mjs';
import {salesOrderRows,filterSales,summarizeGeography} from './sales-map-model.mjs?v=20261001-so';
import {toCSV} from './settings-model.mjs';
export function createSalesMap({React,client,useApp,records}){
 const h=React.createElement,SellerRanking=createSellerRanking(React);
 async function read(table,columns){const rows=[];for(let n=0;n<20000;n+=500){const r=await client.from(table).select(columns).order('id').range(n,n+499);if(r.error)throw r.error;rows.push(...r.data);if(r.data.length<500)return rows;}throw Error('More than 20,000 records; narrow your reporting scope');}
 return function SalesMap({lang}){
  const {demoMode,profile,navigate}=useApp(),t=(th,en)=>lang==='th'?th:en;
  const [rows,Rows]=React.useState([]),[busy,Busy]=React.useState(false),[error,Err]=React.useState(''),[product,Product]=React.useState(''),[seller,Seller]=React.useState(''),[from,From]=React.useState(''),[to,To]=React.useState(''),[min,Min]=React.useState(''),[max,Max]=React.useState(''),[selected,Selected]=React.useState(''),[zoom,Zoom]=React.useState(1),[pan,Pan]=React.useState({x:0,y:0}),[refresh,Refresh]=React.useState(0),[asOf,AsOf]=React.useState(''),[canExport,CanExport]=React.useState(false),[diagnostics,Diagnostics]=React.useState({}),[sourceSync,SourceSync]=React.useState('');
  React.useEffect(()=>{const id=setInterval(()=>Refresh(v=>v+1),30000);return()=>clearInterval(id);},[]);
  React.useEffect(()=>Rows([]),[demoMode,profile?.id,profile?.role,profile?.custom_role_key]);
  const drag=React.useRef(null),svg=React.useRef(null);
  React.useEffect(()=>{let active=true;Busy(true);Err('');(async()=>{try{let o,c;if(demoMode){o=records.sales_orders||[];c=records.customers;}else{[o,c]=await Promise.all([read('kc_dw_sales_order_facts','id,source_system,source_so_id,so_number,customer_id,customer_name,net_amount,product_lines,sales_email,sales_name,status,converted_at,synced_at,source_updated_at,currency'),read('customers','id,name,address,province,billing_country,billing_city,billing_postal_code')]);}let exportAllowed=demoMode||profile?.role==='admin';if(!exportAllowed){const p=await client.from('role_permissions').select('can_export').eq('role_key',profile?.role==='custom'?profile.custom_role_key:profile?.role||'').eq('module','quotations').maybeSingle();if(p.error)throw p.error;exportAllowed=!!p.data?.can_export;}if(active){const data=salesOrderRows(o,c);Rows(data.rows);Diagnostics(data);SourceSync(o.map(v=>v.synced_at||'').sort().at(-1)||'');CanExport(exportAllowed);AsOf(new Date().toISOString());}}catch(e){if(active)Err(e.message);}finally{if(active)Busy(false);}})();return()=>{active=false;};},[demoMode,profile?.id,profile?.role,profile?.custom_role_key,refresh]);
  const invalidFilters=(from&&to&&from>to)||(min!==''&&max!==''&&Number(min)>Number(max)),filtered=invalidFilters?[]:filterSales(rows,{product,seller,from,to,minimum:min,maximum:max}),summary=summarizeGeography(filtered),byProvince=new Map(summary.provinces.map(p=>[p.id,p])),high=Math.max(...summary.provinces.map(p=>p.amount),1),selectedRows=filtered.filter(r=>selected==='unmapped'?!r.province_id:!selected||r.province_id===selected),current=THAI_PROVINCES.find(p=>p.id===selected);
  const cash=n=>new Intl.NumberFormat(lang==='th'?'th-TH':'en-US',{maximumFractionDigits:2}).format(n)+' '+t('บาท','THB');
  const btn=(label,fn,props={})=>h('button',{type:'button',onClick:fn,...props},label);
  const field=(label,value,set,type='date')=>h('label',{className:'sales-map-filter'},h('span',null,label),h('input',{type,'aria-label':label,value,min:type==='number'?0:undefined,step:type==='number'?'any':undefined,onChange:e=>{set(e.target.value);Selected('');}}));
  const select=(label,value,set,options)=>h('label',{className:'sales-map-filter'},h('span',null,label),h('select',{'aria-label':label,value,onChange:e=>{set(e.target.value);Selected('');}},h('option',{value:''},t('ทั้งหมด','All')),...options.map(([id,label])=>h('option',{key:id,value:id},label))));
  const color=v=>v===0?'#e4eaf0':v/high>.66?'#086f79':v/high>.33?'#18a5ac':'#93d6d6';
  function reset(){Product('');Seller('');From('');To('');Min('');Max('');Selected('');Zoom(1);Pan({x:0,y:0});}
  function exportCSV(){const csv=toCSV(selectedRows,['code','source_system','source_so_id','customer_name','province_th','product_name','product_code','seller_name','order_date','amount']);const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='sales-order-map.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return h(React.Fragment,null,h(SellerRanking,{rows,lang,busy,error,asOf,onRefresh:()=>Refresh(v=>v+1)}),h('section',{className:'sales-map-panel','aria-label':t('แผนที่ยอดขาย','Sales map')},
   h('header',{className:'sales-map-heading'},h('div',null,h('p',{className:'sales-map-eyebrow'},'SALES GEOGRAPHY'),h('h2',null,t('ยอดเปิด Sales Order ตามที่อยู่ลูกค้า','Sales Orders by customer location')),h('p',null,t('ยอดสุทธิ SO ไม่รวม VAT · ระดับจังหวัด · THB','Converted SO net value excluding VAT · Province level · THB'))),h('div',{className:'sales-map-actions'},btn(t('โหลดใหม่','Refresh map'),()=>Refresh(v=>v+1),{disabled:busy}),canExport&&btn(t('ส่งออกยอดที่กรอง CSV','Export filtered sales CSV'),exportCSV,{disabled:busy||!!error}))),
   h('div',{className:'sales-map-controls'},select(t('สินค้า (By Product)','By Product'),product,Product,[...new Map(rows.map(r=>[r.product,r.product==='__unspecified'?t('ไม่ระบุสินค้า','Unspecified product'):r.product_name+(r.product_code?' ('+r.product_code+')':'')])).entries()].sort((a,b)=>a[1].localeCompare(b[1]))),select(t('พนักงานขาย (By Sales)','By Sales'),seller,Seller,[...new Map(rows.map(r=>[r.seller_id,r.seller_name||t('ไม่ระบุพนักงานขาย','Unassigned seller')])).entries()]),field(t('วันเปิด SO ตั้งแต่','SO date from'),from,From),field(t('ถึงวันที่','SO date to'),to,To),field(t('ยอด SO ขั้นต่ำ','Minimum SO value'),min,Min,'number'),field(t('ยอด SO สูงสุด','Maximum SO value'),max,Max,'number'),btn(t('ล้างตัวกรอง','Reset map filters'),reset)),
   error&&h('p',{role:'alert',className:'crm-error'},error),invalidFilters&&h('p',{role:'alert',className:'crm-error'},t('ช่วงวันที่หรือช่วงยอดขายไม่ถูกต้อง','Invalid date or SO value range')),
   !busy&&!error&&!rows.length&&h('p',{role:'status',className:'sales-map-note'},t('ยังไม่มี SO ที่เปิดสำเร็จสกุลเงินบาทในข้อมูลที่เชื่อมเข้ามา','No converted THB Sales Orders are available in the connected feed')),
   (diagnostics.excluded_currency_count>0||diagnostics.invalid_order_count>0)&&h('p',{role:'status',className:'sales-map-note'},t('ไม่นำมารวม: SO สกุลอื่น ','Excluded: other-currency SO ')+(diagnostics.excluded_currency_count||0)+t(' / ข้อมูลยอดหรือสินค้าต้องตรวจสอบ ',' / SO with invalid amounts or product data ')+(diagnostics.invalid_order_count||0)),
   diagnostics.unallocated_order_count>0&&h('p',{className:'sales-map-note'},diagnostics.unallocated_order_count+' SO '+t('ยังมีมูลค่าที่ไม่ระบุสินค้า','have value without product details')),
   h('div',{className:'sales-map-kpis'},h('article',null,h('span',null,t('ยอดรวมตามตัวกรอง','Filtered sales')),h('strong',{'data-map-total':true},cash(summary.total)),h('small',null,summary.orders+' SO')),h('article',null,h('span',null,t('ยอดที่แสดงบนแผนที่','Mapped sales')),h('strong',{'data-map-mapped':true},cash(summary.mapped)),h('small',null,summary.provinces.length+' '+t('จังหวัด','provinces'))),h('article',null,h('span',null,t('ยังระบุจังหวัดไม่ได้','Unresolved locations')),h('strong',{'data-map-unmapped':true},cash(summary.unmapped)),btn(summary.unmapped_count+' '+t('รายการ · ตรวจที่อยู่','records · Review addresses'),()=>Selected('unmapped')))),
   h('div',{className:'sales-map-grid'},h('div',{className:'sales-map-canvas'},h('div',{className:'sales-map-zoom'},btn('+',()=>Zoom(z=>Math.min(4,z+.5)),{'aria-label':t('ขยายแผนที่','Zoom in')}),btn('−',()=>Zoom(z=>Math.max(1,z-.5)),{'aria-label':t('ย่อแผนที่','Zoom out')}),btn(t('พอดีจอ','Fit'),()=>{Zoom(1);Pan({x:0,y:0});})),
    h('svg',{ref:svg,viewBox:'0 0 520 810',className:'sales-map-svg','aria-label':t('แผนที่จังหวัดประเทศไทย','Thailand province map'),onPointerDown:e=>{if(zoom<=1)return;drag.current={x:e.clientX,y:e.clientY,pan};e.currentTarget.setPointerCapture(e.pointerId);},onPointerMove:e=>{if(!drag.current)return;const scale=810/e.currentTarget.getBoundingClientRect().height;Pan({x:drag.current.pan.x+(e.clientX-drag.current.x)*scale,y:drag.current.pan.y+(e.clientY-drag.current.y)*scale});},onPointerUp:e=>{drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);},onPointerCancel:()=>{drag.current=null;}},h('g',{transform:`translate(${260*(1-zoom)+pan.x} ${405*(1-zoom)+pan.y}) scale(${zoom})`},THAI_PROVINCES.map(p=>{const v=byProvince.get(p.id);return h('path',{key:p.id,d:p.path,fill:color(v?.amount||0),stroke:selected===p.id?'#183c67':'white',strokeWidth:selected===p.id?2.2:.65,fillRule:'evenodd',role:'button',tabIndex:0,'aria-label':(lang==='th'?p.th:p.en)+' · '+cash(v?.amount||0),'aria-pressed':selected===p.id,'data-province':p.id,onClick:()=>Selected(p.id),onKeyDown:e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();Selected(p.id);}}},h('title',null,(lang==='th'?p.th:p.en)+'\n'+cash(v?.amount||0)+' · '+(v?.orders||0)+' SO'));}))),
    h('div',{className:'sales-map-legend'},h('span',null,t('ไม่มีข้อมูล','No sales')),['#e4eaf0','#93d6d6','#18a5ac','#086f79'].map(c=>h('i',{key:c,style:{background:c}})),h('span',null,t('ยอดขายสูง','Higher sales'))),h('small',{className:'sales-map-attribution'},'Map: geoBoundaries / CC BY 4.0 · ',h('a',{href:'https://www.geoboundaries.org/',target:'_blank',rel:'noreferrer'},'Source'))),
    h('div',{className:'sales-map-ranking'},h('h3',null,t('ยอดขายรายจังหวัด','Sales by province')),summary.provinces.map(p=>btn(h(React.Fragment,null,h('span',null,lang==='th'?p.th:p.en),h('strong',null,cash(p.amount)),h('small',null,p.customer_count+' '+t('ลูกค้า','accounts')+' · '+p.orders+' SO')),()=>Selected(p.id),{key:p.id,'aria-pressed':selected===p.id,className:'sales-map-province-row'})),!busy&&!summary.provinces.length&&h('p',null,t('ยังไม่มียอด SO ที่ระบุจังหวัดได้ในตัวกรองนี้','No located Sales Orders for these filters')),selected&&btn(t('แสดงทุกจังหวัด','Show all provinces'),()=>Selected('')))),
   h('div',{className:'sales-map-detail'},h('h3',null,current?(lang==='th'?current.th:current.en):selected==='unmapped'?t('รายการที่ต้องตรวจที่อยู่ลูกค้า','Customer locations to review'):t('รายการขายตามตัวกรอง','Filtered sales records')),h('p',null,cash(selectedRows.reduce((n,r)=>n+r.amount,0))+' · '+new Set(selectedRows.map(r=>r.order_id)).size+' SO · '+selectedRows.length+' '+t('รายการสินค้า','product rows')),h('div',{className:'sales-map-table-scroll'},h('table',null,h('thead',null,h('tr',null,...['Sales Order',t('ลูกค้า / ที่อยู่','Customer / address'),t('สินค้า','Product'),t('พนักงานขาย','Salesperson'),t('วันเปิด SO','SO date'),t('ยอดขาย','Value'),t('รายละเอียด','Details')].map(label=>h('th',{key:label},label)))),h('tbody',null,selectedRows.slice(0,100).map(r=>h('tr',{key:r.id},h('td',null,r.code,h('small',null,r.source_system)),h('td',null,r.customer_name,h('small',null,r.address||t('ยังไม่มีที่อยู่','No address'))),h('td',null,r.product==='__unspecified'?'—':r.product_name+(r.product_code?' ('+r.product_code+')':'')),h('td',null,r.seller_name||'—'),h('td',null,r.order_date||'—'),h('td',null,cash(r.amount)),h('td',null,r.customer_id&&btn(t('ดูลูกค้า','Open customer'),()=>navigate('customers','customer-list',{recordId:r.customer_id}))))))))),
   h('p',{role:'status',className:'sales-map-note'},busy?t('กำลังโหลดข้อมูลยอดขาย…','Loading sales…'):t('โหลดข้อมูลเมื่อ ','Loaded ')+(asOf?new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(asOf)):'—')+(demoMode?t(' · โหมดทดลอง ใช้เฉพาะรายการที่สร้างในโหมดทดลอง',' · Demo mode: records created in demo only'):'')),
   sourceSync&&h('p',{className:'sales-map-note'},t('รับข้อมูล SO ล่าสุด: ','Latest SO sync: ')+new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(sourceSync))),
   h('details',{className:'sales-map-definitions'},h('summary',null,t('ที่มาและการคำนวณแผนที่','Map source and definitions')),h('p',null,t('ยอดขาย = ยอดสุทธิไม่รวม VAT ของ Sales Order ที่เปิดสำเร็จ ไม่รวม SO ที่ยกเลิกหรือเป็นโมฆะ วันเปิด SO ใช้เวลาไทย ตัวกรองสินค้าและพนักงานขายใช้ร่วมกัน ช่วงยอดขั้นต่ำ/สูงสุดอ้างอิงยอดทั้ง SO','Sales = converted Sales Order net amount excluding VAT. Cancelled and voided SO are excluded. SO dates use Bangkok time. Product and seller filters combine; minimum/maximum applies to the full SO net value.')),h('p',null,t('จับคู่จังหวัดจากช่องจังหวัดลูกค้า หรือชื่อจังหวัดที่ระบุในที่อยู่ ไม่เดาตำแหน่งจากรหัสไปรษณีย์ ที่อยู่ต่างประเทศและรายการที่จับคู่ไม่ได้อยู่ในยอดยังระบุจังหวัดไม่ได้','Provinces come from the customer province field or an explicit province name in the address. Postal codes are not used to guess locations. Foreign and unmatched locations appear in unresolved totals.')),h('p',null,t('กรองสินค้า = ยอดสุทธิของสินค้าที่เลือก ยอดที่ยังไม่มีรายละเอียดสินค้าอยู่ในไม่ระบุสินค้า ไม่ใช้ยอดใบเสนอราคาหรือโอกาสขายแทน SO','Product filter = selected product net amount. Amount without product details remains in Unspecified product. Quotation and opportunity values never substitute for SO.')),h('p',null,t('ยอดรวม = ยอดบนแผนที่ + ยอดยังระบุจังหวัดไม่ได้ อ่านเฉพาะรายการที่บัญชีของคุณมีสิทธิ์เห็น','Total = mapped + unresolved value. Only records your account can access are included.')))));
 };
}
export function createDashboardSalesMap(dependencies){
 const {React}=dependencies,h=React.createElement,SalesMap=createSalesMap(dependencies);
 return function DashboardSalesMap({lang,Component}){
  return h('div',{className:'kc-dashboard-layout'},h(Component,{lang}),h(SalesMap,{lang}));
 };
}
