import {createTargetVisuals} from './dashboard-studio.mjs?v=20261003-motion';
import {TARGET_EVENT,monthKey,monthsBetween,allocateMonths,validateTargets,targetDraft,targetMetrics,sameSavedTargets} from './sales-target-model.mjs?v=20261002-targets';
export function createSalesTargets({React,client,useApp}){
 const TargetVisuals=createTargetVisuals(React);
 const h=React.createElement,demoPlans=new Map(),yearNow=()=>new Date().getFullYear();
 const empty=people=>({plan:null,people,employees:[],months:[],scope:'company',can_manage:true,can_export:true,basis:'converted_so_net_thb'});
 async function read(year,demoMode,profile){if(demoMode)return structuredClone(demoPlans.get(year)||empty([{id:profile?.id||'demo',name:profile?.display_name||'Demo User',active:true}]));const {data,error}=await client.rpc('crm_get_sales_targets',{p_year:year});if(error)throw error;return data;}
 function changed(){window.dispatchEvent(new Event(TARGET_EVENT));}
 function demoSave(payload,people){const employees=payload.p_employees.map(e=>({...e,name:people.find(p=>p.id===e.profile_id)?.name}));const company=allocateMonths(payload.p_company,payload.p_start,payload.p_end);const data={...empty(people),employees,plan:{id:'demo-'+payload.p_year,plan_year:payload.p_year,start_month:payload.p_start,end_month:payload.p_end,company_target:payload.p_company,updated_at:new Date().toISOString()},months:company.map(m=>({month:m.month+'-01',company_target:m.amount,company_actual:0,employees:people.map(p=>{const e=employees.find(x=>x.profile_id===p.id);return {profile_id:p.id,target:e?(allocateMonths(e.amount,e.start_month,e.end_month).find(x=>x.month===m.month)?.amount||0):null,actual:0};})}))};demoPlans.set(payload.p_year,data);return data;}
 const field=(label,value,onChange,type='text',props={})=>h('label',{className:'crm-field'},h('span',null,label),h('input',{type,'aria-label':label,value:value??'',onChange:e=>onChange(e.target.value),onInput:type==='month'?e=>onChange(e.currentTarget.value):undefined,...props}));
 function Settings({lang}){
  const {demoMode,profile}=useApp(),t=(a,b)=>lang==='th'?a:b;
  const [year,Y]=React.useState(yearNow),[data,D]=React.useState(null),[draft,F]=React.useState(null),[baseline,B]=React.useState(''),[busy,U]=React.useState(false),[error,E]=React.useState(''),[message,M]=React.useState('');
  const canManage=demoMode||profile?.role==='admin',dirty=draft&&JSON.stringify(draft)!==baseline;
  async function load(nextYear=year){U(true);E('');M('');try{const result=await read(Number(nextYear),demoMode,profile),form=targetDraft(result,Number(nextYear));D(result);F(form);B(JSON.stringify(form));}catch(e){E(e.message);D(null);F(null);}finally{U(false);}}
  React.useEffect(()=>{load();},[demoMode,profile?.id]);
  const update=(key,value)=>F(old=>({...old,[key]:value,...(['start','end'].includes(key)?{employees:old.employees.map(r=>r[key]===old[key]?{...r,[key]:value}:r)}:{})})),employee=(id,key,value)=>F(old=>({...old,employees:old.employees.map(r=>r.profile_id===id?{...r,[key]:value}:r)}));
  async function save(event){event.preventDefault();if(!canManage||busy)return;U(true);E('');M('');try{const payload=validateTargets(draft);let result;if(demoMode)result=demoSave(payload,data.people);else{const saved=await client.rpc('crm_save_sales_targets',payload);if(saved.error)throw saved.error;result=await read(draft.year,false,profile);if(!sameSavedTargets(result,payload))throw Error(t('ยังยืนยันข้อมูลที่บันทึกไม่ได้ กรุณาโหลดใหม่','Unable to verify saved targets. Reload.'));}D(result);const form=targetDraft(result,draft.year);F(form);B(JSON.stringify(form));changed();M(t(demoMode?'บันทึกในโหมดทดลองแล้ว':'บันทึกและตรวจสอบแล้ว Dashboard และรายงานใช้เป้าชุดนี้',demoMode?'Saved in demo mode':'Saved and verified. Dashboards and reports use these targets.'));}catch(e){E(e.code==='40001'?t('ข้อมูลถูกแก้ไขแล้ว กรุณายกเลิกการแก้ไขและโหลดใหม่','Targets changed. Discard your changes and reload.'):e.code==='23P01'?t('ช่วงเดือนซ้อนกับแผนปีอื่น กรุณาปรับช่วงเดือน','Period overlaps another plan. Adjust the months.'):e.message);}finally{U(false);}}
  const cash=n=>new Intl.NumberFormat(lang==='th'?'th-TH':'en-US',{maximumFractionDigits:2}).format(n),total=draft?.employees.reduce((n,r)=>n+Number(r.amount||0),0)||0;
  let distribution=[];try{if(draft?.company!=='')distribution=allocateMonths(draft.company,draft.start,draft.end);}catch{}
  return h('section',{className:'crm-settings crm-targets'},h('h1',null,t('เป้ายอดขายบริษัทและพนักงาน','Company and employee sales targets')),h('p',null,t('กรอกยอดรวมสำหรับช่วงเดือนที่เลือก ระบบกระจายเท่ากันทุกรายเดือนและปรับเศษสตางค์ในเดือนสุดท้าย','Enter the total for the selected period. Targets are spread evenly by month; rounding is settled in the final month.')),demoMode&&h('p',{className:'crm-notice'},t('โหมดทดลอง ไม่บันทึกข้อมูลจริง','Demo mode — no production writes')),
   h('div',{className:'crm-target-year'},field(t('ปีเป้าหมาย (ค.ศ.)','Target year (CE)'),year,Y,'number',{min:2000,max:2200,disabled:busy||!!dirty}),h('button',{onClick:()=>load(year),disabled:busy||!!dirty},t('โหลดปีที่เลือก','Load selected year'))),
   error&&h('p',{role:'alert',className:'crm-error'},error),message&&h('p',{role:'status',className:'crm-notice'},message),busy&&h('p',{role:'status'},t('กำลังโหลดหรือบันทึก…','Loading or saving…')),
   draft&&h('form',{onSubmit:save},h('h2',null,t('เป้าบริษัท ปี ','Company target — ')+draft.year),h('div',{className:'crm-grid'},field(t('เดือนเริ่มเป้าบริษัท','Company start month'),draft.start,v=>update('start',v),'month',{disabled:!canManage||busy,required:true}),field(t('เดือนสิ้นสุดเป้าบริษัท','Company end month'),draft.end,v=>update('end',v),'month',{disabled:!canManage||busy,required:true}),field(t('เป้าบริษัทรวม (บาท)','Company target total (THB)'),draft.company,v=>update('company',v),'number',{min:0,max:1000000000000,step:'.01',disabled:!canManage||busy,required:true})),
    h('h2',null,t('เป้ารายพนักงาน','Employee targets')),h('p',null,t('เว้นยอดว่างสำหรับคนที่ยังไม่ตั้งเป้า เลือกช่วงเดือนภายในช่วงเป้าบริษัทได้ การกรอก 0 หมายถึงตั้งเป้าเป็นศูนย์','Leave amount blank for unassigned targets. Employee months must be within the company period. Zero is an explicit target.')),
    h('div',{className:'crm-table-scroll'},h('table',{className:'crm-master-table'},h('thead',null,h('tr',null,...[t('พนักงาน','Employee'),t('เป้ารวม (บาท)','Total target (THB)'),t('เดือนเริ่ม','Start month'),t('เดือนสิ้นสุด','End month')].map(x=>h('th',{key:x},x)))),h('tbody',null,draft.employees.map(row=>h('tr',{key:row.profile_id},h('td',null,row.name,!row.active&&h('small',null,t(' (ไม่ใช้งาน)',' (inactive)'))),h('td',null,field(t('เป้ารวม ','Total target ')+row.name,row.amount,v=>employee(row.profile_id,'amount',v),'number',{min:0,max:1000000000000,step:'.01',disabled:!canManage||busy,placeholder:t('ยังไม่ตั้งเป้า','Not set')})),h('td',null,field(t('เดือนเริ่ม ','Start month ')+row.name,row.start,v=>employee(row.profile_id,'start',v),'month',{disabled:!canManage||busy})),h('td',null,field(t('เดือนสิ้นสุด ','End month ')+row.name,row.end,v=>employee(row.profile_id,'end',v),'month',{disabled:!canManage||busy}))))))),
    h('div',{className:'crm-notice'},t('รวมเป้าพนักงาน: ','Employee total: ')+cash(total)+' '+t('บาท · ส่วนต่างจากเป้าบริษัท: ','THB · Company less employee total: ')+cash(Number(draft.company||0)-total)),
    distribution.length>0&&h('details',null,h('summary',null,t('ดูการกระจายเป้าบริษัทแต่ละเดือน','View monthly company allocation')),h('div',{className:'crm-target-months'},distribution.map(row=>h('div',{key:row.month},row.month,h('strong',null,cash(row.amount)))))),
    h('div',{className:'crm-actions'},h('button',{type:'submit',className:'crm-save',disabled:!canManage||busy||!dirty},t('บันทึกเป้ายอดขาย','Save sales targets')),h('button',{type:'button',disabled:busy||!dirty,onClick:()=>{F(JSON.parse(baseline));E('');M('');}},t('ยกเลิกการแก้ไข','Discard changes'))),!canManage&&h('p',null,t('ผู้ดูแลระบบเป็นผู้ตั้งเป้ายอดขาย','Administrators manage sales targets'))));
 }
 function Summary({lang,defaultScope='auto'}){
  const {demoMode,profile,navigate}=useApp(),t=(a,b)=>lang==='th'?a:b;
  const [year,Y]=React.useState(yearNow),[data,D]=React.useState(null),[from,F]=React.useState(''),[to,T]=React.useState(''),[scope,S]=React.useState(''),[busy,U]=React.useState(true),[error,E]=React.useState(''),[revision,R]=React.useState(0);
  React.useEffect(()=>{const refresh=()=>R(n=>n+1);window.addEventListener(TARGET_EVENT,refresh);window.addEventListener('focus',refresh);const timer=setInterval(refresh,30000);return()=>{window.removeEventListener(TARGET_EVENT,refresh);window.removeEventListener('focus',refresh);clearInterval(timer);};},[]);
  React.useEffect(()=>{let active=true;U(true);E('');(async()=>{try{const result=await read(Number(year),demoMode,profile);if(!active)return;D(result);const first=monthKey(result.plan?.start_month),last=monthKey(result.plan?.end_month);F(old=>old>=first&&old<=last?old:first);T(old=>old>=first&&old<=last?old:last);S(old=>(old==='company'&&result.scope==='company')||(old==='team'&&result.scope!=='self')||result.people.some(p=>p.id===old)?old:defaultScope==='self'?profile?.id:result.scope==='company'?'company':result.scope==='team'?'team':profile?.id);}catch(e){if(active){D(null);E(e.message);}}finally{if(active)U(false);}})();return()=>{active=false;};},[year,demoMode,profile?.id,revision]);
  const invalid=from&&to&&from>to,metrics=targetMetrics(data,{from,to,scope}),cash=n=>n===null?'—':new Intl.NumberFormat(lang==='th'?'th-TH':'en-US',{maximumFractionDigits:2}).format(n),hasPlan=!!data?.plan&&data.plan.plan_year===Number(year);
  const select=(label,value,set,options)=>h('label',{className:'crm-field'},h('span',null,label),h('select',{'aria-label':label,value,onChange:e=>set(e.target.value)},options.map(([id,name])=>h('option',{key:id,value:id},name))));
  function exportCSV(){if(!data?.can_export||invalid||!hasPlan)return;const csv='\uFEFFmonth,target_thb,actual_so_net_thb\r\n'+metrics.rows.map(r=>[r.month,r.target??'',r.actual].join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`sales-target-${year}-${scope}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return h('section',{className:'crm-settings crm-targets crm-target-summary','aria-label':t('ยอดขายเทียบเป้า','Sales versus target')},h('div',{className:'crm-target-heading'},h('div',null,h('h2',null,t('ยอดขายเทียบเป้าหมาย','Sales versus target')),h('p',null,t('ยอดจริงจาก Sales Order ที่เปิดสำเร็จ สุทธิไม่รวม VAT เฉพาะเงินบาท','Actuals: successfully converted Sales Orders, net of VAT, THB only'))),(demoMode||profile?.role==='admin')&&h('button',{onClick:()=>navigate('settings','set-sales-targets')},t('ตั้งเป้ายอดขาย','Set sales targets'))),
   h('div',{className:'crm-grid'},field(t('ปีเป้าหมาย (ค.ศ.)','Target year (CE)'),year,Y,'number',{min:2000,max:2200}),hasPlan&&select(t('ขอบเขตเป้า','Target scope'),scope,S,[...(data.scope==='company'?[['company',t('บริษัท','Company')]]:[]),...(data.scope!=='self'?[['team',t('รวมพนักงานที่มองเห็น','Visible employee total')]]:[]),...data.people.map(p=>[p.id,p.name])]),hasPlan&&field(t('ตั้งแต่เดือน','From month'),from,F,'month',{min:monthKey(data.plan.start_month),max:monthKey(data.plan.end_month)}),hasPlan&&field(t('ถึงเดือน','Through month'),to,T,'month',{min:monthKey(data.plan.start_month),max:monthKey(data.plan.end_month)})),
   error&&h('p',{role:'alert',className:'crm-error'},error),invalid&&h('p',{role:'alert'},t('เดือนสิ้นสุดต้องไม่ก่อนเดือนเริ่ม','End month must not precede start month')),busy&&h('p',{role:'status'},t('กำลังโหลดเป้า…','Loading targets…')),
   !busy&&!error&&!hasPlan&&h('p',{className:'crm-notice'},t('ยังไม่ได้ตั้งเป้าปีนี้ กรุณาให้ผู้ดูแลระบบตั้งเป้ายอดขาย','No target plan for this year. Ask your administrator to set sales targets.')),
   hasPlan&&!invalid&&h(React.Fragment,null,h('div',{className:'crm-target-kpis'},...[[t('เป้าช่วงที่เลือก','Selected period target'),cash(metrics.target)], [t('ยอด SO สุทธิ','Net SO sales'),cash(metrics.actual)], [t('ยอดที่ยังขาดจากเป้า','Remaining to target'),cash(metrics.remaining)], [t('ทำได้เทียบเป้า','Attainment'),metrics.attainment===null?'—':(metrics.attainment*100).toFixed(1)+'%']].map(([label,value])=>h('article',{key:label},h('span',null,label),h('strong',null,value)))),metrics.target===null&&h('p',{className:'crm-notice'},t('ยังไม่ได้ตั้งเป้าสำหรับพนักงานที่เลือก','No target is assigned to the selected employee')),
    h(TargetVisuals,{metrics,lang,onMonth:month=>{F(month);T(month);},onReset:()=>{F(monthKey(data.plan.start_month));T(monthKey(data.plan.end_month));}}),h('div',{className:'crm-table-scroll'},h('table',{className:'crm-master-table'},h('thead',null,h('tr',null,...[t('เดือน','Month'),t('เป้า (บาท)','Target (THB)'),t('ยอดจริง (บาท)','Actual (THB)'),t('ทำได้ (%)','Attainment (%)')].map(x=>h('th',{key:x},x)))),h('tbody',null,metrics.rows.map(r=>h('tr',{key:r.month},h('td',null,r.month),h('td',null,cash(r.target)),h('td',null,cash(r.actual)),h('td',null,r.target>0?(r.actual/r.target*100).toFixed(1)+'%':'—')))))),
    h('h3',null,t('ผลงานรายพนักงาน','Employee performance')),h('div',{className:'crm-table-scroll'},h('table',{className:'crm-master-table'},h('thead',null,h('tr',null,...[t('พนักงาน','Employee'),t('เป้าช่วงที่เลือก','Period target'),t('ยอด SO สุทธิ','Net SO sales'),t('ทำได้ (%)','Attainment (%)')].map(x=>h('th',{key:x},x)))),h('tbody',null,data.people.filter(p=>['company','team'].includes(scope)||p.id===scope).map(p=>{const v=targetMetrics(data,{from,to,scope:p.id});return h('tr',{key:p.id},h('td',null,h('button',{onClick:()=>S(p.id)},p.name)),h('td',null,cash(v.target)),h('td',null,cash(v.actual)),h('td',null,v.attainment===null?'—':(v.attainment*100).toFixed(1)+'%'));})))),h('div',{className:'crm-actions'},h('button',{onClick:()=>R(v=>v+1),disabled:busy},t('โหลดเป้าใหม่','Reload targets')),data.can_export&&h('button',{onClick:exportCSV,disabled:busy},t('ส่งออกเป้าและยอดจริง CSV','Export targets and actuals CSV')))),
   h('small',null,t('ใช้เป้าชุดเดียวกับการตั้งค่า · ข้อมูลแสดงตามสิทธิ์ของผู้ใช้งาน','Shared with target settings · Data is scoped to your access')));
 }
 return {Settings,Summary};
}
