export const STATUSES=['new','assigned','acknowledged','diagnosing','in-progress','waiting-customer','waiting-approval','waiting-parts','waiting-vendor','repairing','claim-processing','testing','resolved','customer-confirmed','closed'];
export const CLAIM_STATUSES=['preparing','submitted','vendor-received','inspection','waiting-parts','repair-replacement','shipped-back','received','qc','completed'];
export const TYPES=['Incident','Repair','Warranty Claim','Technical Support','Installation','Preventive Maintenance','On-site Service','Remote Support','Request Service','Other'];
export const CHANNELS=['Phone','Email','LINE','Web Portal','Walk-in','Sales','Internal'];
export const STATUS_LABELS={new:'ใหม่',assigned:'มอบหมายแล้ว',acknowledged:'รับงานแล้ว',diagnosing:'ตรวจสอบ','in-progress':'กำลังดำเนินการ','waiting-customer':'รอลูกค้า','waiting-approval':'รออนุมัติ','waiting-parts':'รออะไหล่','waiting-vendor':'รอผู้ขาย',repairing:'กำลังซ่อม','claim-processing':'กำลังเคลม',testing:'ทดสอบ',resolved:'แก้ไขแล้ว','customer-confirmed':'ลูกค้ายืนยัน',closed:'ปิดงาน'};
export const CATEGORIES={Hardware:{Notebook:['Power','Display','Storage','Performance'],Server:['Power','Storage','Performance'],Printer:['Print','Paper','Network']},Network:{Firewall:['Connectivity','Policy'],Switch:['Connectivity','Performance'],Wireless:['Connectivity','Coverage']},Software:{Application:['Error','Installation','License'],OS:['Boot','Performance','Update']},Other:{Other:['Other']}};
export const DEFAULT_SETTINGS={ticket_types:TYPES,channels:CHANNELS,statuses:STATUSES,claim_statuses:CLAIM_STATUSES,repair_statuses:['received','diagnosing','repairing','testing','completed'],priorities:['low','medium','high','critical'],impact:['low','medium','high'],urgency:['low','medium','high'],categories:CATEGORIES,prefixes:{ticket:'SR',repair:'REPAIR',claim:'CLAIM',rma:'RMA'},auto_assignment:{Endpoint:'Client Support',Notebook:'Client Support',Server:'Infrastructure',Storage:'Infrastructure',Network:'Network & Security',Firewall:'Network & Security',Software:'Application Support'},escalation:{thresholds:[50,75,90,100],waiting_hours:48},notifications:{enabled:true},email_templates:Object.fromEntries(['รับเรื่องแล้ว','มอบหมายวิศวกรแล้ว','อยู่ระหว่างตรวจสอบ','รอข้อมูลจากลูกค้า','รออะไหล่','ส่งเคลมผู้ขาย','ซ่อมเสร็จ','พร้อมส่งคืน','ปิดงานแล้ว'].map(x=>[x,`เรียน {{contact}}\n\nเคส {{code}}: {{subject}}\nสถานะ: ${x}\n\nทีมบริการ KC CuTo`]))};
export const normalizeStatus=s=>({open:'new',accepted:'acknowledged','pending-customer':'waiting-customer',escalated:'in-progress',pending:'waiting-customer'}[s]||s);
export const isClosed=t=>['closed','cancelled'].includes(normalizeStatus(t.status));
export const day=value=>value?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'';
export function priority(impact,urgency){const n={low:1,medium:2,high:3};return ['low','medium','medium','high','critical'][(n[impact]||2)+(n[urgency]||2)-2];}
export function warranty(asset,now=Date.now()){if(!asset?.warranty_end)return {status:'unknown',days:null};const end=new Date(asset.warranty_end+'T23:59:59+07:00').getTime(),days=Math.ceil((end-now)/86400000);return {status:end<now?'expired':days<=30?'expiring':'valid',days};}
export function businessMinutes(start,end,calendar={mode:'24x7'}){let a=new Date(start).getTime(),b=new Date(end).getTime();if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a)return 0;if(calendar.mode!=='business')return (b-a)/60000;const offset=7*3600000,first=Math.floor((a+offset)/86400000)*86400000-offset;let minutes=0;for(let d=first;d<b;d+=86400000){const date=new Date(d+offset),weekday=date.getUTCDay(),key=date.toISOString().slice(0,10);if(!(calendar.weekdays||[1,2,3,4,5]).includes(weekday)||(calendar.holidays||[]).includes(key))continue;const lo=d+(calendar.start_hour??9)*3600000,hi=d+(calendar.end_hour??18)*3600000;minutes+=Math.max(0,Math.min(b,hi)-Math.max(a,lo))/60000;}return minutes;}
export function sla(ticket,now=Date.now()){const p=ticket.sla_snapshot||{},calendar=p.calendar||{},end=ticket.resolved_at||new Date(now).toISOString(),pause=ticket.paused_at?businessMinutes(ticket.paused_at,end,calendar):0,elapsed=Math.max(0,businessMinutes(ticket.created_at,end,calendar)-Number(ticket.paused_minutes||0)-pause),rEnd=ticket.first_response_at||end,responseElapsed=Math.max(0,businessMinutes(ticket.created_at,rEnd,calendar)-Number(ticket.response_paused_minutes||0)-(ticket.first_response_at?0:pause)),response=Number(p.response_minutes||60)-responseElapsed,resolution=Number(p.resolution_minutes||480)-elapsed,ratio=Math.max(ticket.first_response_at?0:responseElapsed/Number(p.response_minutes||60),elapsed/Number(p.resolution_minutes||480)),status=ticket.paused_at?'paused':(response<0||resolution<0)?'breached':ratio>=.75?'warning':'on-track';return {response,resolution,ratio,status,elapsed,responseElapsed};}
export function remaining(minutes){const n=Math.ceil(Math.abs(minutes));return `${minutes<0?'-':''}${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
export function enrich(t,data){const find=(k,id)=>(data[k]||[]).find(x=>x.id===id)||{};const customer=find('customers',t.customer_id),contact=find('contacts',t.contact_id),asset=find('assets',t.asset_id),engineer=find('profiles',t.assigned_to_id),product=find('products',asset.product_id),owner=find('profiles',t.owner_id);return {...t,status:normalizeStatus(t.status),customer,contact,asset,engineer,product,owner,customer_name:customer.name||t.customer_name||'',contact_name:contact.name||t.contact_name||'',assigned_to_name:engineer.display_name||t.assigned_to_name||'',brand:asset.brand||product.brand||'',product_name:product.name||asset.name||'',category:t.service_data?.category||t.type||'Other'};}
export function filterTickets(rows,f={},now=Date.now()){return rows.filter(t=>{const s=sla(t,now),w=warranty(t.asset,now);if(f.query&&!([t.code,t.subject,t.customer_name,t.contact_name,t.asset?.code,t.asset?.serial_number,t.product_name,t.asset?.model,t.brand,t.assigned_to_name].join(' ').toLowerCase().includes(f.query.toLowerCase())))return false;for(const k of ['status','priority','request_type','customer_id','assigned_to_id','team_id','brand'])if(f[k]&&t[k]!==f[k])return false;if(f.product_id&&t.asset?.product_id!==f.product_id)return false;if(f.sla&&s.status!==f.sla)return false;if(f.warranty&&w.status!==f.warranty)return false;if(f.from&&day(t.created_at)<f.from||f.to&&day(t.created_at)>f.to)return false;if(f.due_from&&day(t.sla_deadline)<f.due_from||f.due_to&&day(t.sla_deadline)>f.due_to)return false;const today=day(now);return !f.kpi||({open:!isClosed(t),today:day(t.created_at)===today,unassigned:!t.assigned_to_id&&!isClosed(t),progress:['in-progress','diagnosing','repairing','testing'].includes(t.status),customer:t.status==='waiting-customer',parts:t.status==='waiting-parts',claim:t.status==='claim-processing',warning:!isClosed(t)&&s.status==='warning',breached:!isClosed(t)&&s.status==='breached',finished:day(t.resolved_at)===today})[f.kpi];});}
export function closureErrors(t,parts=[],claims=[]){const e=[];for(const k of ['resolution','root_cause','action_taken','assigned_to_id','testing_result'])if(!String(t[k]||'').trim())e.push(k);if(t.parts_changed&&!parts.length)e.push('parts');if(claims.some(c=>c.status!=='completed'))e.push('claims');return e;}
export function canTransition(from,to){from=normalizeStatus(from);if(from===to)return true;if(from==='closed'||from==='cancelled')return false;if(to==='closed')return from==='customer-confirmed';if(to==='customer-confirmed')return from==='resolved';if(from==='resolved'||from==='customer-confirmed')return to==='diagnosing';if(to==='resolved')return ['testing','in-progress','diagnosing','repairing'].includes(from);if(from==='new')return to==='assigned';if(from==='assigned')return to==='acknowledged';if(from==='acknowledged')return to==='diagnosing';return STATUSES.includes(to)&&!['new','assigned','acknowledged'].includes(to);}
export function analytics(rows,repairs=[],claims=[],now=Date.now()){const resolved=rows.filter(x=>x.resolved_at),responded=rows.filter(x=>x.first_response_at),counts=new Map;for(const t of rows)if(t.asset_id)counts.set(t.asset_id,(counts.get(t.asset_id)||0)+1);const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null,csat=rows.filter(x=>x.csat);return {total:rows.length,open:rows.filter(x=>!isClosed(x)).length,closed:rows.filter(isClosed).length,compliance:resolved.length?100*resolved.filter(x=>sla(x,now).status!=='breached').length/resolved.length:null,response:mean(responded.map(x=>sla(x,now).responseElapsed)),resolution:mean(resolved.map(x=>sla(x,now).elapsed)),firstFix:resolved.length?100*resolved.filter(x=>!x.reopened_count&&(counts.get(x.asset_id)||1)===1).length/resolved.length:null,repeat:rows.length?100*rows.filter(x=>(counts.get(x.asset_id)||0)>1).length/rows.length:null,csat:mean(csat.map(x=>Number(x.csat))),repairCost:repairs.reduce((s,r)=>s+Number(r.cost||0),0),claimCost:claims.reduce((s,c)=>s+Number(c.cost||0),0)};}
