import {DEFAULT_SETTINGS,STATUSES} from './service-model.mjs?v=20261001-service';
export function seedServiceDemo(d,profile){if(d.service_seeded)return;d.service_seeded=true;const now=Date.now(),iso=n=>new Date(n).toISOString(),id=(kind,i)=>`demo-service-${kind}-${i}`;
 d.service_settings=[{id:'default',config:structuredClone(DEFAULT_SETTINGS)}];d.service_teams=['Client Support','Infrastructure','Network & Security','Application Support'].map((name,i)=>({id:id('team',i),name,queue:'Service desk',active:true,supervisor_id:profile.id}));
 d.service_sla_policies=[{id:id('sla',1),name:'Standard 24x7',response_minutes:60,resolution_minutes:480,pause_statuses:['waiting-customer','waiting-vendor','waiting-approval'],calendar:{mode:'24x7'},coverage:'24x7',active:true}];
 d.service_profiles=[profile,...Array.from({length:5},(_,i)=>({id:id('engineer',i),display_name:`วิศวกร ${i+1}`,email:`engineer${i+1}@example.invalid`,is_active:true,role:'service_engineer'}))];
 for(const k of ['customers','contacts','branches','assets','contracts','tickets','quotations','knowledge','products','service_repairs','service_claims','service_parts','service_events','service_communications','service_attachments'])d[k]||=[];
 const add=(k,rows)=>{for(const row of rows)if(!d[k].some(x=>x.id===row.id))d[k].push(row);};
 add('products',Array.from({length:4},(_,i)=>({id:id('product',i),name:['Business Notebook','Rack Server','Firewall','Business App'][i],brand:['Lenovo','Dell','Fortinet','Microsoft'][i],category:['Endpoint','Server','Firewall','Software'][i]})));
 add('customers',Array.from({length:10},(_,i)=>({id:id('customer',i),code:`DEMO-C${i+1}`,name:`บริษัทตัวอย่างบริการ ${i+1}`,address:'กรุงเทพมหานคร',province:'กรุงเทพมหานคร',owner_id:profile.id,status:'active'})));
 add('contacts',Array.from({length:10},(_,i)=>({id:id('contact',i),name:`ผู้ติดต่อ ${i+1}`,customer_id:id('customer',i),email:`customer${i+1}@example.invalid`,phone:'02-000-0000',is_primary:true,status:'active'})));
 add('branches',Array.from({length:10},(_,i)=>({id:id('branch',i),name:'สำนักงานใหญ่',customer_id:id('customer',i),address:'กรุงเทพมหานคร',status:'active'})));
 add('contracts',Array.from({length:10},(_,i)=>({id:id('contract',i),code:`DEMO-MA-${i+1}`,name:`MA ${i+1}`,customer_id:id('customer',i),service_sla_id:id('sla',1),start_date:iso(now-864e5*100).slice(0,10),end_date:iso(now+864e5*300).slice(0,10),status:'active',type:'Maintenance'})));
 add('assets',Array.from({length:20},(_,i)=>({id:id('asset',i),code:`DEMO-AST-${i+1}`,name:d.products.find(x=>x.id===id('product',i%4)).name,customer_id:id('customer',i%10),branch_id:id('branch',i%10),contract_id:id('contract',i%10),product_id:id('product',i%4),category:['Endpoint','Server','Firewall','Software'][i%4],brand:['Lenovo','Dell','Fortinet','Microsoft'][i%4],model:`Model ${i%4+1}`,serial_number:`DEMO-SN-${i+1}`,warranty_start:iso(now-864e5*100).slice(0,10),warranty_end:iso(now+864e5*(i%3===0?-30:i%3===1?20:300)).slice(0,10),location:'สำนักงานใหญ่',status:'active'})));
 add('tickets',Array.from({length:20},(_,i)=>{const status=STATUSES[i%STATUSES.length],created=iso(now-(i%3===0?600:i%3===1?47:15)*60000),resolved=['resolved','customer-confirmed','closed'].includes(status);return {id:id('ticket',i),code:`SR-DEMO-${String(i+1).padStart(6,'0')}`,subject:['เปิดเครื่องไม่ได้','ระบบเครือข่ายขัดข้อง','ติดตั้งซอฟต์แวร์','ตรวจสอบอุปกรณ์'][i%4],customer_id:id('customer',i%10),contact_id:id('contact',i%10),asset_id:id('asset',i),contract_id:id('contract',i%10),branch_id:id('branch',i%10),assigned_to_id:i%5===0?null:id('engineer',i%5),owner_id:profile.id,team_id:id('team',i%4),status,priority:['low','medium','high','critical'][i%4],request_type:['Incident','Repair','Warranty Claim','Technical Support'][i%4],type:'Hardware',channel:'Phone',impact:'medium',urgency:'medium',created_at:created,updated_at:created,status_since:created,sla_snapshot:d.service_sla_policies[0],service_sla_id:id('sla',1),sla_deadline:iso(new Date(created).getTime()+480*60000),paused_minutes:0,response_paused_minutes:0,first_response_at:i%2?iso(new Date(created).getTime()+10*60000):null,paused_at:status.startsWith('waiting-')?iso(now-5*60000):null,resolved_at:resolved?iso(now-60000):null,resolution:resolved?'แก้ไขและทดสอบแล้ว':'',root_cause:resolved?'อุปกรณ์ขัดข้อง':'',action_taken:resolved?'แก้ไขและทดสอบ':'',testing_result:resolved?'Pass':'',customer_approved:true,service_data:{category:'Hardware',subcategory:'Notebook',symptom:'Power',first_time_fix:resolved?'yes':undefined},csat:resolved?4:null};}));
 add('service_repairs',Array.from({length:5},(_,i)=>({id:id('repair',i),code:`REPAIR-DEMO-${i+1}`,ticket_id:id('ticket',i),engineer_id:id('engineer',i),status:'received',received_at:iso(now),created_at:iso(now),updated_at:iso(now),details:{},cost:0})));
 add('service_claims',Array.from({length:5},(_,i)=>({id:id('claim',i),code:`CLAIM-DEMO-${i+1}`,rma_number:`RMA-DEMO-${i+1}`,ticket_id:id('ticket',i+5),status:'preparing',vendor:'Demo Vendor',created_at:iso(now),updated_at:iso(now),details:{},cost:0})));
 for(const t of d.tickets.filter(x=>String(x.id).startsWith('demo-service-')))d.service_events.push({id:crypto.randomUUID(),ticket_id:t.id,kind:'tickets',new_status:t.status,message:'ข้อมูลตัวอย่างในโหมดทดลอง',created_at:t.created_at});
}
