import {STATUSES,CLAIM_STATUSES,TYPES,CHANNELS,STATUS_LABELS,DEFAULT_SETTINGS,priority,warranty,sla,remaining,enrich,filterTickets,analytics,closureErrors,canTransition,day,isClosed} from './service-model.mjs?v=20261001-service';
import {seedServiceDemo} from './service-demo.mjs?v=20261001-service';
import {toCSV} from './settings-model.mjs';
const TABLES={customers:'customers',contacts:'contacts',branches:'crm_branches',assets:'assets',products:'products',contracts:'contracts',profiles:'profiles',tickets:'tickets',quotations:'quotations',knowledge:'crm_knowledge_articles',service_settings:'crm_service_settings',service_teams:'crm_service_teams',service_sla_policies:'crm_service_sla_policies',service_repairs:'crm_service_repairs',service_claims:'crm_service_claims',service_parts:'crm_service_parts',service_events:'crm_service_events',service_communications:'crm_service_communications',service_attachments:'crm_service_attachments'};
const clone=x=>structuredClone(x),money=n=>Number(n||0).toLocaleString('th-TH',{maximumFractionDigits:2}),title=s=>String(s||'').replaceAll('-',' ').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const DESCRIPTORS={
 repair:[['engineer_id','Engineer','profiles'],['status','Status',['received','diagnosing','repairing','testing','completed']],['received_at','Received at','datetime-local'],['started_at','Repair start','datetime-local'],['finished_at','Repair finish','datetime-local'],['details.device_condition','Device condition'],['details.accessories','Accessories received'],['details.inspection','Inspection result','textarea'],['diagnosis','Diagnosis','textarea'],['root_cause','Root cause','textarea'],['action_taken','Repair action','textarea'],['testing_result','Testing result','textarea'],['qc_result','QC result','textarea'],['cost','Repair cost','number'],['customer_approved','Customer approval','checkbox'],['details.note','Note','textarea']],
 claim:[['repair_id','Repair job','service_repairs'],['claim_type','Claim type',['Warranty','DOA','Repair','Replacement']],['vendor','Vendor'],['distributor','Distributor'],['vendor_ticket','Vendor ticket'],['status','Claim status',CLAIM_STATUSES],['submitted_at','Submitted at','datetime-local'],['courier','Courier'],['tracking_number','Tracking number'],['expected_return','Expected return','date'],['vendor_response','Vendor response','textarea'],['replacement_product_id','Replacement product','products'],['replacement_serial_number','Replacement serial number'],['cost','Claim cost','number'],['details.qc_result','QC result','textarea']],
 part:[['repair_id','Repair job','service_repairs'],['product_id','Product','products'],['part_no','Part number'],['name','Part name'],['serial_number','Serial number'],['quantity','Quantity','number'],['unit','Unit'],['unit_cost','Unit cost','number'],['selling_price','Selling price','number'],['stock_location','Stock location'],['warranty_part','Warranty part','checkbox'],['old_part_returned','Old part returned','checkbox'],['replacement_serial_number','Replacement serial number'],['inventory_reference','Inventory reference']],
 diagnosis:[['root_cause','Root cause','textarea'],['action_taken','Action taken','textarea'],['resolution','Resolution','textarea'],['testing_result','Testing result','textarea'],['parts_changed','Parts changed','checkbox'],['customer_approved','Customer approval','checkbox'],['service_data.first_time_fix','Fixed on first visit',['yes','no']],['csat','Satisfaction (1–5)','number'],['csat_comment','Customer feedback','textarea']],
 assignment:[['team_id','Service team','service_teams'],['service_data.queue','Queue'],['assigned_to_id','Engineer','profiles'],['backup_engineer_id','Backup engineer','profiles'],['service_data.location','Service location'],['service_data.mode','Service mode',['Remote','On-site','Carry-in']],['service_data.appointment','Appointment','datetime-local'],['service_data.expected_completion','Expected completion','datetime-local'],['service_sla_id','SLA policy','service_sla_policies']],
 problem:[['service_data.category','Problem category'],['service_data.subcategory','Subcategory'],['service_data.symptom','Symptom'],['service_data.error_code','Error code'],['description','Problem description','textarea'],['service_data.first_occurrence','First occurrence','datetime-local'],['service_data.frequency','Frequency'],['service_data.device_usable','Device usable','checkbox'],['service_data.business_impact','Business impact','textarea'],['service_data.troubleshooting','Troubleshooting performed','textarea'],['service_data.remote_result','Remote diagnostic result','textarea']],
 asset:[['product_id','Product','products'],['branch_id','Branch / Site','branches'],['assigned_user_id','Assigned user','contacts'],['purchase_date','Purchase date','date'],['installation_date','Installation date','date'],['warranty_type','Warranty type'],['warranty_provider','Warranty provider'],['vendor','Vendor'],['distributor','Distributor'],['next_maintenance','Next maintenance','date']],
 policy:[['name','Policy name'],['response_minutes','Response SLA (minutes)','number'],['resolution_minutes','Resolution SLA (minutes)','number'],['coverage','Coverage'],['active','Active','checkbox']],
 team:[['name','Team name'],['queue','Queue'],['supervisor_id','Supervisor','profiles'],['active','Active','checkbox']]
};
export function createServiceDesk({React,client,useApp,records}){
 const h=React.createElement;
 const unwrap=async p=>{const {data,error}=await p;if(error)throw error;return data;};
 async function all(table){const rows=[];for(let i=0;i<20000;i+=500){const part=await unwrap(client.from(table).select('*').order('id').range(i,i+499));rows.push(...part);if(part.length<500)return rows;}throw Error('More than 20,000 records: request a filtered server query');}
 function Modal({name,children,onClose,busy,onSave}){const ref=React.useRef(null);React.useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return h('dialog',{ref,className:'svc-dialog','aria-label':name,onCancel:e=>{e.preventDefault();if(!busy)onClose();}},h('form',{onSubmit:e=>{e.preventDefault();onSave();}},h('header',null,h('div',null,h('small',null,'KC CuTo · SERVICE DESK'),h('h2',null,name)),h('button',{type:'button','aria-label':'Close dialog',disabled:busy,onClick:onClose},'×')),h('div',{className:'svc-dialog-body'},children),h('footer',null,h('button',{type:'button',onClick:onClose,disabled:busy},'ยกเลิก / Cancel'),h('button',{type:'submit',className:'primary',disabled:busy},busy?'กำลังบันทึก…':'บันทึก / Save'))));}
 function Lookup({label,value,rows,onChange,required=false,disabled=false}){const [q,Q]=React.useState('');return h('label',{className:'svc-field'},h('span',null,label,required?' *':''),h('input',{type:'search',value:q,disabled,'aria-label':`Search ${label}`,placeholder:'ค้นหา / Search…',onChange:e=>Q(e.target.value)}),h('select',{'aria-label':label,value:value||'',required,disabled,onChange:e=>onChange(e.target.value)},h('option',{value:''},'— เลือก / Select —'),rows.filter(x=>x.id===value||[x.code,x.name,x.display_name,x.email,x.serial_number,x.model,x.brand,x.location,x.search_text].join(' ').toLowerCase().includes(q.toLowerCase())).map(x=>h('option',{key:x.id,value:x.id},[x.code,x.display_name||x.name||x.email,x.serial_number].filter(Boolean).join(' · ')))));}
 return function ServiceDesk({lang='th',route='tk-overview',params={},embedded=false,customerId,assetId}){
 const {demoMode,profile,navigate}=useApp(),th=lang==='th',txt=(a,b)=>th?a:b;
 const [data,D]=React.useState({}),[loaded,L]=React.useState(false),[busy,B]=React.useState(false),[error,E]=React.useState(''),[message,M]=React.useState(''),[permissions,P]=React.useState({}),[f,F]=React.useState({}),[view,V]=React.useState(route==='tk-kanban'?'kanban':'list'),[detail,Detail]=React.useState(null),[tab,Tab]=React.useState('Overview'),[modal,ModalState]=React.useState(null),[draft,Draft]=React.useState({}),[advanced,A]=React.useState(false),[now,Now]=React.useState(Date.now()),[page,Page]=React.useState(0),[files,Files]=React.useState([]);
 const lock=React.useRef(false),mounted=React.useRef(true);
 const can=a=>demoMode||profile?.role==='admin'||!!permissions[`can_${a}`];
 const setting={...DEFAULT_SETTINGS,...data.service_settings?.[0]?.config};
 const rows=(data.tickets||[]).map(x=>enrich(x,data)).filter(x=>(!customerId||x.customer_id===customerId)&&(!assetId||x.asset_id===assetId));
 const selected=rows.find(x=>x.id===detail),filtered=filterTickets(rows,{...f,...(route==='tk-mine'?{assigned_to_id:profile.id}:{})},now),shown=filtered.slice(page*30,page*30+30);
 const related=(key,t=selected)=>(data[key]||[]).filter(x=>x.ticket_id===t?.id);
 const badge=(label,kind='')=>h('span',{className:`svc-badge ${kind}`},label);
 const b=(name,fn,opts={})=>h('button',{type:'button',onClick:fn,disabled:busy,...opts},name);
 const statusName=s=>th?(STATUS_LABELS[s]||title(s)):title(s);
 const section=(name,children)=>h('section',{className:'svc-card'},h('h3',null,name),children);
 const errorText=x=>x?.message||String(x);
 async function run(fn){if(lock.current)return;lock.current=true;B(true);E('');M('');try{await fn();}catch(e){E(errorText(e));}finally{lock.current=false;if(mounted.current)B(false);}}
 async function load(){let next={};if(demoMode){for(const key of Object.keys(TABLES))if(key!=='profiles')records[key]||=[];records.service_profiles||=[profile];if(!records.service_sla_policies.length)records.service_sla_policies.push({id:'demo-service-default-sla',name:'Standard 24x7',response_minutes:60,resolution_minutes:480,pause_statuses:['waiting-customer','waiting-vendor','waiting-approval'],calendar:{mode:'24x7'},active:true});if(!embedded)seedServiceDemo(records,profile);for(const key of Object.keys(TABLES))next[key]=clone(key==='profiles'?(records.service_profiles||[profile]):records[key]||[]);}else{
 const results=await Promise.allSettled(Object.entries(TABLES).map(async([k,t])=>[k,await all(t)]));const failures=[];results.forEach((r,i)=>{if(r.status==='fulfilled')next[r.value[0]]=r.value[1];else{const k=Object.keys(TABLES)[i];next[k]=[];if(k.startsWith('service_')||k==='tickets')failures.push(`${k}: ${errorText(r.reason)}`);}});if(failures.length)throw Error(failures.join('\n'));}
 if(mounted.current){D(next);L(true);}return next;}
 React.useEffect(()=>{mounted.current=true;run(async()=>{if(!demoMode&&profile?.role!=='admin'){const list=await unwrap(client.from('role_permissions').select('*').eq('role_key',profile?.custom_role_key||profile?.role).in('module',['tickets','quotations']));P({...list.find(x=>x.module==='tickets'),quotation_create:!!list.find(x=>x.module==='quotations')?.can_create});}await load();});const timer=setInterval(()=>Now(Date.now()),1000);return()=>{mounted.current=false;clearInterval(timer);};},[]);
 React.useEffect(()=>{Page(0);},[JSON.stringify(f)]);
 React.useEffect(()=>{if(loaded&&params.recordId)Detail(params.recordId);if(loaded&&(params.create||route==='tk-create'))open('create');},[loaded,params.recordId,params.create]);
 function open(kind,row){E('');Files([]);ModalState(kind);Draft(row?clone(row):kind==='create'?{subject:'',customer_id:customerId||'',asset_id:assetId||'',request_type:'Incident',channel:'Phone',type:'Hardware',priority:'medium',impact:'medium',urgency:'medium',service_data:{category:'Hardware',subcategory:'Notebook',symptom:'Power'},service_sla_id:data.service_sla_policies?.find(x=>x.active)?.id||''}:kind==='repair'?{ticket_id:selected.id,engineer_id:selected.assigned_to_id,status:'received',received_at:new Date().toISOString(),details:{},cost:0}:kind==='claim'?{ticket_id:selected.id,status:'preparing',claim_type:'Warranty',details:{},cost:0}:kind==='part'?{ticket_id:selected.id,repair_id:related('service_repairs')[0]?.id||'',quantity:1,unit:'unit',unit_cost:0,selling_price:0}:kind==='communication'?{ticket_id:selected.id,channel:'Internal Note',recipient_contact_id:selected.contact_id,message:'',delivery_status:'logged'}:kind==='status'?{...clone(selected),service_data:{...selected.service_data,transition_comment:''}}:kind==='settings'?{config:clone(setting)}:kind==='policy'?{name:'',response_minutes:60,resolution_minutes:480,pause_statuses:['waiting-customer','waiting-vendor','waiting-approval'],calendar:{mode:'24x7',weekdays:[1,2,3,4,5],start_hour:9,end_hour:18,holidays:[]},active:true}:kind==='team'?{name:'',active:true}:kind==='quotation'?{items:[...related('service_parts').map(x=>({name:x.name,qty:Number(x.quantity),price:Number(x.selling_price),cost:Number(x.unit_cost),unit:x.unit,product_id:x.product_id,service_part_id:x.id})),{name:'Service / ค่าแรง',qty:1,price:0,cost:0,unit:'งาน'}]}:clone(selected||{}));}
 function set(key,value){Draft(prev=>{const out=clone(prev);if(key.includes('.')){const [a,k]=key.split('.');out[a]={...out[a],[k]:value};}else out[key]=value;if(key==='customer_id'){out.contact_id='';out.asset_id='';out.branch_id='';out.contract_id='';const c=data.contacts?.find(x=>x.customer_id===value&&x.is_primary);if(c)out.contact_id=c.id;}
 if(key==='asset_id'){const a=data.assets?.find(x=>x.id===value);if(a){out.customer_id=a.customer_id;out.branch_id=a.branch_id;out.contract_id=a.contract_id;const c=data.contracts?.find(x=>x.id===a.contract_id);if(c?.service_sla_id)out.service_sla_id=c.service_sla_id;const name=setting.auto_assignment?.[a.category];out.team_id=data.service_teams?.find(x=>x.name===name)?.id||out.team_id;}}
 if(['impact','urgency'].includes(key))out.priority=priority(out.impact,out.urgency);
 if(key==='service_data.category'){out.service_data.subcategory='';out.service_data.symptom='';}if(key==='service_data.subcategory')out.service_data.symptom='';return out;});}
 function field([key,label,type='text'],required=false){const value=key.includes('.')?draft[key.split('.')[0]]?.[key.split('.')[1]]:draft[key];const disabled=busy;let opts=type;if(key==='service_data.category')opts=Object.keys(setting.categories||{});if(key==='service_data.subcategory')opts=Object.keys(setting.categories?.[draft.service_data?.category]||{});if(key==='service_data.symptom')opts=setting.categories?.[draft.service_data?.category]?.[draft.service_data?.subcategory]||[];
 if(TABLES[type]){let list=data[type]||[];if(['contacts','branches','assets','contracts'].includes(type)&&draft.customer_id)list=list.filter(x=>x.customer_id===draft.customer_id);if(type==='service_repairs')list=list.filter(x=>x.ticket_id===(draft.ticket_id||selected?.id));if(type==='profiles')list=list.filter(x=>x.is_active!==false);if(type==='assets')list=list.map(x=>({...x,search_text:[data.customers?.find(c=>c.id===x.customer_id)?.name,data.branches?.find(b=>b.id===x.branch_id)?.name,data.contacts?.find(c=>c.id===x.assigned_user_id)?.name].filter(Boolean).join(' ')}));return h(Lookup,{key,label,value,rows:list,onChange:v=>set(key,v),required,disabled});}
 const props={'aria-label':label,value:value??'',required,disabled,onChange:e=>set(key,type==='checkbox'?e.target.checked:type==='number'?e.target.value===''?'':Number(e.target.value):e.target.value)};
 let input=Array.isArray(opts)?h('select',props,h('option',{value:''},'—'),opts.map(x=>h('option',{key:x,value:x},title(x)))):type==='textarea'?h('textarea',{...props,rows:3}):type==='checkbox'?h('input',{...props,type:'checkbox',checked:!!value,value:undefined}):h('input',{...props,type,min:type==='number'?0:undefined,max:key==='csat'?5:undefined,step:type==='number'?'any':undefined,value:type==='datetime-local'&&value?new Date(new Date(value).getTime()+7*3600000).toISOString().slice(0,16):value??'',onChange:e=>set(key,type==='datetime-local'&&e.target.value?new Date(e.target.value+':00+07:00').toISOString():type==='number'?e.target.value===''?'':Number(e.target.value):e.target.value)});
 return h('label',{key,className:'svc-field'+(type==='textarea'?' wide':'')},h('span',null,label,required?' *':''),input);}
 const fields=arr=>h('div',{className:'svc-fields'},arr.map(x=>field(x)));
 async function saveRecord(key,patch,original){const clean=Object.fromEntries(Object.entries(patch).filter(([k])=>!['customer','contact','asset','engineer','product','owner','brand','product_name'].includes(k)));for(const k of Object.keys(clean))if(k.endsWith('_id')&&clean[k]==='')clean[k]=null;
 let saved;if(demoMode){const id=original?.id||crypto.randomUUID(),stamp=new Date().toISOString(),old=(records[key]||[]).find(x=>x.id===id);saved={...old,...clean,id,created_at:old?.created_at||stamp,updated_at:stamp};if(key==='quotations'&&!old)saved.code='SQ-DEMO-'+String((records.quotations||[]).length+1).padStart(6,'0');if(['tickets','service_repairs','service_claims'].includes(key)&&!old)saved.code=`${setting.prefixes?.[key==='tickets'?'ticket':key==='service_repairs'?'repair':'claim']||'SR'}-DEMO-${String((records[key]||[]).length+1).padStart(6,'0')}`;
 if(key==='tickets'){if(!old){saved.status='new';saved.owner_id=profile.id;saved.sla_snapshot=clone(data.service_sla_policies.find(x=>x.id===saved.service_sla_id)||data.service_sla_policies[0]);saved.sla_deadline=new Date(Date.now()+saved.sla_snapshot.resolution_minutes*60000).toISOString();}else if(saved.status!==old.status){if(!canTransition(old.status,saved.status))throw Error('Invalid workflow transition');if(saved.status==='assigned'&&!saved.assigned_to_id)throw Error('Engineer required');if(['resolved','customer-confirmed','closed'].includes(saved.status)){const errs=closureErrors(saved,(records.service_parts||[]).filter(x=>x.ticket_id===id),(records.service_claims||[]).filter(x=>x.ticket_id===id));if(errs.length)throw Error(`Complete: ${errs.join(', ')}`);if(records.service_repairs.some(x=>x.ticket_id===id&&x.status!=='completed'))throw Error('Complete all repairs first');saved.resolved_at||=stamp;}if(saved.status==='acknowledged')saved.first_response_at||=stamp;if(old.paused_at){const mins=(Date.now()-new Date(old.paused_at))/60000;saved.paused_minutes=Number(old.paused_minutes||0)+mins;if(!old.first_response_at)saved.response_paused_minutes=Number(old.response_paused_minutes||0)+mins;saved.paused_at=null;}if(saved.sla_snapshot.pause_statuses.includes(saved.status))saved.paused_at=stamp;saved.status_since=stamp;}if(saved.status==='repairing'&&warranty(data.assets.find(x=>x.id===saved.asset_id)).status==='expired'&&!saved.customer_approved)throw Error('Customer approval required');}
 if(key==='service_repairs'&&saved.status==='completed'&&['diagnosis','root_cause','action_taken','testing_result','qc_result','engineer_id'].some(k=>!saved[k]))throw Error('Complete repair diagnosis, action, testing and QC');
 if(key==='service_claims'){saved.rma_number||=`RMA-DEMO-${saved.code}`;if(old&&saved.status!==old.status&&CLAIM_STATUSES.indexOf(saved.status)!==CLAIM_STATUSES.indexOf(old.status)+1)throw Error('Follow RMA workflow in order');if(saved.status==='completed'){if(!saved.details?.qc_result)throw Error('Claim QC required');const ticket=records.tickets.find(x=>x.id===saved.ticket_id),asset=records.assets.find(x=>x.id===ticket.asset_id);if(asset&&saved.replacement_serial_number){records.service_events.push({id:crypto.randomUUID(),ticket_id:ticket.id,kind:'asset-replacement',message:`${asset.serial_number} → ${saved.replacement_serial_number}`,created_at:stamp});asset.serial_number=saved.replacement_serial_number;if(saved.replacement_product_id)asset.product_id=saved.replacement_product_id;}}}
 records[key]||=[];records[key]=[...records[key].filter(x=>x.id!==id),saved];if(key==='tickets'||saved.ticket_id)records.service_events.push({id:crypto.randomUUID(),ticket_id:key==='tickets'?id:saved.ticket_id,actor_id:profile.id,kind:key,old_status:old?.status,new_status:saved.status,message:saved.service_data?.transition_comment||saved.message||saved.code||'Updated',created_at:stamp});
 }else{let q=original?.id?client.from(TABLES[key]).update(clean).eq('id',original.id):client.from(TABLES[key]).insert(clean);if(original?.updated_at)q=q.eq('updated_at',original.updated_at);saved=await unwrap(q.select().maybeSingle());if(!saved)throw Error('Record changed or access denied. Reload and try again.');}return saved;}
 async function upload(ticketId){for(const file of files){if(file.size>25*1024*1024)throw Error('Maximum attachment size is 25 MB');const name=file.name,path=`${ticketId}/${crypto.randomUUID()}-${name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,mime=file.type||'text/plain';if(demoMode){await saveRecord('service_attachments',{ticket_id:ticketId,name,path,mime_type:mime,size_bytes:file.size,phase:draft.attachment_phase||'problem',demo_url:URL.createObjectURL(file)});}else{await unwrap(client.storage.from('service-attachments').upload(path,file,{contentType:mime,upsert:false}));await saveRecord('service_attachments',{ticket_id:ticketId,name,path,mime_type:mime,size_bytes:file.size,phase:draft.attachment_phase||'problem'});}}Files([]);}
 async function submit(){await run(async()=>{let saved;if(modal==='create'||['edit','diagnosis','assignment','problem','status'].includes(modal)){const keys=['subject','customer_id','contact_id','asset_id','contract_id','branch_id','request_type','channel','type','priority','impact','urgency','description','service_data','team_id','assigned_to_id','backup_engineer_id','service_sla_id','root_cause','action_taken','resolution','testing_result','parts_changed','customer_approved','csat','csat_comment'];if(modal!=='create')keys.push('status');const patch=Object.fromEntries(keys.filter(k=>draft[k]!==undefined).map(k=>[k,draft[k]]));if(!patch.subject?.trim()||!patch.customer_id)throw Error('Customer and subject required');saved=await saveRecord('tickets',patch,modal==='create'?null:selected);Detail(saved.id);if(files.length){ModalState('edit');Draft({...draft,...saved});}await upload(saved.id);}
 else if(['repair','claim','part'].includes(modal)){const key={repair:'service_repairs',claim:'service_claims',part:'service_parts'}[modal],keys=DESCRIPTORS[modal].map(x=>x[0].split('.')[0]);saved=await saveRecord(key,Object.fromEntries([...new Set(['ticket_id',...keys])].map(k=>[k,draft[k]??null])),draft.id?draft:null);await upload(draft.ticket_id);}
 else if(modal==='communication'){await saveRecord('service_communications',{ticket_id:selected.id,channel:draft.channel,message:draft.message,recipient_contact_id:draft.recipient_contact_id||null,delivery_status:draft.channel==='Email'?'draft':'logged'});}
 else if(modal==='attachment')await upload(selected.id);
 else if(modal==='policy'||modal==='team'){const key=modal==='policy'?'service_sla_policies':'service_teams';await saveRecord(key,draft,draft.id?draft:null);}
 else if(modal==='settings')await saveRecord('service_settings',{config:draft.config,updated_at:new Date().toISOString()},{id:'default'});
 else if(modal==='quotation'){const items=draft.items.filter(x=>x.name&&Number(x.qty)>0).map(x=>({...x,qty:Number(x.qty),price:Number(x.price),cost:Number(x.cost||0)}));if(!items.length)throw Error('Add service items');const subtotal=items.reduce((s,x)=>s+x.qty*x.price,0);saved=await saveRecord('quotations',{customer_id:selected.customer_id,contact_id:selected.contact_id,owner_id:profile.id,service_ticket_id:selected.id,service_asset_id:selected.asset_id,reference_document:selected.code,project_name:selected.subject,items,subtotal,vat:subtotal*.07,total:subtotal*1.07,tax_rate:7,discount:0,status:'draft',note:`Service ${selected.code} / S/N ${selected.asset.serial_number||''}`});await saveRecord('tickets',{quotation_id:saved.id},selected);}
 else if(modal==='knowledge'){if(selected.status!=='closed')throw Error('Close ticket first');await saveRecord('knowledge',{name:selected.subject,description:selected.description||'',category:selected.category,status:'draft',service_ticket_id:selected.id,product_id:selected.asset.product_id||null,model:selected.asset.model||'',error_code:selected.service_data?.error_code||'',root_cause:selected.root_cause,solution:selected.resolution,tags:String(draft.tags||'').split(',').map(x=>x.trim()).filter(Boolean)});}
 await load();ModalState(null);M(txt('บันทึกแล้ว','Saved'));});}
 function drill(filter){F(filter);Detail(null);navigate('tickets','tk-all',{serviceFilter:filter});}
 React.useEffect(()=>{if(params.serviceFilter)F(params.serviceFilter);},[JSON.stringify(params.serviceFilter)]);
 const kpis=[['open','เคสเปิดอยู่','Open tickets'],['today','เปิดใหม่วันนี้','New today'],['unassigned','รอรับงาน','Unassigned'],['progress','กำลังดำเนินการ','In progress'],['customer','รอลูกค้า','Waiting customer'],['parts','รออะไหล่','Waiting parts'],['claim','อยู่ระหว่างเคลม','Claim processing'],['warning','SLA ใกล้ครบ','SLA warning'],['breached','SLA เกินกำหนด','SLA breached'],['finished','เสร็จวันนี้','Completed today']];
 const ticketIds=new Set(rows.map(x=>x.id));const scopedRepairs=(data.service_repairs||[]).filter(x=>ticketIds.has(x.ticket_id)),scopedClaims=(data.service_claims||[]).filter(x=>ticketIds.has(x.ticket_id));const summary=analytics(rows,scopedRepairs,scopedClaims,now);summary.repairCost+=(data.service_parts||[]).filter(x=>ticketIds.has(x.ticket_id)).reduce((n,x)=>n+Number(x.quantity)*Number(x.unit_cost),0);
 function charts(){const dims=[['status','สถานะ / Status',x=>x.status],['priority','Priority',x=>x.priority],['request_type','ประเภทคำขอ / Request type',x=>x.request_type],['category','ประเภทปัญหา / Problem',x=>x.category],['product_id','สินค้า / Product',x=>x.asset.product_id||x.product_name],['brand','Brand',x=>x.brand],['model','Model',x=>x.asset.model],['customer_id','ลูกค้า / Customer',x=>x.customer_id],['assigned_to_id','Engineer',x=>x.assigned_to_id],['month','เดือน / Month',x=>day(x.created_at).slice(0,7)],['asset','อุปกรณ์ขัดข้อง / Failure by asset',x=>x.asset.code],['warranty','Warranty',x=>warranty(x.asset,now).status]];return h('div',{className:'svc-charts'},dims.map(([key,label,get])=>{const counts=new Map;rows.forEach(x=>{const v=get(x)||'Unspecified';counts.set(v,(counts.get(v)||0)+1);});const top=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,10),max=Math.max(1,...top.map(x=>x[1]));return section(label,h('div',{className:'svc-bars'},top.length?top.map(([v,n])=>{const item=key==='customer_id'?data.customers.find(x=>x.id===v):key==='assigned_to_id'?data.profiles.find(x=>x.id===v):key==='product_id'?data.products.find(x=>x.id===v):null;return b(h(React.Fragment,null,h('span',null,item?.name||item?.display_name||statusName(v)),h('i',{style:{width:`${100*n/max}%`}}),h('strong',null,n)),()=>drill({[key]:v}),{key:v});}):h('p',null,'ยังไม่มีข้อมูล / No records')));}));}
 function dashboard(){return h(React.Fragment,null,h('div',{className:'svc-kpis'},kpis.map(([key,a,c])=>b(h(React.Fragment,null,h('span',null,txt(a,c)),h('strong',null,filterTickets(rows,{kpi:key},now).length)),()=>drill({kpi:key}),{key,className:`svc-kpi ${key}`,'data-kpi':key}))),h('div',{className:'svc-metrics'},[['SLA compliance',summary.compliance,'%'],['Avg response',summary.response,' min'],['Avg resolution',summary.resolution,' min'],['First time fix',summary.firstFix,'%'],['Repeat asset incidents',summary.repeat,'%'],['CSAT',summary.csat,' / 5'],['Repair cost',summary.repairCost,' ฿'],['Claim cost',summary.claimCost,' ฿']].map(([label,value,unit])=>h('div',{key:label},h('small',null,label),h('strong',null,value==null?'—':money(value)+unit)))),h('p',{className:'svc-muted'},txt('เวลาเฉลี่ยและ SLA คำนวณจากเคสที่มีเวลารับงาน/แก้ไขตามปฏิทิน SLA · — หมายถึงยังไม่มีข้อมูล','Averages use recorded response/resolution and SLA calendar · — means no observations')),charts());}
 const timers=t=>{const s=sla(t,now);return h('div',{className:'svc-timers'},badge(title(s.status),s.status),h('span',null,`Response ${remaining(s.response)}${t.first_response_at?' ✓':''}`),h('span',null,`Resolution ${remaining(s.resolution)}${t.resolved_at?' ✓':''}`));};
 function exportCSV(){const keys=['code','customer_name','contact_name','subject','request_type','status','priority','assigned_to_name','created_at','sla_deadline'];const url=URL.createObjectURL(new Blob(['\ufeff'+toCSV(filtered,keys)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='service-tickets.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function filters(){const select=(key,label,options)=>h('label',{className:'svc-field',key},h('span',null,label),h('select',{'aria-label':label,value:f[key]||'',onChange:e=>F({...f,[key]:e.target.value})},h('option',{value:''},'ทั้งหมด / All'),options.map(x=>h('option',{key:x.id||x,value:x.id||x},x.name||x.display_name||statusName(x)))));return h('div',{className:'svc-filters'},h('div',{className:'svc-toolbar'},h('input',{type:'search','aria-label':'Search cases',placeholder:'ค้นหาเคส ลูกค้า S/N สินค้า วิศวกร…',value:f.query||'',onChange:e=>F({...f,query:e.target.value})}),b('ตัวกรอง / Filters',()=>A(!advanced),{'aria-expanded':advanced}),b('ล้างตัวกรอง / Reset',()=>F({})),...['list','kanban','card'].map(x=>b(title(x),()=>V(x),{'aria-pressed':view===x,key:x}))),advanced&&h('div',{className:'svc-fields'},select('status','Status',STATUSES),select('priority','Priority',setting.priorities),select('request_type','Request type',setting.ticket_types),select('customer_id','Customer',data.customers||[]),select('product_id','Product',data.products||[]),select('brand','Brand',[...new Set(rows.map(x=>x.brand).filter(Boolean))]),select('assigned_to_id','Engineer',data.profiles||[]),select('team_id','Service team',data.service_teams||[]),select('sla','SLA status',['on-track','warning','breached','paused']),select('warranty','Warranty status',['valid','expiring','expired','unknown']),...['from','to','due_from','due_to'].map(key=>h('label',{className:'svc-field',key},h('span',null,{from:'Created from',to:'Created to',due_from:'Due from',due_to:'Due to'}[key]),h('input',{type:'date','aria-label':key,value:f[key]||'',onChange:e=>F({...f,[key]:e.target.value})})))));}
 function card(t){return b(h(React.Fragment,null,h('small',null,t.code),h('strong',null,t.subject),h('span',null,t.customer_name),h('span',null,t.asset.serial_number||'—'),h('div',null,badge(statusName(t.status)),badge(t.priority,t.priority)),timers(t),h('span',null,t.assigned_to_name||'ยังไม่มอบหมาย')),()=>Detail(t.id),{key:t.id,className:'svc-ticket-card','aria-label':`Open ${t.code}`});}
 function list(){
 const columns=['Case','Customer / Contact','Asset / S/N','Subject / Type','Status','Priority','SLA','Opened / Due','Owner / Engineer','Actions'];
 const tableRows=shown.map(t=>h('tr',{key:t.id},
 h('td',null,b(t.code,()=>Detail(t.id))),h('td',null,t.customer_name,h('small',null,t.contact_name)),
 h('td',null,t.asset.code,h('small',null,t.asset.serial_number)),h('td',null,t.subject,h('small',null,t.request_type)),
 h('td',null,badge(statusName(t.status))),h('td',null,badge(t.priority,t.priority)),
 h('td',null,badge(title(sla(t,now).status),sla(t,now).status)),
 h('td',null,day(t.created_at),h('small',null,day(t.sla_deadline))),
 h('td',null,t.owner.display_name,h('small',null,t.assigned_to_name)),h('td',null,b(txt('เปิด','Open'),()=>Detail(t.id)))));
 const table=h('div',{className:'svc-table-scroll'},h('table',null,h('thead',null,h('tr',null,columns.map(x=>h('th',{key:x},x)))),h('tbody',null,tableRows)));
 const board=h('div',{className:'svc-kanban'},STATUSES.map(s=>h('section',{key:s},h('h3',null,statusName(s),' · ',filtered.filter(x=>x.status===s).length),filtered.filter(x=>x.status===s).slice(0,100).map(card))));
 return h(React.Fragment,null,filters(),h('p',{role:'status'},`${filtered.length} ${txt('เคส','cases')}`),view==='kanban'?board:view==='card'?h('div',{className:'svc-cards'},shown.map(card)):table,
 !filtered.length&&section(txt('ยังไม่มีเคสในมุมมองนี้','No cases in this view'),h('p',null,txt('สร้างเคสหรือปรับตัวกรองเพื่อเริ่มต้น','Create a case or change filters'))),
 view!=='kanban'&&h('div',{className:'svc-toolbar'},b('←',()=>Page(Math.max(0,page-1)),{disabled:page===0}),h('span',null,`${page+1} / ${Math.max(1,Math.ceil(filtered.length/30))}`),b('→',()=>Page(page+1),{disabled:(page+1)*30>=filtered.length})));
 }
 function jobList(key,kind,items=data[key]||[]){return h('div',{className:'svc-table-scroll'},h('table',null,h('thead',null,h('tr',null,['Number','Ticket','Status','Cost','Actions'].map(x=>h('th',{key:x},x)))),h('tbody',null,items.map(x=>h('tr',{key:x.id},h('td',null,x.code||x.part_no||x.name),h('td',null,b(rows.find(t=>t.id===x.ticket_id)?.code||'Case',()=>{Detail(x.ticket_id);Tab(kind==='repair'?'Repair':kind==='claim'?'Claim':'Parts');})),h('td',null,badge(title(x.status||'used'))),h('td',null,money(x.cost??Number(x.quantity)*Number(x.unit_cost))),h('td',null,can('edit')&&b('แก้ไข / Edit',()=>{Detail(x.ticket_id);open(kind,x);})))))));}
 function info(record,keys){return h('dl',{className:'svc-info'},keys.map(([key,label])=>h(React.Fragment,{key},h('dt',null,label),h('dd',null,String(record?.[key]??'—')))));}
 function assetInfo(a){const w=warranty(a,now),c=data.contracts?.find(x=>x.id===a.contract_id);return h(React.Fragment,null,badge(w.status==='valid'?'In Warranty':w.status==='expiring'?'Expiring Soon':w.status==='expired'?'Out of Warranty':'Warranty unknown',w.status),w.days!=null&&h('span',null,` ${w.days} days`),w.status==='expired'&&h('p',{className:'svc-alert'},'สินทรัพย์นี้หมดระยะประกันแล้ว กรุณาตรวจสอบค่าใช้จ่ายและการอนุมัติจากลูกค้าก่อนดำเนินการ'),info(a,[['code','Asset tag'],['serial_number','Serial number'],['name','Product'],['brand','Brand'],['model','Model'],['category','Category'],['location','Location'],['purchase_date','Purchase date'],['installation_date','Installed'],['warranty_start','Warranty start'],['warranty_end','Warranty end'],['warranty_type','Warranty type'],['warranty_provider','Warranty provider'],['vendor','Vendor'],['distributor','Distributor'],['next_maintenance','Next maintenance']]),c&&info(c,[['code','Contract'],['type','Contract type'],['start_date','Contract start'],['end_date','Contract end'],['sla_level','SLA']]),h('p',null,`Previous repairs: ${(data.service_repairs||[]).filter(r=>rows.some(t=>t.id===r.ticket_id&&t.asset_id===a.id)).length}`));}
 function details(){const t=selected,tabs=['Overview','Customer','Asset','Problem','Diagnosis','Repair','Claim','Parts','Communication','Attachments','Activity','SLA','History'],events=related('service_events').sort((a,b)=>b.created_at.localeCompare(a.created_at)),quote=data.quotations?.find(x=>x.id===t.quotation_id||x.service_ticket_id===t.id);let body;
 if(tab==='Overview')body=info(t,[['subject','Subject'],['request_type','Request type'],['channel','Channel'],['description','Description'],['priority','Priority'],['created_at','Opened at'],['resolved_at','Resolution date'],['resolution','Resolution']]);
 if(tab==='Customer')body=h(React.Fragment,null,info(t.customer,[['code','Customer code'],['name','Customer'],['address','Address'],['owner_name','Sales owner']]),info(t.contact,[['name','Contact'],['position','Position'],['phone','Phone'],['email','Email']]),b('เปิดบัญชีลูกค้า / Customer 360',()=>navigate('customers','customer-list',{recordId:t.customer_id})));
 if(tab==='Asset')body=h(React.Fragment,null,assetInfo(t.asset),b('เปิดสินทรัพย์ / Asset 360',()=>navigate('assets','asset-all',{recordId:t.asset_id})));
 if(tab==='Problem')body=h(React.Fragment,null,info(t.service_data,DESCRIPTORS.problem.filter(x=>x[0].includes('.')).map(x=>[x[0].split('.')[1],x[1]])),can('edit')&&b('แก้ไขปัญหา / Edit problem',()=>open('problem',t)));
 if(tab==='Diagnosis')body=h(React.Fragment,null,info(t,DESCRIPTORS.diagnosis.map(x=>[x[0],x[1]])),can('edit')&&b('บันทึกการแก้ไข / Resolution',()=>open('diagnosis',t)));
 if(tab==='Repair'||tab==='Claim'||tab==='Parts'){const kind=tab==='Repair'?'repair':tab==='Claim'?'claim':'part',key=`service_${kind==='part'?'parts':kind+'s'}`;body=h(React.Fragment,null,can('edit')&&b(`+ ${tab}`,()=>open(kind),{className:'primary'}),jobList(key,kind,related(key)));}
 if(tab==='Communication')body=h(React.Fragment,null,can('edit')&&b('ส่งอัปเดตให้ลูกค้า / Compose update',()=>open('communication')),related('service_communications').map(x=>section(`${x.channel} · ${x.delivery_status}`,h('p',{style:{whiteSpace:'pre-wrap'}},x.message))));
 if(tab==='Attachments')body=h(React.Fragment,null,can('edit')&&b('+ แนบไฟล์ / Attach files',()=>open('attachment')),related('service_attachments').map(x=>b(`${x.phase} · ${x.name}`,()=>run(async()=>{const url=demoMode?x.demo_url:(await unwrap(client.storage.from('service-attachments').createSignedUrl(x.path,60))).signedUrl;if(!url)throw Error('File unavailable');window.open(url,'_blank','noopener,noreferrer');}),{key:x.id})));
 if(['History','Activity'].includes(tab))body=h('ol',{className:'svc-timeline'},events.map(x=>h('li',{key:x.id},h('strong',null,title(x.kind)),h('p',null,x.old_status?`${title(x.old_status)} → ${title(x.new_status)}`:title(x.new_status)),h('p',null,x.message),h('small',null,new Date(x.created_at).toLocaleString(th?'th-TH':'en-GB',{timeZone:'Asia/Bangkok'}),' · ',data.profiles?.find(p=>p.id===x.actor_id)?.display_name||'System'))));
 if(tab==='SLA')body=h(React.Fragment,null,timers(t),info(t.sla_snapshot,[['name','Policy'],['response_minutes','Response (minutes)'],['resolution_minutes','Resolution (minutes)'],['coverage','Coverage']]),h('p',null,`Paused ${money(t.paused_minutes)} minutes`),can('assign')&&b('ปรับ SLA / Assignment',()=>open('assignment',t)));
 return h(React.Fragment,null,b('← รายการเคส / Cases',()=>Detail(null)),h('header',{className:'svc-detail-header'},h('div',null,h('small',null,t.code),h('h2',null,t.subject),h('p',null,t.customer_name,' · ',t.asset.serial_number)),h('div',null,badge(statusName(t.status)),badge(t.priority,t.priority),timers(t))),h('div',{className:'svc-toolbar'},can('edit')&&t.status!=='closed'&&b('แก้ไขเคส / Edit case',()=>open('edit',t)),can('edit')&&b('สถานะ / Status',()=>open('status',t)),can('assign')&&b('มอบหมาย / Assign',()=>open('assignment',t)),can('edit')&&b('นัดหมาย / Appointment',()=>open('assignment',t)),can('edit')&&b('Note / Email',()=>open('communication')),can('edit')&&b('+ Repair',()=>open('repair')),can('edit')&&b('+ Claim / RMA',()=>open('claim')),(demoMode||profile?.role==='admin'||permissions.quotation_create)&&b('+ Quotation',()=>open('quotation')),can('edit')&&b('ปิดงาน / Close case',()=>open('status',{...t,status:'closed'})),t.status==='closed'&&can('edit')&&b('+ Knowledge article',()=>open('knowledge')),quote&&b(`Quotation ${quote.code}`,()=>navigate('quotations','quot-list',{recordId:quote.id}))),h('div',{className:'svc-detail-grid'},h('div',null,h('nav',{className:'svc-tabs','aria-label':'Ticket detail tabs'},tabs.map(x=>b(x,()=>Tab(x),{key:x,'aria-pressed':tab===x}))),section(tab,body)),h('aside',null,section('Activity timeline',h('ol',{className:'svc-timeline'},events.slice(0,20).map(x=>h('li',{key:x.id},h('small',null,new Date(x.created_at).toLocaleString(th?'th-TH':'en-GB',{timeZone:'Asia/Bangkok'})),h('strong',null,title(x.new_status||x.kind)),h('p',null,x.message))))))));
 }
 function workload(){return section('Engineer workload',h('div',{className:'svc-table-scroll'},h('table',null,h('thead',null,h('tr',null,['Engineer','Open','Due today','Overdue','SLA warning','Done today','Avg resolution','SLA compliance'].map(x=>h('th',{key:x},x)))),h('tbody',null,(data.profiles||[]).filter(p=>p.is_active!==false).map(p=>{const jobs=rows.filter(t=>t.assigned_to_id===p.id),a=analytics(jobs,[],[],now);return h('tr',{key:p.id},h('td',null,b(p.display_name||p.email,()=>drill({assigned_to_id:p.id}))),h('td',null,a.open),h('td',null,jobs.filter(t=>!isClosed(t)&&day(t.sla_deadline)===day(now)).length),h('td',null,filterTickets(jobs,{kpi:'breached'},now).length),h('td',null,filterTickets(jobs,{kpi:'warning'},now).length),h('td',null,filterTickets(jobs,{kpi:'finished'},now).length),h('td',null,a.resolution==null?'—':money(a.resolution)+' min'),h('td',null,a.compliance==null?'—':money(a.compliance)+'%'));})))));}
 function settings(){if(!can('manage_settings'))return h('p',null,'Settings permission required');return h(React.Fragment,null,section('การตั้งค่าบริการ / Service settings',h(React.Fragment,null,h('p',null,'ประเภทคำขอ · หมวดปัญหา · สถานะ · Priority · Auto assignment · Escalation · Templates · เลขเอกสาร'),b('แก้ไขการตั้งค่า / Edit settings',()=>open('settings')))),section('SLA policies',h(React.Fragment,null,b('+ SLA policy',()=>open('policy')),(data.service_sla_policies||[]).map(p=>h('div',{className:'svc-setting-row',key:p.id},h('span',null,p.name,` · ${p.response_minutes} / ${p.resolution_minutes} min · ${p.calendar?.mode}`),b('Edit',()=>open('policy',p)))))),section('Service teams / Queues',h(React.Fragment,null,b('+ Service team',()=>open('team')),(data.service_teams||[]).map(p=>h('div',{className:'svc-setting-row',key:p.id},h('span',null,p.name,' · ',p.queue),b('Edit',()=>open('team',p)))))));}
 const chooseFiles=h('label',{className:'svc-field wide'},h('span',null,'Attachments · PNG / JPG / WebP / MP4 / PDF / TXT / CSV / ZIP · 25 MB'),h('input',{type:'file',multiple:true,'aria-label':'Attachments',accept:'.png,.jpg,.jpeg,.webp,.mp4,.pdf,.txt,.log,.csv,.zip',onChange:e=>Files([...e.target.files])}));
 function modalBody(){if(modal==='create'||modal==='edit'){const asset=data.assets?.find(x=>x.id===draft.asset_id),customer=data.customers?.find(x=>x.id===draft.customer_id),contact=data.contacts?.find(x=>x.id===draft.contact_id);return h(React.Fragment,null,section('A · ข้อมูลคำขอ / Request',h(React.Fragment,null,h('p',{className:'svc-muted'},'หมายเลขและวันเวลาสร้างให้อัตโนมัติ / Number & opening time assigned on save'),h('div',{className:'svc-fields'},field(['subject','Subject'],true),field(['request_type','Request type',setting.ticket_types]),field(['channel','Channel',setting.channels]),field(['impact','Impact',setting.impact]),field(['urgency','Urgency',setting.urgency]),field(['priority','Priority',setting.priorities])))),section('B · ลูกค้าและสินทรัพย์ / Customer & asset',h(React.Fragment,null,h('div',{className:'svc-fields'},field(['customer_id','Customer','customers'],true),field(['branch_id','Branch / Site','branches']),field(['contact_id','Contact','contacts']),field(['asset_id','Asset / Serial number','assets']),field(['contract_id','Contract','contracts'])),customer&&info(customer,[['code','Customer code'],['address','Address'],['owner_name','Sales owner']]),contact&&info(contact,[['position','Position'],['phone','Phone'],['email','Email']]),asset&&assetInfo(asset))),section('C · ปัญหา / Problem',fields(DESCRIPTORS.problem)),section('D · SLA / Assignment',fields(DESCRIPTORS.assignment)),section('E · Attachments',chooseFiles));}
 if(['repair','claim','part','diagnosis','assignment','problem','team','policy'].includes(modal))return h(React.Fragment,null,fields(DESCRIPTORS[modal]),modal==='policy'&&h(React.Fragment,null,h('label',{className:'svc-field'},h('span',null,'Pause statuses (comma separated)'),h('input',{'aria-label':'Pause statuses',value:(draft.pause_statuses||[]).join(','),onChange:e=>Draft({...draft,pause_statuses:e.target.value.split(',')})})),h('div',{className:'svc-fields'},field(['calendar.mode','SLA calendar',['24x7','business']]),field(['calendar.start_hour','Opening hour (Bangkok)','number']),field(['calendar.end_hour','Closing hour (Bangkok)','number'])),h('label',{className:'svc-field'},h('span',null,'Working weekdays (0=Sunday … 6=Saturday)'),h('input',{'aria-label':'Working weekdays',value:(draft.calendar?.weekdays||[]).join(','),onChange:e=>set('calendar.weekdays',e.target.value.split(',').map(Number))})),h('label',{className:'svc-field'},h('span',null,'Holiday dates (YYYY-MM-DD, comma separated)'),h('textarea',{'aria-label':'Holidays',value:(draft.calendar?.holidays||[]).join(','),onChange:e=>set('calendar.holidays',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}))),['repair','claim'].includes(modal)&&h(React.Fragment,null,field(['attachment_phase','Photo / attachment phase',['before','after','claim','document']]),chooseFiles));
 if(modal==='status')return h(React.Fragment,null,h('p',null,`${statusName(selected.status)} → ${statusName(draft.status)}`),fields([['status','New status',STATUSES.filter(x=>canTransition(selected.status,x))],['service_data.transition_comment','Transition comment','textarea']]),['resolved','customer-confirmed','closed'].includes(draft.status)&&fields(DESCRIPTORS.diagnosis),h('p',{className:'svc-muted'},'Resolved → Customer Confirmed → Closed · งานซ่อมและเคลมต้องเสร็จก่อนปิดเคส'));
 if(modal==='communication')return h(React.Fragment,null,fields([['channel','Channel',['Email','Phone','LINE','Customer Message','Internal Note','Engineer Note']],['recipient_contact_id','Contact','contacts']]),h('label',{className:'svc-field'},h('span',null,'Update template'),h('select',{'aria-label':'Update template',onChange:e=>set('message',(setting.email_templates[e.target.value]||'').replaceAll('{{contact}}',selected.contact_name).replaceAll('{{code}}',selected.code).replaceAll('{{subject}}',selected.subject))},h('option',{value:''},'—'),Object.keys(setting.email_templates).map(x=>h('option',{key:x,value:x},x)))),field(['message','Message','textarea'],true),draft.channel==='Email'&&h('p',{className:'svc-alert'},'บันทึกเป็นร่างอีเมล — ยังไม่มีการส่งจากหน้านี้ / Saved as an email draft. Delivery integration is not configured.'));
 if(modal==='attachment')return h(React.Fragment,null,field(['attachment_phase','Attachment phase',['problem','before','after','claim','log','document']]),chooseFiles);
 if(modal==='quotation'){
 const items=draft.items.map((x,i)=>h('div',{className:'svc-fields',key:i},['name','qty','price'].map(k=>h('label',{className:'svc-field',key:k},h('span',null,title(k)),h('input',{'aria-label':`${k} ${i+1}`,type:k==='name'?'text':'number',min:0,value:x[k],onFocus:e=>e.target.select(),onChange:e=>Draft({...draft,items:draft.items.map((v,j)=>i===j?{...v,[k]:e.target.value}:v)})})))));
 return h(React.Fragment,null,h('p',null,selected.customer_name,' · ',selected.code,' · ',selected.asset.serial_number),h('div',{className:'svc-quote-items'},items),b('+ Service item',()=>Draft({...draft,items:[...draft.items,{name:'',qty:1,price:0,cost:0}]})),h('p',null,'บันทึกเป็นใบเสนอราคาฉบับร่างในโมดูลเดิม / Creates a linked quotation draft'));
 }
 if(modal==='knowledge')return h(React.Fragment,null,info(selected,[['subject','Problem'],['root_cause','Root cause'],['resolution','Solution']]),field(['tags','Tags (comma separated)']));
 if(modal==='settings'){
 const cfg=draft.config,update=(key,val)=>Draft(v=>({...v,config:{...v.config,[key]:val}}));
 const textList=(key,label)=>h('label',{className:'svc-field',key},h('span',null,label),h('textarea',{'aria-label':label,value:(cfg[key]||[]).join('\n'),rows:5,onChange:e=>update(key,e.target.value.split('\n').filter(Boolean))}));
 return h(React.Fragment,null,section('ประเภทคำขอและช่องทาง / Request options',h('div',{className:'svc-fields'},textList('ticket_types','Ticket types · one per line'),textList('channels','Channels · one per line'))),
 section('เลขเอกสาร / Document numbers',h('div',{className:'svc-fields'},Object.entries(cfg.prefixes).map(([k,v])=>h('label',{className:'svc-field',key:k},h('span',null,title(k)+' prefix'),h('input',{'aria-label':`${k} prefix`,required:true,maxLength:20,value:v,onChange:e=>update('prefixes',{...cfg.prefixes,[k]:e.target.value})}))))),
 section('Escalation / Notifications',h('div',{className:'svc-fields'},h('label',{className:'svc-field'},h('span',null,'SLA thresholds (%)'),h('input',{'aria-label':'SLA thresholds',value:(cfg.escalation.thresholds||[]).join(','),onChange:e=>update('escalation',{...cfg.escalation,thresholds:e.target.value.split(',').map(Number)})})),h('label',{className:'svc-field'},h('span',null,'Waiting customer alert (hours)'),h('input',{type:'number',min:1,required:true,'aria-label':'Waiting alert hours',value:cfg.escalation.waiting_hours,onChange:e=>update('escalation',{...cfg.escalation,waiting_hours:Number(e.target.value)})})),h('label',{className:'svc-field'},h('span',null,'In-app notifications'),h('input',{type:'checkbox','aria-label':'In-app notifications',checked:cfg.notifications.enabled,onChange:e=>update('notifications',{enabled:e.target.checked})})))),
 section('Auto assignment',Object.entries(cfg.auto_assignment||{}).map(([category,team])=>h('label',{key:category,className:'svc-field'},h('span',null,category),h('select',{'aria-label':`Team for ${category}`,value:team,onChange:e=>update('auto_assignment',{...cfg.auto_assignment,[category]:e.target.value})},h('option',{value:''},'—'),(data.service_teams||[]).map(x=>h('option',{value:x.name,key:x.id},x.name)))))),
 section('หมวดปัญหา / Problem categories',Object.entries(cfg.categories||{}).map(([category,subs])=>h('div',{key:category},h('h4',null,category),Object.entries(subs).map(([sub,symptoms])=>h('label',{key:sub,className:'svc-field'},h('span',null,sub+' · Symptoms (one per line)'),h('textarea',{'aria-label':`${category} ${sub} symptoms`,value:symptoms.join('\n'),onChange:e=>update('categories',{...cfg.categories,[category]:{...subs,[sub]:e.target.value.split('\n').filter(Boolean)}})})))))),
 section('แม่แบบอัปเดตลูกค้า / Customer update templates',Object.entries(cfg.email_templates||{}).map(([k,v])=>h('label',{key:k,className:'svc-field'},h('span',null,k),h('textarea',{'aria-label':`Template ${k}`,rows:5,value:v,onChange:e=>update('email_templates',{...cfg.email_templates,[k]:e.target.value})})))),
 section('Workflow / Priority',h('p',null,STATUSES.map(statusName).join(' → ')),h('p',null,'Impact + Urgency: Low / Medium / High → Low / Medium / High / Critical')));
 }

 }
 function embeddedSummary(){
 const assets=(data.assets||[]).filter(x=>(!customerId||x.customer_id===customerId)&&(!assetId||x.id===assetId));
 const parts=(data.service_parts||[]).filter(x=>ticketIds.has(x.ticket_id));const history=(data.service_events||[]).filter(x=>ticketIds.has(x.ticket_id)&&x.kind==='asset-replacement');
 return h(React.Fragment,null,h('div',{className:'svc-metrics'},[['Open tickets',summary.open],['Closed tickets',summary.closed],['Repair history',scopedRepairs.length],['Claims',scopedClaims.length],['Service cost',money(summary.repairCost+summary.claimCost)+' ฿'],['Parts replaced',parts.reduce((n,p)=>n+Number(p.quantity),0)],['Recorded downtime',money(rows.filter(x=>x.resolved_at).reduce((n,t)=>n+(new Date(t.resolved_at)-new Date(t.created_at))/3600000,0))+' h'],['Last service',rows.map(x=>x.resolved_at).filter(Boolean).sort().at(-1)?.slice(0,10)||'—']].map(([label,value])=>h('div',{key:label},h('small',null,label),h('strong',null,value)))),
 h('details',null,h('summary',null,'Installed assets · Warranty · Contracts · Next maintenance'),assets.map(a=>section(a.code||a.name,assetInfo(a)))),
 h('details',null,h('summary',null,'Repairs / Claims / Parts history'),jobList('service_repairs','repair',scopedRepairs),jobList('service_claims','claim',scopedClaims),jobList('service_parts','part',parts)),
 history.length>0&&section('Serial replacement history',history.map(x=>h('p',{key:x.id},x.created_at,' · ',x.details?.old_serial||x.message,' → ',x.details?.new_serial||''))));
 }
 const names={'tk-overview':['ภาพรวมบริการ','Service overview'],'tk-all':['เคสบริการ','Service cases'],'tk-repairs':['งานซ่อม','Repair jobs'],'tk-claims':['งานเคลม / RMA','Claims / RMA'],'tk-sla':['ติดตาม SLA','SLA tracking'],'tk-assign':['วิศวกร / การมอบหมาย','Engineer workload'],'tk-report':['การวิเคราะห์บริการ','Service analytics'],'tk-settings':['ตั้งค่าบริการ','Service settings']};
 return h('section',{className:'svc-root','data-service-desk':true},h('header',{className:'svc-header'},h('div',null,h('small',null,'KC CuTo · SERVICE OPERATIONS'),h('h1',null,(names[route]||names['tk-all'])[th?0:1]),h('p',null,txt('ดูแลลูกค้า อุปกรณ์ และงานบริการในที่เดียว','Customers, assets and service work in one place'))),h('div',{className:'svc-toolbar'},b('↻',()=>run(load),{'aria-label':'Refresh service'}),can('export')&&b('Export CSV',exportCSV),b('พิมพ์ / Print',()=>window.print()),can('create')&&b('+ สร้างเคส / Create case',()=>open('create'),{className:'primary'}),can('manage_settings')&&b('⚙',()=>navigate('tickets','tk-settings'),{'aria-label':'Service settings'}))),demoMode&&h('p',{className:'svc-demo'},'ข้อมูลตัวอย่างบริการ · บันทึกเฉพาะเซสชันทดลอง / Demo data · session only'),error&&h('p',{role:'alert',className:'svc-alert'},error),message&&h('p',{role:'status',className:'svc-notice'},message),loaded&&embedded&&!selected&&embeddedSummary(),!loaded?h('p',null,'กำลังโหลด / Loading…'):selected?details():route==='tk-overview'||route==='tk-report'?dashboard():route==='tk-repairs'?jobList('service_repairs','repair'):route==='tk-claims'?jobList('service_claims','claim'):route==='tk-assign'?workload():route==='tk-settings'?settings():route==='tk-sla'?h(React.Fragment,null,workload(),list()):list(),modal&&h(Modal,{name:({create:'สร้างเคส / Create case',edit:'แก้ไขเคส / Edit case',status:'เปลี่ยนสถานะ / Change status',repair:'Repair job',claim:'Claim / RMA',part:'Parts used',diagnosis:'Diagnosis / Resolution',assignment:'Assignment / Appointment',problem:'Problem',communication:'Communication',attachment:'Attachments',quotation:'Create quotation',knowledge:'Knowledge article',settings:'Service settings',policy:'SLA policy',team:'Service team'})[modal],busy,onClose:()=>{ModalState(null);E('');},onSave:submit},error&&h('p',{role:'alert',className:'svc-alert'},error),modalBody()));
 };
}
