import {validatePersonalProfile,PERSONAL_FIELDS} from './profile-document-defaults.mjs?v=20261007-profile';
import {createRecordPopup} from './record-popup.mjs?v=20261004';
import {profileNames,profileDisplayName} from './profile-names.mjs?v=20261002';
export function validateProfilePhoto(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('รองรับรูป PNG, JPG หรือ WebP เท่านั้น');if(file.size>5242880)throw Error('รูปต้องมีขนาดไม่เกิน 5 MB');}
export function createUserProfile({React,client,useApp}){
 const h=React.createElement,Popup=createRecordPopup(React),bucket='crm-profile-photos';
 return function UserProfile({onSignOut}){
  const {profile,session,demoMode,enterDemoMode,syncProfile,lang}=useApp(),[menu,Menu]=React.useState(false),[edit,Edit]=React.useState(null),[photo,Photo]=React.useState(null),[preview,Preview]=React.useState(''),[avatar,Avatar]=React.useState(''),[busy,Busy]=React.useState(false),[error,ErrorText]=React.useState(''),[message,Message]=React.useState('');
  const root=React.useRef(null),busyRef=React.useRef(false),tr=(th,en)=>lang==='th'?th:en;
  const name=profile?.display_name||profile?.email||session?.user?.email||'',initials=name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';
  React.useEffect(()=>{let alive=true;if(!profile?.avatar_path){Avatar('');return;}client.storage.from(bucket).createSignedUrl(profile.avatar_path,3600).then(({data,error})=>{if(alive)Avatar(error?'':data?.signedUrl||'');});return()=>{alive=false;};},[profile?.avatar_path,profile?.updated_at]);
  React.useEffect(()=>{if(!menu)return;const outside=e=>{if(!root.current?.contains(e.target))Menu(false);},key=e=>{if(e.key==='Escape')Menu(false);};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key);};},[menu]);
  React.useEffect(()=>()=>{if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);},[preview]);
  const open=()=>{Menu(false);ErrorText('');Message('');Photo(null);Preview('');Edit({...profile,...profileNames(profile),document_department:profile.document_department||profile.department_group||''});};
  const choose=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{validateProfilePhoto(file);const url=URL.createObjectURL(file),img=new Image();try{img.src=url;await img.decode();}catch{URL.revokeObjectURL(url);throw Error('ไม่สามารถอ่านไฟล์รูปภาพนี้ได้');}Photo(file);Preview(url);Edit(v=>({...v,remove_photo:false}));ErrorText('');}catch(err){ErrorText(err.message);}};
  const save=async e=>{e.preventDefault();if(busyRef.current)return;busyRef.current=true;Busy(true);ErrorText('');Message('');let uploaded=null;try{
   const patch={...validatePersonalProfile(edit),avatar_path:edit.remove_photo?null:profile.avatar_path||null};
   if(demoMode){syncProfile?.({...profile,...patch});if(photo)Avatar(preview);if(edit.remove_photo)Avatar('');Message(tr('บันทึกเฉพาะโหมดทดลอง','Saved in demo only'));Edit(null);return;}
   if(photo){uploaded=profile.id+'/'+crypto.randomUUID()+({ 'image/png':'.png','image/jpeg':'.jpg','image/webp':'.webp'}[photo.type]);const result=await client.storage.from(bucket).upload(uploaded,photo,{contentType:photo.type,upsert:false});if(result.error)throw result.error;patch.avatar_path=uploaded;}
   let query=client.from('profiles').update(patch).eq('id',session.user.id);if(edit.updated_at)query=query.eq('updated_at',edit.updated_at);const {data,error}=await query.select('*').maybeSingle();if(error)throw error;if(!data)throw Error(tr('ข้อมูลเปลี่ยนแล้ว กรุณาปิดแล้วเปิดโปรไฟล์ใหม่','Profile changed. Reopen the form and try again'));
   uploaded=null;if(profile.avatar_path&&profile.avatar_path!==data.avatar_path)await client.storage.from(bucket).remove([profile.avatar_path]);syncProfile?.(data);window.dispatchEvent(new Event('crm-access-changed'));Edit(null);Message(tr('บันทึกโปรไฟล์แล้ว','Profile saved'));
  }catch(err){if(uploaded)await client.storage.from(bucket).remove([uploaded]);ErrorText(err.message);}finally{busyRef.current=false;Busy(false);}};
  const logout=async()=>{ErrorText('');try{if(demoMode){onSignOut();}else{const {error}=await client.auth.signOut();if(error)throw error;}}catch(e){ErrorText(e.message);}};
  const image=(src,size=38)=>src?h('img',{src,alt:tr('รูปโปรไฟล์','Profile photo'),style:{width:size,height:size,flexShrink:0,borderRadius:12,objectFit:'cover'},onError:()=>Avatar('')}):h('span',{style:{display:'grid',placeItems:'center',width:size,height:size,borderRadius:12,background:'#0d9488',color:'white',fontWeight:700}},initials);
  return h('div',{ref:root,style:{position:'relative'}},h('button',{type:'button','aria-label':tr('โปรไฟล์ผู้ใช้','User profile'),'aria-expanded':menu,onClick:()=>Menu(!menu),style:{border:0,padding:0,background:'transparent'}},image(avatar)),menu&&h('section',{'aria-label':tr('เมนูโปรไฟล์','Profile menu'),style:{position:'absolute',right:0,top:48,width:280,maxWidth:'calc(100vw - 32px)',background:'white',padding:18,border:'1px solid #dbe5ef',borderRadius:16,boxShadow:'0 12px 40px #102b4430',zIndex:200}},h('strong',{style:{display:'block',overflowWrap:'anywhere'}},name),h('p',{style:{fontSize:13,color:'#64748b',overflowWrap:'anywhere'}},profile?.email||session?.user?.email),profile?.is_super_admin&&h('p',null,'Super Admin'),h('button',{type:'button',onClick:open,style:{display:'block',width:'100%',padding:10,textAlign:'left'}},tr('แก้ไขโปรไฟล์','Edit profile')),h('button',{type:'button',onClick:logout,style:{display:'block',width:'100%',padding:10,textAlign:'left',color:'#b91c1c'}},tr('ออกจากระบบ','Sign out')),error&&h('p',{role:'alert'},error)),message&&h('span',{role:'status',style:{position:'absolute',right:0,top:48,background:'#ecfdf5',padding:10,width:220,zIndex:199}},message),edit&&h(Popup,{title:tr('โปรไฟล์ของฉัน','My profile'),lang,busy,error,onClose:()=>Edit(null)},
   h('form',{onSubmit:save,className:'crm-personal-profile'},
    h('style',null,'.crm-record-popup:has(.crm-personal-profile){width:min(720px,calc(100vw - 24px))}.crm-personal-profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.crm-personal-profile input:not([type=file]),.crm-personal-profile select{display:block;width:100%;padding:12px;border:1px solid #dce5ee;border-radius:18px;margin-top:7px;background:white}.crm-personal-profile label{font-size:13px;color:#244864}.crm-personal-profile small{display:block;margin-top:6px;color:#71869d;font-size:11px}.crm-personal-photo img,.crm-personal-photo>span{border-radius:50%!important}@media(max-width:560px){.crm-personal-profile-grid{grid-template-columns:1fr}}'),
    h('p',{style:{color:'#71869d',fontSize:13,marginBottom:24}},tr('บันทึกข้อมูลพนักงานเพื่อใช้เป็นค่าเริ่มต้นในทุกแบบฟอร์ม ช่องข้อมูลในร่างที่บันทึกแล้วและเอกสารที่ส่งแล้วจะคงเดิม','Save your employee details as defaults for new documents. Saved drafts and submitted documents keep their original details.')),
    h('div',{style:{display:'flex',alignItems:'center',gap:20,marginBottom:24,flexWrap:'wrap'}},h('div',{className:'crm-personal-photo'},image(edit.remove_photo?'':preview||avatar,100)),
     h('div',null,h('label',{style:{display:'inline-block',border:'1px solid #0aada9',borderRadius:18,padding:'10px 16px',color:'#0aada9',cursor:'pointer'}},tr('เลือกรูปโปรไฟล์','Choose profile photo'),h('input',{type:'file',style:{display:'none'},accept:'image/png,image/jpeg,image/webp',onChange:choose,disabled:busy,'aria-label':tr('เพิ่มรูปโปรไฟล์','Upload profile photo')})),h('button',{type:'button',disabled:busy,onClick:()=>{Photo(null);Preview('');Edit({...edit,remove_photo:true});},style:{marginLeft:14,color:'#f43f5e',border:0,background:'transparent'}},tr('ลบรูป','Remove photo')),h('small',null,'JPG, PNG, WebP · '+tr('ไม่เกิน 5 MB','up to 5 MB')))),
    h('div',{className:'crm-personal-profile-grid'},...PERSONAL_FIELDS.flatMap((key,i)=>[
     h('label',{key},tr(['ชื่อ','นามสกุล','บริษัท / องค์กร','เบอร์โทรศัพท์','ตำแหน่ง','แผนก','รหัสพนักงาน','อีเมลติดต่อ','LINE ID'][i],['First name','Last name','Company / Organization','Phone','Position','Department','Employee code','Contact email','LINE ID'][i]),
      key==='document_department'?h('select',{'aria-label':tr('แผนก','Department'),value:edit[key]||'',disabled:busy,onChange:e=>Edit({...edit,[key]:e.target.value})},h('option',{value:''},tr('เลือกแผนก','Select department')),[...new Set([edit[key],profile.department_group,'ฝ่ายบริหาร','ฝ่ายขาย','ฝ่ายการตลาด','ฝ่ายบัญชี','ฝ่ายการเงิน','ฝ่ายจัดซื้อ','ฝ่ายบริการ','ฝ่ายซอฟต์แวร์','ฝ่ายบุคคล','ฝ่ายคลังสินค้า'].filter(Boolean))].map(value=>h('option',{key:value,value},value))):
      h('input',{'aria-label':tr(['ชื่อ','นามสกุล','บริษัท / องค์กร','เบอร์โทรศัพท์','ตำแหน่ง','แผนก','รหัสพนักงาน','อีเมลติดต่อ','LINE ID'][i],['First name','Last name','Company / Organization','Phone','Position','Department','Employee code','Contact email','LINE ID'][i]),type:key==='contact_email'?'email':key==='phone'?'tel':'text',value:edit[key]||'',maxLength:150,required:i<2,disabled:busy,onChange:e=>Edit({...edit,[key]:e.target.value})}),
      key==='contact_email'&&h('small',null,tr('หากเว้นว่าง จะใช้อีเมลบัญชีเป็นค่าเริ่มต้น','Leave blank to use your account email'))),
     ...(i===1?[h('label',{key:'account-email',style:{gridColumn:'1/-1'}},tr('อีเมลบัญชี','Account email'),h('input',{'aria-label':tr('อีเมลบัญชี','Account email'),value:profile?.email||session?.user?.email||'',readOnly:true,style:{background:'#f1f5f9'}}),h('small',null,tr('ติดต่อผู้ดูแลหากต้องการเปลี่ยนอีเมลหรือสิทธิ์ใช้งาน','Contact an administrator to change your login email or access')))]:[])
    ])),
    h('div',{className:'crm-actions',style:{marginTop:24}},h('button',{type:'button',disabled:busy,onClick:()=>Edit(null)},tr('ยกเลิก','Cancel')),h('button',{type:'submit',disabled:busy,style:{background:'#0aada9',color:'white',border:0,borderRadius:18,padding:'12px 20px'}},busy?tr('กำลังบันทึก…','Saving…'):tr('บันทึกโปรไฟล์','Save')))
   )));
 };
}
