import {createRecordPopup} from './record-popup.mjs?v=20261004';
import {profileNames,profileDisplayName} from './profile-names.mjs?v=20261002';
export function validateProfilePhoto(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('รองรับรูป PNG, JPG หรือ WebP เท่านั้น');if(file.size>2097152)throw Error('รูปต้องมีขนาดไม่เกิน 2 MB');}
export function createUserProfile({React,client,useApp}){
 const h=React.createElement,Popup=createRecordPopup(React),bucket='crm-profile-photos';
 return function UserProfile({onSignOut}){
  const {profile,session,demoMode,enterDemoMode,syncProfile,lang}=useApp(),[menu,Menu]=React.useState(false),[edit,Edit]=React.useState(null),[photo,Photo]=React.useState(null),[preview,Preview]=React.useState(''),[avatar,Avatar]=React.useState(''),[busy,Busy]=React.useState(false),[error,ErrorText]=React.useState(''),[message,Message]=React.useState('');
  const root=React.useRef(null),busyRef=React.useRef(false),tr=(th,en)=>lang==='th'?th:en;
  const name=profile?.display_name||profile?.email||session?.user?.email||'',initials=name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';
  React.useEffect(()=>{let alive=true;if(!profile?.avatar_path){Avatar('');return;}client.storage.from(bucket).createSignedUrl(profile.avatar_path,3600).then(({data,error})=>{if(alive)Avatar(error?'':data?.signedUrl||'');});return()=>{alive=false;};},[profile?.avatar_path,profile?.updated_at]);
  React.useEffect(()=>{if(!menu)return;const outside=e=>{if(!root.current?.contains(e.target))Menu(false);},key=e=>{if(e.key==='Escape')Menu(false);};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key);};},[menu]);
  React.useEffect(()=>()=>{if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);},[preview]);
  const open=()=>{Menu(false);ErrorText('');Message('');Photo(null);Preview('');Edit({...profile,...profileNames(profile)});};
  const choose=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{validateProfilePhoto(file);const url=URL.createObjectURL(file),img=new Image();try{img.src=url;await img.decode();}catch{URL.revokeObjectURL(url);throw Error('ไม่สามารถอ่านไฟล์รูปภาพนี้ได้');}Photo(file);Preview(url);Edit(v=>({...v,remove_photo:false}));ErrorText('');}catch(err){ErrorText(err.message);}};
  const save=async e=>{e.preventDefault();if(busyRef.current)return;busyRef.current=true;Busy(true);ErrorText('');Message('');let uploaded=null;try{
   const first=String(edit.first_name||'').trim(),last=String(edit.last_name||'').trim(),phone=String(edit.phone||'').trim();if(!first||!last)throw Error(tr('กรุณากรอกชื่อและนามสกุล','First and last name are required'));if([first,last,phone].some(x=>x.length>150))throw Error('ข้อมูลยาวเกิน 150 ตัวอักษร');
   const patch={first_name:first,last_name:last,display_name:profileDisplayName(first,last),phone,avatar_path:edit.remove_photo?null:profile.avatar_path||null};
   if(demoMode){syncProfile?.({...profile,...patch});if(photo)Avatar(preview);if(edit.remove_photo)Avatar('');Message(tr('บันทึกเฉพาะโหมดทดลอง','Saved in demo only'));Edit(null);return;}
   if(photo){uploaded=profile.id+'/'+crypto.randomUUID()+({ 'image/png':'.png','image/jpeg':'.jpg','image/webp':'.webp'}[photo.type]);const result=await client.storage.from(bucket).upload(uploaded,photo,{contentType:photo.type,upsert:false});if(result.error)throw result.error;patch.avatar_path=uploaded;}
   let query=client.from('profiles').update(patch).eq('id',session.user.id);if(edit.updated_at)query=query.eq('updated_at',edit.updated_at);const {data,error}=await query.select('*').maybeSingle();if(error)throw error;if(!data)throw Error(tr('ข้อมูลเปลี่ยนแล้ว กรุณาปิดแล้วเปิดโปรไฟล์ใหม่','Profile changed. Reopen the form and try again'));
   uploaded=null;if(profile.avatar_path&&profile.avatar_path!==data.avatar_path)await client.storage.from(bucket).remove([profile.avatar_path]);syncProfile?.(data);window.dispatchEvent(new Event('crm-access-changed'));Edit(null);Message(tr('บันทึกโปรไฟล์แล้ว','Profile saved'));
  }catch(err){if(uploaded)await client.storage.from(bucket).remove([uploaded]);ErrorText(err.message);}finally{busyRef.current=false;Busy(false);}};
  const logout=async()=>{ErrorText('');try{if(demoMode){onSignOut();}else{const {error}=await client.auth.signOut();if(error)throw error;}}catch(e){ErrorText(e.message);}};
  const image=(src,size=38)=>src?h('img',{src,alt:tr('รูปโปรไฟล์','Profile photo'),style:{width:size,height:size,flexShrink:0,borderRadius:12,objectFit:'cover'},onError:()=>Avatar('')}):h('span',{style:{display:'grid',placeItems:'center',width:size,height:size,borderRadius:12,background:'#0d9488',color:'white',fontWeight:700}},initials);
  return h('div',{ref:root,style:{position:'relative'}},h('button',{type:'button','aria-label':tr('โปรไฟล์ผู้ใช้','User profile'),'aria-expanded':menu,onClick:()=>Menu(!menu),style:{border:0,padding:0,background:'transparent'}},image(avatar)),menu&&h('section',{'aria-label':tr('เมนูโปรไฟล์','Profile menu'),style:{position:'absolute',right:0,top:48,width:280,maxWidth:'calc(100vw - 32px)',background:'white',padding:18,border:'1px solid #dbe5ef',borderRadius:16,boxShadow:'0 12px 40px #102b4430',zIndex:200}},h('strong',{style:{display:'block',overflowWrap:'anywhere'}},name),h('p',{style:{fontSize:13,color:'#64748b',overflowWrap:'anywhere'}},profile?.email||session?.user?.email),profile?.is_super_admin&&h('p',null,'Super Admin'),h('button',{type:'button',onClick:open,style:{display:'block',width:'100%',padding:10,textAlign:'left'}},tr('แก้ไขโปรไฟล์','Edit profile')),h('button',{type:'button',onClick:logout,style:{display:'block',width:'100%',padding:10,textAlign:'left',color:'#b91c1c'}},tr('ออกจากระบบ','Sign out')),error&&h('p',{role:'alert'},error)),message&&h('span',{role:'status',style:{position:'absolute',right:0,top:48,background:'#ecfdf5',padding:10,width:220,zIndex:199}},message),edit&&h(Popup,{title:tr('โปรไฟล์ของฉัน','My profile'),lang,busy,error,onClose:()=>Edit(null)},h('form',{onSubmit:save},h('div',{style:{display:'flex',alignItems:'center',gap:16,marginBottom:20,flexWrap:'wrap'}},image(edit.remove_photo?'':preview||avatar,80),h('label',{style:{flex:'1 1 180px',minWidth:0}},tr('เพิ่มรูปโปรไฟล์','Upload profile photo'),h('input',{type:'file',style:{maxWidth:'100%'},accept:'image/png,image/jpeg,image/webp',onChange:choose,disabled:busy,'aria-label':tr('เพิ่มรูปโปรไฟล์','Upload profile photo')}),h('small',null,'PNG, JPG, WebP · 2 MB')),h('button',{type:'button',disabled:busy,onClick:()=>{Photo(null);Preview('');Edit({...edit,remove_photo:true});}},tr('ลบรูป','Remove photo'))),...['first_name','last_name','phone'].map((key,i)=>h('label',{key,style:{display:'block',margin:'14px 0'}},tr(['ชื่อ','นามสกุล','โทรศัพท์'][i],['First name','Last name','Phone'][i]),h('input',{value:edit[key]||'',maxLength:150,required:i<2,disabled:busy,onChange:e=>Edit({...edit,[key]:e.target.value}),style:{display:'block',width:'100%',padding:12,border:'1px solid #cbd5e1',borderRadius:8}}))),h('p',null,tr('อีเมล: ','Email: ')+profile?.email),h('div',{className:'crm-actions'},h('button',{type:'button',disabled:busy,onClick:()=>Edit(null)},tr('ยกเลิก','Cancel')),h('button',{type:'submit',disabled:busy},busy?tr('กำลังบันทึก…','Saving…'):tr('บันทึก','Save'))))));
 };
}
