-- Additive Service Desk on the existing CRM masters. No business rows are seeded.
create table public.crm_service_settings (id text primary key default 'default' check(id='default'), config jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.crm_service_teams (id uuid primary key default gen_random_uuid(), name text not null unique, queue text not null default '', supervisor_id uuid references public.profiles(id), active boolean not null default true);
create table public.crm_service_sla_policies (id uuid primary key default gen_random_uuid(), name text not null unique, response_minutes integer not null check(response_minutes>0), resolution_minutes integer not null check(resolution_minutes>=response_minutes), pause_statuses text[] not null default array['waiting-customer','waiting-vendor','waiting-approval'], calendar jsonb not null default '{"mode":"24x7"}', coverage text not null default '', active boolean not null default true);
insert into public.crm_service_settings(config) values ('{"prefixes":{"ticket":"SR","repair":"REPAIR","claim":"CLAIM","rma":"RMA"},"escalation":{"thresholds":[50,75,90,100],"waiting_hours":48},"notifications":{"enabled":true}}');
insert into public.crm_service_teams(name) values ('Client Support'),('Infrastructure'),('Network & Security'),('Application Support');
insert into public.crm_service_sla_policies(name,response_minutes,resolution_minutes,coverage) values ('Standard 24x7',60,480,'24x7');
alter table public.assets add column product_id text references public.products(id), add column branch_id uuid references public.crm_branches(id), add column assigned_user_id uuid references public.contacts(id), add column purchase_date date, add column installation_date date, add column warranty_type text, add column warranty_provider text, add column vendor text, add column distributor text, add column next_maintenance date;
alter table public.contracts add column service_sla_id uuid references public.crm_service_sla_policies(id);
alter table public.tickets add column request_type text not null default 'Incident', add column channel text not null default 'Phone', add column branch_id uuid references public.crm_branches(id), add column owner_id uuid references public.profiles(id), add column requester_id uuid references public.contacts(id), add column backup_engineer_id uuid references public.profiles(id), add column team_id uuid references public.crm_service_teams(id), add column service_sla_id uuid references public.crm_service_sla_policies(id), add column sla_snapshot jsonb not null default '{}', add column first_response_at timestamptz, add column paused_at timestamptz, add column paused_minutes numeric not null default 0, add column response_paused_minutes numeric not null default 0, add column status_since timestamptz not null default now(), add column impact text not null default 'medium', add column urgency text not null default 'medium', add column service_data jsonb not null default '{}', add column root_cause text, add column action_taken text, add column testing_result text, add column parts_changed boolean not null default false, add column customer_approved boolean not null default false, add column csat integer check(csat between 1 and 5), add column csat_comment text, add column reopened_count integer not null default 0, add column quotation_id uuid references public.quotations(id);
alter table public.tickets drop constraint tickets_status_check;
alter table public.tickets add constraint tickets_status_check check(status=any(array['open','in-progress','pending-customer','resolved','closed','escalated','new','accepted','waiting-customer','waiting-parts','waiting-vendor','cancelled','assigned','acknowledged','diagnosing','waiting-approval','repairing','claim-processing','testing','customer-confirmed']));
alter table public.quotations add column service_ticket_id uuid references public.tickets(id), add column service_asset_id uuid references public.assets(id);
alter table public.crm_knowledge_articles add column service_ticket_id uuid references public.tickets(id), add column product_id text references public.products(id), add column model text, add column error_code text, add column tags text[], add column root_cause text, add column solution text;
create table public.crm_service_repairs (id uuid primary key default gen_random_uuid(), code text unique, ticket_id uuid not null references public.tickets(id), engineer_id uuid references public.profiles(id), status text not null default 'received' check(status in ('received','diagnosing','repairing','testing','completed')), received_at timestamptz not null default now(), started_at timestamptz, finished_at timestamptz, diagnosis text, root_cause text, action_taken text, testing_result text, qc_result text, customer_approved boolean not null default false, cost numeric not null default 0 check(cost>=0), details jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crm_service_claims (id uuid primary key default gen_random_uuid(), code text unique, rma_number text unique, ticket_id uuid not null references public.tickets(id), repair_id uuid references public.crm_service_repairs(id), status text not null default 'preparing' check(status in ('preparing','submitted','vendor-received','inspection','waiting-parts','repair-replacement','shipped-back','received','qc','completed')), claim_type text, vendor text, distributor text, vendor_ticket text, submitted_at timestamptz, courier text, tracking_number text, expected_return date, vendor_response text, replacement_product_id text references public.products(id), replacement_serial_number text, cost numeric not null default 0 check(cost>=0), details jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crm_service_parts (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.tickets(id), repair_id uuid not null references public.crm_service_repairs(id), product_id text references public.products(id), part_no text not null, name text not null, serial_number text, quantity numeric not null check(quantity>0), unit text default 'unit', unit_cost numeric not null default 0 check(unit_cost>=0), selling_price numeric not null default 0 check(selling_price>=0), stock_location text, warranty_part boolean default false, old_part_returned boolean default false, replacement_serial_number text, inventory_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crm_service_events (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.tickets(id), actor_id uuid references public.profiles(id), kind text not null, old_status text, new_status text, message text, details jsonb not null default '{}', created_at timestamptz not null default now());
create table public.crm_service_communications (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.tickets(id), channel text not null check(channel in ('Email','Phone','LINE','Customer Message','Internal Note','Engineer Note')), message text not null check(length(trim(message))>0), recipient_contact_id uuid references public.contacts(id), delivery_status text not null default 'logged' check(delivery_status in ('logged','draft')), author_id uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now());
create table public.crm_service_attachments (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.tickets(id), name text not null, path text not null unique, mime_type text, size_bytes bigint check(size_bytes>0 and size_bytes<=26214400), phase text default 'problem' check(phase in ('problem','before','after','claim','log','document')), uploaded_by uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now());
create table private.crm_service_counters (kind text not null, year integer not null, value bigint not null, primary key(kind,year));
alter table private.crm_service_counters enable row level security;
create table private.crm_service_alerts (ticket_id uuid references public.tickets(id), kind text, cycle timestamptz, primary key(ticket_id,kind,cycle));
alter table private.crm_service_alerts enable row level security;
create or replace function private.crm_service_number(p_kind text) returns text language plpgsql security definer set search_path='' as $$ declare n bigint;y integer:=extract(year from now() at time zone 'Asia/Bangkok');prefix text;begin
 insert into private.crm_service_counters(kind,year,value) values(p_kind,y,1) on conflict(kind,year) do update set value=crm_service_counters.value+1 returning value into n;
 select config->'prefixes'->>p_kind into prefix from public.crm_service_settings where id='default';return coalesce(prefix,upper(p_kind))||'-'||y||'-'||lpad(n::text,6,'0');end $$;
revoke all on function private.crm_service_number(text) from public,anon,authenticated;
create or replace function private.crm_service_engineer() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and is_active and coalesce(custom_role_key,role)='service_engineer') $$;
create or replace function private.crm_service_access(p_id uuid,p_action text) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and private.crm_can('tickets',p_action) and exists(select 1 from public.tickets t where t.id=p_id and (not private.crm_service_engineer() or t.assigned_to_id=auth.uid() or t.backup_engineer_id=auth.uid())) $$;
revoke all on function private.crm_service_engineer(),private.crm_service_access(uuid,text) from public,anon;
grant execute on function private.crm_service_engineer(),private.crm_service_access(uuid,text) to authenticated;
-- Restrictive policies also protect legacy list/export/REST paths.
create policy service_assigned_scope on public.tickets as restrictive for all to authenticated using (not (select private.crm_service_engineer()) or assigned_to_id=(select auth.uid()) or backup_engineer_id=(select auth.uid())) with check(not (select private.crm_service_engineer()) or assigned_to_id=(select auth.uid()) or backup_engineer_id=(select auth.uid()));
-- Reuse permission matrix and existing custom role editor. No existing user is reassigned.
insert into public.custom_roles(role_key,label_th,label_en,description,is_system) values ('service_engineer','วิศวกรบริการ','Service Engineer','Assigned service tickets only',false),('service_supervisor','หัวหน้าบริการ','Service Supervisor','Assignment and SLA',false),('service_manager','ผู้จัดการบริการ','Service Manager','Service management',false),('customer_service','เจ้าหน้าที่บริการลูกค้า','Customer Service','Create and update service requests',false) on conflict do nothing;
insert into public.role_permissions(role_key,module,can_view,can_create,can_edit,can_delete,can_export,can_approve,can_assign,can_manage_settings)
select role_key,'tickets',true,role_key<>'service_engineer',true,false,role_key in ('service_manager','service_supervisor'),role_key in ('service_manager','service_supervisor'),role_key in ('service_manager','service_supervisor'),role_key='service_manager' from public.custom_roles where role_key in ('service_engineer','service_supervisor','service_manager','customer_service') on conflict(role_key,module) do nothing;
-- Lookup access uses existing module permissions, configured for the new roles only.
insert into public.role_permissions(role_key,module,can_view) select r,m,true from unnest(array['service_engineer','service_supervisor','service_manager','customer_service']) r cross join unnest(array['customers','contacts','assets','contracts']) m on conflict(role_key,module) do nothing;
insert into public.role_permissions(role_key,module,can_view,can_create) values('sales_user','tickets',true,true) on conflict(role_key,module) do update set can_view=true,can_create=true;
update public.role_permissions set can_create=true where role_key='sales_manager' and module='tickets';
do $$ declare tab text;begin
 foreach tab in array array['crm_service_settings','crm_service_teams','crm_service_sla_policies','crm_service_repairs','crm_service_claims','crm_service_parts','crm_service_events','crm_service_communications','crm_service_attachments'] loop
 execute format('alter table public.%I enable row level security',tab);execute format('revoke all on public.%I from anon,authenticated',tab);execute format('grant select on public.%I to authenticated',tab);
 if tab in ('crm_service_settings','crm_service_teams','crm_service_sla_policies') then
 execute format('grant insert,update on public.%I to authenticated',tab);
 execute format('create policy service_read on public.%I for select to authenticated using ((select private.crm_can(''tickets'',''view'')))',tab);
 execute format('create policy service_create on public.%I for insert to authenticated with check ((select private.crm_can(''tickets'',''manage_settings'')))',tab);
 execute format('create policy service_update on public.%I for update to authenticated using ((select private.crm_can(''tickets'',''manage_settings''))) with check ((select private.crm_can(''tickets'',''manage_settings'')))',tab);
 else
 execute format('create policy service_read on public.%I for select to authenticated using (private.crm_service_access(ticket_id,''view''))',tab);
 if tab<>'crm_service_events' then
 execute format('grant insert on public.%I to authenticated',tab);
 execute format('create policy service_create on public.%I for insert to authenticated with check (private.crm_service_access(ticket_id,''edit''))',tab);
 if tab not in ('crm_service_communications','crm_service_attachments') then execute format('grant update on public.%I to authenticated',tab);execute format('create policy service_update on public.%I for update to authenticated using (private.crm_service_access(ticket_id,''edit'')) with check (private.crm_service_access(ticket_id,''edit''))',tab);end if;
 end if;end if;end loop;end $$;
create function private.crm_service_minutes(a timestamptz,b timestamptz,cal jsonb) returns numeric language plpgsql immutable set search_path='' as $$ declare d date;lo timestamptz;hi timestamptz;minutes numeric:=0;begin
 if a is null or b is null or b<=a then return 0;end if;
 if coalesce(cal->>'mode','24x7')<>'business' then return extract(epoch from b-a)/60;end if;
 for d in select generate_series((a at time zone 'Asia/Bangkok')::date,(b at time zone 'Asia/Bangkok')::date,'1 day')::date loop
 if coalesce(cal->'weekdays','[1,2,3,4,5]'::jsonb) @> to_jsonb(extract(dow from d)::integer) and not coalesce(cal->'holidays','[]'::jsonb) @> to_jsonb(d::text) then
 lo:=(d+make_interval(hours=>coalesce((cal->>'start_hour')::int,9))) at time zone 'Asia/Bangkok';hi:=(d+make_interval(hours=>coalesce((cal->>'end_hour')::int,18))) at time zone 'Asia/Bangkok';minutes:=minutes+greatest(0,extract(epoch from least(b,hi)-greatest(a,lo))/60);end if;end loop;return minutes;end $$;
create function private.crm_service_due(a timestamptz,mins numeric,cal jsonb) returns timestamptz language plpgsql immutable set search_path='' as $$ declare b timestamptz:=a;remaining numeric:=mins;step numeric;begin
 if coalesce(cal->>'mode','24x7')<>'business' then return a+mins*interval '1 minute';end if;
 -- Bounded by validated SLA/calendar settings; keep exact minute precision.
 for i in 1..1051200 loop exit when remaining<=0;step:=private.crm_service_minutes(b,b+interval '1 minute',cal);b:=b+interval '1 minute';remaining:=remaining-step;end loop;if remaining>0 then raise exception 'SLA calendar has no working time within two years';end if;return b;end $$;
create function private.crm_service_validate_policy() returns trigger language plpgsql set search_path='' as $$ begin
 if new.resolution_minutes>525600 or coalesce(new.calendar->>'mode','24x7') not in ('24x7','business') then raise exception 'Invalid SLA policy';end if;
 if new.calendar->>'mode'='business' and (jsonb_array_length(coalesce(new.calendar->'weekdays','[]'))=0 or coalesce((new.calendar->>'start_hour')::int,9)<0 or coalesce((new.calendar->>'end_hour')::int,18)>24 or coalesce((new.calendar->>'start_hour')::int,9)>=coalesce((new.calendar->>'end_hour')::int,18)) then raise exception 'Calendar requires working weekdays and valid hours';end if;return new;end $$;
create trigger service_policy_guard before insert or update on public.crm_service_sla_policies for each row execute function private.crm_service_validate_policy();
create function private.crm_service_ticket_guard() returns trigger language plpgsql security definer set search_path='' as $$ declare a public.assets;c public.contracts;p public.crm_service_sla_policies;previous text;paused numeric;nexts text[];begin
 if auth.uid() is null then raise exception 'Authentication required';end if;
 if not private.crm_can('tickets',case when tg_op='INSERT' then 'create' else 'edit' end) then raise exception 'Service permission required';end if;
 if tg_op='UPDATE' and not private.crm_service_access(old.id,'edit') then raise exception 'Assigned ticket required';end if;
 if new.customer_id is null or length(trim(new.subject))=0 then raise exception 'Customer and subject are required';end if;
 if new.contact_id is not null and not exists(select 1 from public.contacts where id=new.contact_id and customer_id=new.customer_id) then raise exception 'Contact customer mismatch';end if;
 if new.branch_id is not null and not exists(select 1 from public.crm_branches where id=new.branch_id and customer_id=new.customer_id) then raise exception 'Branch customer mismatch';end if;
 if new.asset_id is not null then select * into a from public.assets where id=new.asset_id; if a.customer_id is distinct from new.customer_id then raise exception 'Asset customer mismatch';end if;new.contract_id:=coalesce(a.contract_id,new.contract_id);new.branch_id:=coalesce(a.branch_id,new.branch_id);end if;
 if new.contract_id is not null then select * into c from public.contracts where id=new.contract_id;if c.customer_id is distinct from new.customer_id then raise exception 'Contract customer mismatch';end if;end if;
 if new.assigned_to_id is not null and not exists(select 1 from public.profiles where id=new.assigned_to_id and is_active) then raise exception 'Active engineer required';end if;
 if tg_op='INSERT' then
 new.code:=private.crm_service_number('ticket');new.created_at:=now();new.owner_id:=auth.uid();new.status:='new';new.resolved_at:=null;new.first_response_at:=null;new.paused_at:=null;new.paused_minutes:=0;new.response_paused_minutes:=0;new.reopened_count:=0;
 new.service_sla_id:=coalesce(case when c.status='active' and c.end_date>=current_date then c.service_sla_id end,new.service_sla_id,(select id from public.crm_service_sla_policies where active order by name limit 1));
 select * into p from public.crm_service_sla_policies where id=new.service_sla_id and active;if p.id is null then raise exception 'Active SLA policy required';end if;new.sla_snapshot:=to_jsonb(p);new.sla_policy:=p.name;new.sla_deadline:=private.crm_service_due(now(),p.resolution_minutes,p.calendar);
 else
 new.code:=old.code;new.created_at:=old.created_at;new.owner_id:=old.owner_id;new.resolved_at:=old.resolved_at;new.first_response_at:=old.first_response_at;new.paused_at:=old.paused_at;new.paused_minutes:=old.paused_minutes;new.response_paused_minutes:=old.response_paused_minutes;new.reopened_count:=old.reopened_count;new.sla_snapshot:=old.sla_snapshot;new.sla_deadline:=old.sla_deadline;new.status_since:=old.status_since;
 if (new.assigned_to_id is distinct from old.assigned_to_id or new.backup_engineer_id is distinct from old.backup_engineer_id or new.team_id is distinct from old.team_id or new.priority is distinct from old.priority or new.service_sla_id is distinct from old.service_sla_id) and not private.crm_can('tickets','assign') then raise exception 'Supervisor assignment permission required';end if;
 if new.service_sla_id is distinct from old.service_sla_id then select * into p from public.crm_service_sla_policies where id=new.service_sla_id and active;if p.id is null then raise exception 'Active policy required';end if;new.sla_snapshot:=to_jsonb(p);new.sla_policy:=p.name;new.sla_deadline:=private.crm_service_due(new.created_at,p.resolution_minutes+new.paused_minutes,p.calendar);end if;
 if old.status='closed' and (to_jsonb(new)-array['updated_at','csat','csat_comment']) is distinct from (to_jsonb(old)-array['updated_at','csat','csat_comment']) then raise exception 'Closed ticket is immutable';end if;
 if new.status is distinct from old.status then
 previous:=case old.status when 'open' then 'new' when 'accepted' then 'acknowledged' when 'pending-customer' then 'waiting-customer' when 'escalated' then 'in-progress' else old.status end;
 if (new.status='closed' and previous<>'customer-confirmed') or (new.status='customer-confirmed' and previous<>'resolved') or (previous='new' and new.status<>'assigned') or (previous='assigned' and new.status<>'acknowledged') or (previous='acknowledged' and new.status<>'diagnosing') or (previous in ('resolved','customer-confirmed') and new.status not in ('diagnosing','customer-confirmed','closed')) or (new.status in ('new','assigned','acknowledged') and not (previous='new' and new.status='assigned' or previous='assigned' and new.status='acknowledged')) or (new.status='resolved' and previous not in ('testing','in-progress','diagnosing','repairing')) then raise exception 'Invalid service workflow: % -> %',previous,new.status;end if;
 if new.status='assigned' and new.assigned_to_id is null then raise exception 'Assign an engineer first';end if;
 if new.first_response_at is null and new.status='acknowledged' then new.first_response_at:=now();end if;
 if old.paused_at is not null then paused:=private.crm_service_minutes(old.paused_at,now(),old.sla_snapshot->'calendar');new.paused_minutes:=old.paused_minutes+paused;if old.first_response_at is null then new.response_paused_minutes:=old.response_paused_minutes+paused;end if;new.paused_at:=null;new.sla_deadline:=private.crm_service_due(now(),greatest(0,(new.sla_snapshot->>'resolution_minutes')::numeric-private.crm_service_minutes(new.created_at,now(),new.sla_snapshot->'calendar')+new.paused_minutes),new.sla_snapshot->'calendar');end if;
 if coalesce(new.sla_snapshot->'pause_statuses','[]') @> to_jsonb(new.status) then new.paused_at:=now();end if;
 new.status_since:=now();if previous in ('resolved','customer-confirmed') and new.status='diagnosing' then new.resolved_at:=null;new.reopened_count:=old.reopened_count+1;end if;
 end if;end if;
 if new.status in ('resolved','customer-confirmed','closed') then
 if nullif(trim(new.resolution),'') is null or nullif(trim(new.root_cause),'') is null or nullif(trim(new.action_taken),'') is null or new.assigned_to_id is null or nullif(trim(new.testing_result),'') is null then raise exception 'Resolution, root cause, action, engineer and testing result required';end if;
 if new.parts_changed and not exists(select 1 from public.crm_service_parts where ticket_id=new.id) then raise exception 'Parts used required';end if;
 if exists(select 1 from public.crm_service_claims where ticket_id=new.id and status<>'completed') then raise exception 'Complete all claims first';end if;
 if exists(select 1 from public.crm_service_repairs where ticket_id=new.id and status<>'completed') then raise exception 'Complete all repairs first';end if;
 new.resolved_at:=coalesce(new.resolved_at,now());end if;
 if new.status='repairing' and a.warranty_end<current_date and not new.customer_approved then raise exception 'Out of warranty: customer approval required';end if;
 if tg_op='INSERT' and not private.crm_can('tickets','assign') then new.assigned_to_id:=null;new.backup_engineer_id:=null;end if;
 new.updated_at:=clock_timestamp();return new;end $$;
revoke all on function private.crm_service_ticket_guard() from public,anon,authenticated;
create trigger aa_service_ticket_guard before insert or update on public.tickets for each row execute function private.crm_service_ticket_guard();
create function private.crm_service_child_guard() returns trigger language plpgsql security definer set search_path='' as $$ declare t public.tickets;states text[]:=array['preparing','submitted','vendor-received','inspection','waiting-parts','repair-replacement','shipped-back','received','qc','completed'];begin
 if auth.uid() is null or not private.crm_service_access(new.ticket_id,'edit') then raise exception 'Service edit permission required';end if;
 select * into t from public.tickets where id=new.ticket_id for update;
 if t.status in ('closed','cancelled') then raise exception 'Ticket is closed';end if;
 if tg_op='UPDATE' and new.ticket_id<>old.ticket_id then raise exception 'Cannot reassign a service record';end if;
 if tg_table_name in ('crm_service_parts','crm_service_claims') and new.repair_id is not null and not exists(select 1 from public.crm_service_repairs where id=new.repair_id and ticket_id=t.id) then raise exception 'Repair ticket mismatch';end if;
 if tg_table_name in ('crm_service_repairs','crm_service_claims') then
 if tg_op='INSERT' then new.code:=private.crm_service_number(case when tg_table_name='crm_service_repairs' then 'repair' else 'claim' end);if tg_table_name='crm_service_claims' then new.rma_number:=private.crm_service_number('rma');end if;
 else new.code:=old.code;new.created_at:=old.created_at;if old.status='completed' then raise exception 'Completed job is immutable';end if;end if;
 if tg_table_name='crm_service_repairs' then
 if new.status='completed' and (nullif(trim(new.diagnosis),'') is null or nullif(trim(new.root_cause),'') is null or nullif(trim(new.action_taken),'') is null or nullif(trim(new.testing_result),'') is null or nullif(trim(new.qc_result),'') is null or new.engineer_id is null) then raise exception 'Complete diagnosis, root cause, action, engineer, testing and QC';end if;
 if new.status='completed' then new.finished_at:=now();end if;
 if new.status in ('repairing','completed') and exists(select 1 from public.assets where id=t.asset_id and warranty_end<current_date) and not t.customer_approved then raise exception 'Customer approval required for out of warranty repair';end if;
 else
 if tg_op='INSERT' and new.status<>'preparing' then raise exception 'Claims start at preparing';end if;
 if tg_op='UPDATE' then new.rma_number:=old.rma_number;if new.status<>old.status and array_position(states,new.status)<>array_position(states,old.status)+1 then raise exception 'Follow the RMA workflow in order';end if;end if;
 if new.status='submitted' then if nullif(trim(new.vendor),'') is null then raise exception 'Vendor required';end if;new.submitted_at:=coalesce(new.submitted_at,now());end if;
 if new.status='completed' and nullif(trim(new.details->>'qc_result'),'') is null then raise exception 'Claim QC result required';end if;
 end if;end if;
 if tg_table_name='crm_service_communications' then new.author_id:=auth.uid();new.created_at:=now();if new.recipient_contact_id is not null and not exists(select 1 from public.contacts where id=new.recipient_contact_id and customer_id=t.customer_id) then raise exception 'Recipient customer mismatch';end if;end if;
 if tg_table_name='crm_service_attachments' then new.uploaded_by:=auth.uid();if split_part(new.path,'/',1)<>t.id::text or not exists(select 1 from storage.objects where bucket_id='service-attachments' and name=new.path) then raise exception 'Uploaded file must belong to this ticket';end if;end if;
 if to_jsonb(new)?'updated_at' then new:=jsonb_populate_record(new,jsonb_build_object('updated_at',clock_timestamp()));end if;
 return new;end $$;
revoke all on function private.crm_service_child_guard() from public,anon,authenticated;
do $$ declare tab text;begin foreach tab in array array['crm_service_repairs','crm_service_claims','crm_service_parts','crm_service_communications','crm_service_attachments'] loop execute format('create trigger service_guard before insert or update on public.%I for each row execute function private.crm_service_child_guard()',tab);end loop;end $$;
create function private.crm_service_audit() returns trigger language plpgsql security definer set search_path='' as $$ declare tid uuid;oldj jsonb:='{}';newj jsonb:=to_jsonb(new);t public.tickets;msg text;begin
 if tg_op='UPDATE' then oldj:=to_jsonb(old);end if;tid:=case when tg_table_name='tickets' then new.id else (newj->>'ticket_id')::uuid end;
 select * into t from public.tickets where id=tid;
 insert into public.crm_service_events(ticket_id,actor_id,kind,old_status,new_status,message,details) values(tid,auth.uid(),tg_table_name,oldj->>'status',newj->>'status',coalesce(newj->'service_data'->>'transition_comment',newj->>'message',newj->>'code',tg_op),jsonb_build_object('record_id',new.id,'before',oldj,'after',newj));
 if tg_table_name='crm_service_claims' and newj->>'status'='completed' and nullif(trim(newj->>'replacement_serial_number'),'') is not null then
 insert into public.crm_service_events(ticket_id,actor_id,kind,message,details) select tid,auth.uid(),'asset-replacement','RMA replacement',jsonb_build_object('asset_id',id,'old_serial',serial_number,'new_serial',newj->>'replacement_serial_number') from public.assets where id=t.asset_id;
 update public.assets set serial_number=newj->>'replacement_serial_number',product_id=coalesce(newj->>'replacement_product_id',product_id),updated_at=now() where id=t.asset_id;
 end if;
 if coalesce((select (config->'notifications'->>'enabled')::boolean from public.crm_service_settings where id='default'),true) then
 if tg_table_name='tickets' or tg_table_name in ('crm_service_claims','crm_service_communications','crm_service_repairs') then
 msg:=case when tg_op='INSERT' then 'New '||tg_table_name when oldj->>'assigned_to_id' is distinct from newj->>'assigned_to_id' then 'Engineer assigned' else coalesce(newj->>'status','Updated') end;
 insert into public.notifications(user_id,type,title,body,related_module,related_id) select distinct u,'service',t.code||' · '||msg,t.subject,'tickets',tid from unnest(array[t.owner_id,t.assigned_to_id,t.backup_engineer_id,(select supervisor_id from public.crm_service_teams where id=t.team_id)]) u where u is not null;
 end if;end if;return new;end $$;
revoke all on function private.crm_service_audit() from public,anon,authenticated;
do $$ declare tab text;begin foreach tab in array array['tickets','crm_service_repairs','crm_service_claims','crm_service_parts','crm_service_communications','crm_service_attachments'] loop execute format('create trigger service_audit after insert or update on public.%I for each row execute function private.crm_service_audit()',tab);end loop;end $$;
-- Time-driven alerts are deduplicated per ticket lifecycle; external channels are intentionally not sent.
create function private.crm_service_sla_alerts() returns void language plpgsql security definer set search_path='' as $$ declare t public.tickets;elapsed numeric;response_elapsed numeric;ratio numeric;threshold integer;kind text;begin
 if not coalesce((select (config->'notifications'->>'enabled')::boolean from public.crm_service_settings where id='default'),true) then return;end if;
 for t in select * from public.tickets where status not in ('closed','cancelled','resolved','customer-confirmed') and sla_snapshot<>'{}' and paused_at is null loop
 elapsed:=greatest(0,private.crm_service_minutes(t.created_at,now(),t.sla_snapshot->'calendar')-t.paused_minutes);
 response_elapsed:=case when t.first_response_at is null then greatest(0,private.crm_service_minutes(t.created_at,now(),t.sla_snapshot->'calendar')-t.response_paused_minutes) else 0 end;
 ratio:=greatest(elapsed/(t.sla_snapshot->>'resolution_minutes')::numeric,response_elapsed/(t.sla_snapshot->>'response_minutes')::numeric)*100;
 for threshold in select jsonb_array_elements_text(coalesce((select config->'escalation'->'thresholds' from public.crm_service_settings where id='default'),'[50,75,90,100]'))::int loop
 if ratio>=threshold then kind:='sla-'||threshold;insert into private.crm_service_alerts values(t.id,kind,t.created_at) on conflict do nothing;
 if found then
 insert into public.crm_service_events(ticket_id,kind,message,details) values(t.id,kind,'SLA escalation '||threshold||'%',jsonb_build_object('team_id',t.team_id));
 insert into public.notifications(user_id,type,title,body,related_module,related_id) select distinct u,'service',t.code||' · SLA '||threshold||'%',t.subject,'tickets',t.id from unnest(array[t.owner_id,t.assigned_to_id,(select supervisor_id from public.crm_service_teams where id=t.team_id)]) u where u is not null;
 end if;end if;end loop;end loop;
 for t in select * from public.tickets where status='waiting-customer' and status_since<now()-make_interval(hours=>coalesce((select (config->'escalation'->>'waiting_hours')::int from public.crm_service_settings where id='default'),48)) loop
 insert into private.crm_service_alerts values(t.id,'waiting-customer',t.status_since) on conflict do nothing;if found then insert into public.notifications(user_id,type,title,body,related_module,related_id) select u,'service',t.code||' · Waiting customer',t.subject,'tickets',t.id from unnest(array[t.owner_id,t.assigned_to_id]) u where u is not null;end if;end loop;
 end $$;
revoke all on function private.crm_service_sla_alerts() from public,anon,authenticated;
select cron.schedule('crm-service-sla-alerts','*/5 * * * *','select private.crm_service_sla_alerts()');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('service-attachments','service-attachments',false,26214400,array['image/png','image/jpeg','image/webp','video/mp4','application/pdf','text/plain','text/csv','application/zip']) on conflict(id) do nothing;
create policy service_files_read on storage.objects for select to authenticated using(bucket_id='service-attachments' and private.crm_service_access(case when split_part(name,'/',1)~'^[0-9a-f-]{36}$' then split_part(name,'/',1)::uuid end,'view'));
create policy service_files_insert on storage.objects for insert to authenticated with check(bucket_id='service-attachments' and private.crm_service_access(case when split_part(name,'/',1)~'^[0-9a-f-]{36}$' then split_part(name,'/',1)::uuid end,'edit'));
-- Index every new foreign key used by RLS/lookups and history screens.
do $$ declare r record;begin for r in select c.relname,a.attname from pg_constraint k join pg_class c on c.oid=k.conrelid join pg_attribute a on a.attrelid=c.oid and a.attnum=any(k.conkey) where k.contype='f' and c.relnamespace='public'::regnamespace and (c.relname like 'crm_service_%' or c.relname in ('tickets','assets','quotations','contracts','crm_knowledge_articles')) loop execute format('create index if not exists %I on public.%I(%I)',left('svc_'||r.relname||'_'||r.attname,63),r.relname,r.attname);end loop;end $$;
create index service_ticket_open_sla on public.tickets(sla_deadline) where status not in ('closed','cancelled');
create index service_event_timeline on public.crm_service_events(ticket_id,created_at desc);
