-- Additive SI role master seed. Existing roles, labels and permission customizations are preserved.
insert into public.custom_roles(role_key,label_th,label_en,description,is_system)
values
 ('sales_director','ผู้อำนวยการฝ่ายขาย','Sales Director','SI default role',false),
 ('account_manager','ผู้จัดการบัญชีลูกค้า','Account Manager','SI default role',false),
 ('key_account_manager','ผู้จัดการลูกค้ารายสำคัญ','Key Account Manager','SI default role',false),
 ('sales_coordinator','ผู้ประสานงานฝ่ายขาย','Sales Coordinator','SI default role',false),
 ('presales_manager','ผู้จัดการพรีเซลส์','Pre-Sales Manager','SI default role',false),
 ('solution_architect','สถาปนิกโซลูชัน','Solution Architect','SI default role',false),
 ('solution_consultant','ที่ปรึกษาโซลูชัน','Solution Consultant','SI default role',false),
 ('presales_engineer','วิศวกรพรีเซลส์','Pre-Sales Engineer','SI default role',false),
 ('product_director','ผู้อำนวยการผลิตภัณฑ์','Product Director','SI default role',false),
 ('product_manager','ผู้จัดการผลิตภัณฑ์','Product Manager','SI default role',false),
 ('product_specialist','ผู้เชี่ยวชาญผลิตภัณฑ์','Product Specialist','SI default role',false),
 ('pmo_manager','ผู้จัดการ PMO','PMO Manager','SI default role',false),
 ('project_manager','ผู้จัดการโครงการ','Project Manager','SI default role',false),
 ('project_coordinator','ผู้ประสานงานโครงการ','Project Coordinator','SI default role',false),
 ('engineering_manager','ผู้จัดการวิศวกรรม','Engineering Manager','SI default role',false),
 ('senior_engineer','วิศวกรอาวุโส','Senior Engineer','SI default role',false),
 ('implementation_engineer','วิศวกรติดตั้งระบบ','Implementation Engineer','SI default role',false),
 ('system_engineer','วิศวกรระบบ','System Engineer','SI default role',false),
 ('network_manager','ผู้จัดการระบบเครือข่าย','Network Manager','SI default role',false),
 ('network_engineer','วิศวกรเครือข่าย','Network Engineer','SI default role',false),
 ('security_manager','ผู้จัดการ Cyber Security','Security Manager','SI default role',false),
 ('security_consultant','ที่ปรึกษา Cyber Security','Security Consultant','SI default role',false),
 ('security_engineer','วิศวกร Cyber Security','Security Engineer','SI default role',false),
 ('cloud_architect','สถาปนิก Cloud','Cloud Architect','SI default role',false),
 ('cloud_engineer','วิศวกร Cloud','Cloud Engineer','SI default role',false),
 ('data_center_engineer','วิศวกร Data Center','Data Center Engineer','SI default role',false),
 ('development_manager','ผู้จัดการพัฒนาซอฟต์แวร์','Development Manager','SI default role',false),
 ('software_developer','นักพัฒนาซอฟต์แวร์','Software Developer','SI default role',false),
 ('frontend_developer','นักพัฒนา Frontend','Frontend Developer','SI default role',false),
 ('backend_developer','นักพัฒนา Backend','Backend Developer','SI default role',false),
 ('fullstack_developer','นักพัฒนา Full Stack','Full Stack Developer','SI default role',false),
 ('qa_manager','ผู้จัดการ QA','QA Manager','SI default role',false),
 ('qa_engineer','วิศวกร QA','QA Engineer','SI default role',false),
 ('software_tester','นักทดสอบซอฟต์แวร์','Software Tester','SI default role',false),
 ('service_desk_manager','ผู้จัดการ Service Desk','Service Desk Manager','SI default role',false),
 ('helpdesk_officer','เจ้าหน้าที่ Helpdesk','Helpdesk Officer','SI default role',false),
 ('support_manager','ผู้จัดการ Technical Support','Technical Support Manager','SI default role',false),
 ('support_engineer','วิศวกร Technical Support','Support Engineer','SI default role',false),
 ('field_engineer','วิศวกรภาคสนาม','Field Engineer','SI default role',false),
 ('ma_engineer','วิศวกร Maintenance / MA','MA Engineer','SI default role',false),
 ('customer_success_manager','ผู้จัดการ Customer Success','Customer Success Manager','SI default role',false),
 ('customer_success_executive','เจ้าหน้าที่ Customer Success','Customer Success Executive','SI default role',false),
 ('procurement_manager','ผู้จัดการจัดซื้อ','Procurement Manager','SI default role',false),
 ('purchasing_officer','เจ้าหน้าที่จัดซื้อ','Purchasing Officer','SI default role',false),
 ('procurement_officer','เจ้าหน้าที่ Procurement','Procurement Officer','SI default role',false),
 ('warehouse_manager','ผู้จัดการคลังสินค้า','Warehouse Manager','SI default role',false),
 ('warehouse_officer','เจ้าหน้าที่คลังสินค้า','Warehouse Officer','SI default role',false),
 ('inventory_officer','เจ้าหน้าที่ Inventory','Inventory Officer','SI default role',false),
 ('logistics_officer','เจ้าหน้าที่ Logistics','Logistics Officer','SI default role',false),
 ('finance_manager','ผู้จัดการการเงิน','Finance Manager','SI default role',false),
 ('finance_officer','เจ้าหน้าที่การเงิน','Finance Officer','SI default role',false),
 ('credit_control','เจ้าหน้าที่ควบคุมเครดิต','Credit Control','SI default role',false),
 ('accounting_manager','ผู้จัดการบัญชี','Accounting Manager','SI default role',false),
 ('senior_accountant','นักบัญชีอาวุโส','Senior Accountant','SI default role',false),
 ('accountant','นักบัญชี','Accountant','SI default role',false),
 ('accounting_officer','เจ้าหน้าที่บัญชี','Accounting Officer','SI default role',false),
 ('hr_manager','ผู้จัดการทรัพยากรบุคคล','HR Manager','SI default role',false),
 ('hr_officer','เจ้าหน้าที่ทรัพยากรบุคคล','HR Officer','SI default role',false),
 ('administration_manager','ผู้จัดการธุรการ','Administration Manager','SI default role',false),
 ('admin_officer','เจ้าหน้าที่ธุรการ','Admin Officer','SI default role',false),
 ('marketing_manager','ผู้จัดการการตลาด','Marketing Manager','SI default role',false),
 ('marketing_executive','เจ้าหน้าที่การตลาด','Marketing Executive','SI default role',false),
 ('digital_marketing_executive','เจ้าหน้าที่ Digital Marketing','Digital Marketing Executive','SI default role',false),
 ('training_manager','ผู้จัดการฝึกอบรม','Training Manager','SI default role',false),
 ('trainer','วิทยากร / Trainer','Trainer','SI default role',false),
 ('technical_consultant','ที่ปรึกษาด้านเทคนิค','Technical Consultant','SI default role',false),
 ('compliance_manager','ผู้จัดการ Compliance','Compliance Manager','SI default role',false),
 ('auditor','ผู้ตรวจสอบ','Auditor','SI default role',false),
 ('viewer','ผู้ใช้งานแบบอ่านอย่างเดียว','Viewer / Read Only','SI default role',false),
 ('external_guest','ผู้ใช้งานภายนอก / Guest','External User / Guest','SI default role',false)
on conflict(role_key) do nothing;

with role_map(role_key,template_role) as (values
 ('sales_director','sales_manager'),
 ('account_manager','sales_user'),
 ('key_account_manager','sales_user'),
 ('sales_coordinator','sales_user'),
 ('presales_manager','sales_manager'),
 ('solution_architect','sales_user'),
 ('solution_consultant','sales_user'),
 ('presales_engineer','sales_user'),
 ('product_director','sales_manager'),
 ('product_manager','sales_manager'),
 ('product_specialist','sales_user'),
 ('pmo_manager','sales_manager'),
 ('project_manager','sales_manager'),
 ('project_coordinator','sales_user'),
 ('engineering_manager','service_agent'),
 ('senior_engineer','service_agent'),
 ('implementation_engineer','service_agent'),
 ('system_engineer','service_agent'),
 ('network_manager','service_agent'),
 ('network_engineer','service_agent'),
 ('security_manager','service_agent'),
 ('security_consultant','service_agent'),
 ('security_engineer','service_agent'),
 ('cloud_architect','service_agent'),
 ('cloud_engineer','service_agent'),
 ('data_center_engineer','service_agent'),
 ('development_manager','service_agent'),
 ('software_developer','service_agent'),
 ('frontend_developer','service_agent'),
 ('backend_developer','service_agent'),
 ('fullstack_developer','service_agent'),
 ('qa_manager','service_agent'),
 ('qa_engineer','service_agent'),
 ('software_tester','service_agent'),
 ('service_desk_manager','service_agent'),
 ('helpdesk_officer','service_agent'),
 ('support_manager','service_agent'),
 ('support_engineer','service_agent'),
 ('field_engineer','service_agent'),
 ('ma_engineer','service_agent'),
 ('customer_success_manager','renewal_owner'),
 ('customer_success_executive','sales_user'),
 ('procurement_manager','finance'),
 ('purchasing_officer','finance'),
 ('procurement_officer','finance'),
 ('warehouse_manager','finance'),
 ('warehouse_officer','finance'),
 ('inventory_officer','finance'),
 ('logistics_officer','finance'),
 ('finance_manager','finance'),
 ('finance_officer','finance'),
 ('credit_control','finance'),
 ('accounting_manager','finance'),
 ('senior_accountant','finance'),
 ('accountant','finance'),
 ('accounting_officer','finance'),
 ('marketing_manager','sales_user'),
 ('marketing_executive','sales_user'),
 ('digital_marketing_executive','sales_user'),
 ('training_manager','sales_user'),
 ('trainer','sales_user'),
 ('technical_consultant','sales_user'),
 ('compliance_manager','executive'),
 ('auditor','executive')
)
insert into public.role_permissions(
 role_key,module,can_view,can_create,can_edit,can_delete,can_export,can_approve,can_assign,can_import,can_manage_settings
)
select m.role_key,p.module,p.can_view,p.can_create,p.can_edit,p.can_delete,p.can_export,p.can_approve,p.can_assign,p.can_import,p.can_manage_settings
from role_map m
join public.role_permissions p on p.role_key=m.template_role
on conflict(role_key,module) do nothing;

with seeded(role_key) as (values
 ('sales_director'),
 ('account_manager'),
 ('key_account_manager'),
 ('sales_coordinator'),
 ('presales_manager'),
 ('solution_architect'),
 ('solution_consultant'),
 ('presales_engineer'),
 ('product_director'),
 ('product_manager'),
 ('product_specialist'),
 ('pmo_manager'),
 ('project_manager'),
 ('project_coordinator'),
 ('engineering_manager'),
 ('senior_engineer'),
 ('implementation_engineer'),
 ('system_engineer'),
 ('network_manager'),
 ('network_engineer'),
 ('security_manager'),
 ('security_consultant'),
 ('security_engineer'),
 ('cloud_architect'),
 ('cloud_engineer'),
 ('data_center_engineer'),
 ('development_manager'),
 ('software_developer'),
 ('frontend_developer'),
 ('backend_developer'),
 ('fullstack_developer'),
 ('qa_manager'),
 ('qa_engineer'),
 ('software_tester'),
 ('service_desk_manager'),
 ('helpdesk_officer'),
 ('support_manager'),
 ('support_engineer'),
 ('field_engineer'),
 ('ma_engineer'),
 ('customer_success_manager'),
 ('customer_success_executive'),
 ('procurement_manager'),
 ('purchasing_officer'),
 ('procurement_officer'),
 ('warehouse_manager'),
 ('warehouse_officer'),
 ('inventory_officer'),
 ('logistics_officer'),
 ('finance_manager'),
 ('finance_officer'),
 ('credit_control'),
 ('accounting_manager'),
 ('senior_accountant'),
 ('accountant'),
 ('accounting_officer'),
 ('hr_manager'),
 ('hr_officer'),
 ('administration_manager'),
 ('admin_officer'),
 ('marketing_manager'),
 ('marketing_executive'),
 ('digital_marketing_executive'),
 ('training_manager'),
 ('trainer'),
 ('technical_consultant'),
 ('compliance_manager'),
 ('auditor'),
 ('viewer'),
 ('external_guest')
), modules(module) as (values ('dashboard'),('leads'),('customers'),('contacts'),('opportunities'),('quotations'),('contracts'),('assets'),('tickets'),('activities'),('documents'),('reports'),('ai'),('settings'))
insert into public.role_permissions(role_key,module)
select s.role_key,m.module from seeded s cross join modules m
on conflict(role_key,module) do nothing;

with role_map(role_key,template_role) as (values
 ('sales_director','sales_manager'),
 ('account_manager','sales_user'),
 ('key_account_manager','sales_user'),
 ('sales_coordinator','sales_user'),
 ('presales_manager','sales_manager'),
 ('solution_architect','sales_user'),
 ('solution_consultant','sales_user'),
 ('presales_engineer','sales_user'),
 ('product_director','sales_manager'),
 ('product_manager','sales_manager'),
 ('product_specialist','sales_user'),
 ('pmo_manager','sales_manager'),
 ('project_manager','sales_manager'),
 ('project_coordinator','sales_user'),
 ('engineering_manager','service_agent'),
 ('senior_engineer','service_agent'),
 ('implementation_engineer','service_agent'),
 ('system_engineer','service_agent'),
 ('network_manager','service_agent'),
 ('network_engineer','service_agent'),
 ('security_manager','service_agent'),
 ('security_consultant','service_agent'),
 ('security_engineer','service_agent'),
 ('cloud_architect','service_agent'),
 ('cloud_engineer','service_agent'),
 ('data_center_engineer','service_agent'),
 ('development_manager','service_agent'),
 ('software_developer','service_agent'),
 ('frontend_developer','service_agent'),
 ('backend_developer','service_agent'),
 ('fullstack_developer','service_agent'),
 ('qa_manager','service_agent'),
 ('qa_engineer','service_agent'),
 ('software_tester','service_agent'),
 ('service_desk_manager','service_agent'),
 ('helpdesk_officer','service_agent'),
 ('support_manager','service_agent'),
 ('support_engineer','service_agent'),
 ('field_engineer','service_agent'),
 ('ma_engineer','service_agent'),
 ('customer_success_manager','renewal_owner'),
 ('customer_success_executive','sales_user'),
 ('procurement_manager','finance'),
 ('purchasing_officer','finance'),
 ('procurement_officer','finance'),
 ('warehouse_manager','finance'),
 ('warehouse_officer','finance'),
 ('inventory_officer','finance'),
 ('logistics_officer','finance'),
 ('finance_manager','finance'),
 ('finance_officer','finance'),
 ('credit_control','finance'),
 ('accounting_manager','finance'),
 ('senior_accountant','finance'),
 ('accountant','finance'),
 ('accounting_officer','finance'),
 ('marketing_manager','sales_user'),
 ('marketing_executive','sales_user'),
 ('digital_marketing_executive','sales_user'),
 ('training_manager','sales_user'),
 ('trainer','sales_user'),
 ('technical_consultant','sales_user'),
 ('compliance_manager','executive'),
 ('auditor','executive')
)
insert into public.dashboard_type_access(role_key,dashboard_type,visible,is_default)
select m.role_key,d.dashboard_type,d.visible,d.is_default
from role_map m
join public.dashboard_type_access d on d.role_key=m.template_role
on conflict(role_key,dashboard_type) do nothing;

with seeded(role_key) as (values
 ('sales_director'),
 ('account_manager'),
 ('key_account_manager'),
 ('sales_coordinator'),
 ('presales_manager'),
 ('solution_architect'),
 ('solution_consultant'),
 ('presales_engineer'),
 ('product_director'),
 ('product_manager'),
 ('product_specialist'),
 ('pmo_manager'),
 ('project_manager'),
 ('project_coordinator'),
 ('engineering_manager'),
 ('senior_engineer'),
 ('implementation_engineer'),
 ('system_engineer'),
 ('network_manager'),
 ('network_engineer'),
 ('security_manager'),
 ('security_consultant'),
 ('security_engineer'),
 ('cloud_architect'),
 ('cloud_engineer'),
 ('data_center_engineer'),
 ('development_manager'),
 ('software_developer'),
 ('frontend_developer'),
 ('backend_developer'),
 ('fullstack_developer'),
 ('qa_manager'),
 ('qa_engineer'),
 ('software_tester'),
 ('service_desk_manager'),
 ('helpdesk_officer'),
 ('support_manager'),
 ('support_engineer'),
 ('field_engineer'),
 ('ma_engineer'),
 ('customer_success_manager'),
 ('customer_success_executive'),
 ('procurement_manager'),
 ('purchasing_officer'),
 ('procurement_officer'),
 ('warehouse_manager'),
 ('warehouse_officer'),
 ('inventory_officer'),
 ('logistics_officer'),
 ('finance_manager'),
 ('finance_officer'),
 ('credit_control'),
 ('accounting_manager'),
 ('senior_accountant'),
 ('accountant'),
 ('accounting_officer'),
 ('hr_manager'),
 ('hr_officer'),
 ('administration_manager'),
 ('admin_officer'),
 ('marketing_manager'),
 ('marketing_executive'),
 ('digital_marketing_executive'),
 ('training_manager'),
 ('trainer'),
 ('technical_consultant'),
 ('compliance_manager'),
 ('auditor'),
 ('viewer'),
 ('external_guest')
), dashboards(dashboard_type) as (values ('my'),('sales'),('manager'),('exec'),('service'),('renewal'),('admin'),('ai'))
insert into public.dashboard_type_access(role_key,dashboard_type,visible,is_default)
select s.role_key,d.dashboard_type,false,false from seeded s cross join dashboards d
on conflict(role_key,dashboard_type) do nothing;
